### ISSUE TITLE
Unairy union gives errors

### ISSUE THREAD

**Issue by kbruneel** [bjornharrtell/jsts#116]
Hi,

The following code gives error "Cannot call method 'getFactory' of undefined".

var topPoly = new jsts.geom.GeometryCollection(top);
topPoly = topPoly.union();

This is because on line
https://github.com/bjornharrtell/jsts/blob/master/src/jsts/operation/union/CascadedPolygonUnion.js#L89

this.geomFactory = this.inputPolys[0].getFactory();

this.inputPolys is not an array, but some other collection. If I change this line to 

this.geomFactory = this.inputPolys.get(0).getFactory();

Its fixed, but the I get an error on line 99 for the same reason. If I fix that error occur further down the code.

I'm very new to jsts.js, so I didn't dig any deeper. It seems to me that some refactoring was not fully executed.

Is there a way to work around this?

Cheers
Karel

Ps: Great library!

**Comment by joseluistorres** [comment]
If someone is looking for an example to use CascadedPolygonUnion with Leaflet Polygons here is one:
```
      $geometries = []
      geo = L.geoJson({features:[]})
      
      $.each(geo._layers, function(i, layer) {
        var reader = new jsts.io.GeoJSONReader();
        $geometries.push(reader.read(JSON.stringify( layer.toGeoJSON().geometry )))
      });

      checker = jsts.operation.union.CascadedPolygonUnion.union($geometries)
```
