### ISSUE TITLE
Union resulting in two holes with shared node yields invalid result

### ISSUE THREAD

**Issue by schmidtc** [bjornharrtell/jsts#135]
Given,
wkt = new jsts.io.WKTReader(),
A = wkt.read("POLYGON((0 0, 0 8, 8 8, 8 0, 0 0), (4 4, 2 4, 2 6, 6 6, 6 2, 4 2, 4 4))");
B = wkt.read("POLYGON((4 4, 4 6, 6 6, 6 4, 4 4))");
C = A.union(B);

Excepted Result:
C.toString() === "POLYGON((0 0, 0 8, 8 8, 8 0, 0 0), (4 6, 2 6, 2 4, 4 4, 4 6), (4 4, 4 2, 6 2, 6 4, 4 4))"

Actual result:
C.toString() === "POLYGON((0 0,0 8,8 8,8 0,0 0))"

Probably related,
D = wkt.read("POLYGON((0 0, 0 8, 8 8, 8 0, 0 0), (4 6, 2 6, 2 4, 4 4, 4 6), (4 4, 4 2, 6 2, 6 4, 4 4))")
D.buffer(0).toString() === "POLYGON((0 0,0 8,8 8,8 0,0 0))"

**Comment by sbatezat** [comment]
I've got this issue too (http://gis.stackexchange.com/questions/109938/jsts-union-on-polygons-with-holes).
Any update?

**Comment by bjornharrtell** [comment]
No progress yet, I expect this to be a non-trivial issue if JTS produces another (correct) result. Would of course like to see it fixed but my free time priorities are elsewhere.

**Comment by bjornharrtell** [comment]
Ignoring my own priorities I had a look at this and found the issue, holes was thrown away in the process because of badly ported code. Fixed in master.

**Comment by sbatezat** [comment]
Many thanks bjornharrtell! For your quick answer, your quick fix, and your hard work on this library, as you said, ignoring your own priorities.
