### ISSUE TITLE
Union of polygons that touch each other doesn't work properly

### ISSUE THREAD

**Issue by carmnu** [bjornharrtell/jsts#148]
Hi, I have tested your library in the last few days. It's excellent but I think I have found a problem concerning the poligons union: if they touch each other but they don't overlap the union function doesn't work as the original JTS library.

I'd really appreciate if you could fix the problem. Thank you for your attention.

Best regards,

Carmine

**Comment by bjornharrtell** [comment]
Could you provide a test case or at least example data to demonstrate the problem?
