### ISSUE TITLE
Speed drop in Firefox

### ISSUE THREAD

**Issue by cpsTinK** [bjornharrtell/jsts#171]
When I make buffers and then combine them, Firefox performs calculation up to 20 times slower than Chrome.
I wonder is it some part of jsts, that contains non-optimized code for Firefox? Can it be improved?
            
            // vars
            var area, buffer, i, line, a, j, n;
            var count = 10; // count test

            // test: buffer blocks track
            time = 0;
            for ( i = 0; i < count; i++ ) {
                console.time(1)
                var buffers = [];
                // create buffers
                for ( j = 0, l = GeoJSON_lines.length; j < l; j++ ) {
                    line = jstsParserGeoJSON.read( GeoJSON_lines[ j ] );
                    buffers[ j ] = line.buffer( bufferDistance_Geodesic, bufferDetail, bufferParameters );
                }
                // union blocks
                while ( j > 1 ) {
                    n = Math.floor( j / 2 );
                    for ( a = 0, b = 0; a < n; a++, b += 2 )
                        buffers[ a ] = buffers[ b ].union( buffers[ b + 1 ] );
                    if ( ( n * 2 ) < j )
                        buffers[ --a ] = buffers[ a ].union( buffers[ j - 1 ] );
                    j = n;
                }
                buffer = buffers[ 0 ];
                area = buffer.getArea();
                console.timeEnd(1)
            }

**Comment by bjornharrtell** [comment]
Just to make sure, which version are you using? The buffer op was optimized lately.

More generally the code is probably quite suboptimal since it's s straight port of Java. I have no plan to reimplement with more optimal code (would be a very large project IMO). There is no special case handling for Chrome.

**Comment by cpsTinK** [comment]
I used version 0.13.2. I checked version 0.15.0 and result is excellent! Now it's executed only 5 seconds in Firefox, and it is fast enough in comparison with former results (30 seconds)!
