### ISSUE TITLE
Merging two or more buffers in one  point

### ISSUE THREAD

**Issue by HtmlRanger** [bjornharrtell/jsts#172]
Hi! Is it possible to merge the two buffers at one point? For Example:
<pre>
         var reader = new jsts.io.WKTReader ();

         var input = reader.read ('LINESTRING (100 100, 100 300)');
         var params = new jsts.operation.buffer.BufferParameters (1,2,2,1);
         var buffer = jsts.operation.buffer.BufferOp.bufferOp2 (input, 15, params);

         var params2 = new jsts.operation.buffer.BufferParameters (1,2,2,1);
         var input2 = reader.read ('LINESTRING (100 100, 300 300)');
         var buffer2 = jsts.operation.buffer.BufferOp.bufferOp2 (input2,35, params2);
</pre>
Connected as follows:
<img src = "http://i9.pixs.ru/storage/9/4/9/1jpg_1924882_16014949.jpg">
And I need something like this:
<img src = "http://i9.pixs.ru/storage/9/5/5/2jpg_9438344_16014955.jpg">
Multylinestring I will not work, because the buffers can be of different thickness. Is that possible?

**Comment by bjornharrtell** [comment]
Not sure I understand the requirements fully but my guess is that what you want is beyond what is implemented.

**Comment by dr-jts** [comment]
Agreed.  This is beyond the scope of how Buffer works.  

If the use case is really as simple as shown (e.g. rectilinear line segments) then it wouldn't be too hard to compute the required segment "buffers" explicitly and then use union to merge them.

**Comment by HtmlRanger** [comment]
Ok, ask another question. Is it possible to make MultyLineString c segments of different thicknesses?
