### ISSUE TITLE
intersects() returns true when it shouldn't

### ISSUE THREAD

**Issue by aflorendo** [bjornharrtell/jsts#175]
Hi,

In the following code, jsts says the following 2 geometries (see image below) intersect when they actually don't.
The intersection method correctly returns GEOMETRYCOLLECTION EMPTY.
Issue seems to occur when one of the geometries is a rectangle and the envelopes of the 2 geometries intersect.

var jsts = require('jsts');
var wktReader = new jsts.io.WKTReader();

var geo1 = wktReader.read('POLYGON ((0 7,3 7,3 10,0 10,0 7))');
var geo2 = wktReader.read('POLYGON ((0 0,10 0,10 10,0 0))');

console.log('geo1.intersects(geo2):', geo1.intersects(geo2));
console.log('geo1.intersection(geo2):', geo1.intersection(geo2).toString());

//// output
//geo1.intersects(geo2): true
//geo1.intersection(geo2): GEOMETRYCOLLECTION EMPTY

![image](https://cloud.githubusercontent.com/assets/7597152/7593407/c1599316-f88e-11e4-9c28-6ceb5c338848.png)

Thank you,
Arnold

**Comment by bjornharrtell** [comment]
Thanks for the detailed report. I've been able to reproduce the issue.

**Comment by bjornharrtell** [comment]
Managed to fix the issue, there was multiple problems in the port for the optimized case with rectangles. Unfortuneatly there still seem to be an issue with more complex cases - the case "AA - A-hole contains B, boundaries touch in line" in TestRelateAA fail with the new code. I guess that case wasn't hitting the optimized code earlier.

**Comment by aflorendo** [comment]
Thank you!!

**Comment by bjornharrtell** [comment]
Found the other case, all tests passing. :) Closing..
