### ISSUE TITLE
'fs.readFileSync' error in browser if installing through npm

### ISSUE THREAD

**Issue by w8r** [bjornharrtell/jsts#176]
Beginning from 0.15.0 you cannot install jsts as an npm module to use with browserify.
```
Uncaught TypeError: fs.readFileSync is not a function
```
Systems: Mac OS X 10.10.2, Win 8.1
It's caused by bower build in javascript.utils and both commonjs `require`s and `goog.require` I guess. Duplicating the issue here to get more attention.

bjornharrtell/javascript.util#9

**Comment by bjornharrtell** [comment]
Thanks for the report. Seems I'm not quite grasping how to set up the closure library code to properly work for both the browser and nodejs. I think it might be for the best to convert the code to simply use browserify.

**Comment by w8r** [comment]
but it did work before grunt was introduced as the build system. It must be solvable, perhaps by compiling the GC code first and then browserifying separately. Now it looks like nodejs adaptor is included anyway

**Comment by bjornharrtell** [comment]
I see and agree if there is an easy fix to the current setup scrapping closure could be avoided.

**Comment by bjornharrtell** [comment]
@w8r I do not have a setup to reproduce the problem, can you provide that or step by step instructions on how to reproduce?

**Comment by w8r** [comment]
I created a repo to showcase the bug: https://github.com/w8r/jsts-browserify

Reproduce steps:
```
git clone https://github.com/w8r/jsts-browserify.git
cd jsts-browserify
npm install
npm start
```
It'll open the page with the browserified bundle and if you open console you'll see that the error right away

**Comment by bjornharrtell** [comment]
Thanks, no problem reproducing the issue now.

**Comment by bjornharrtell** [comment]
Hopefully resolved upstream. See bjornharrtell/javascript.util/issues/9.
