### ISSUE TITLE
Automatic port

### ISSUE THREAD

**Issue by bjornharrtell** [bjornharrtell/jsts#178]
It would be nice and probably possible to convert the upstream Java source to JavaScript using automatic methods. I've got a prototype up and running (https://github.com/bjornharrtell/jsts/tree/1.0.0-wip) using java2estree and astring to convert the original source.

Some changes to the original source was needed, recording them here:
1. Removal of circular dependencies involving class hierarchies (i.e Geometry operation methods) (NOTE: can be worked around by monkey patching Geometry as a separate module)
2. Do not use on demand imports (import with * symbol)
3. Rename fields to not have the same name as methods
4. Remove reliance on null argument resolution for overloads (for example the GeometryFactory methods and friends when creating empty geometries)
5. Avoid overloading on methods with more than 3 arguments (addFillet in OffsetSegmentGenerator) (NOTE: should be possible to handle in translation)
6. If overloading inherited method(s), all inherited method signatures must be defined in subclass (CoordinateList, RobustLineIntersector) (NOTE: should be possible to handle in translation)
7. Do not use inner classes (can be replaced with static inner classes + dependency injection)
8. Use alternative to Clonable and/or Object.clone (replace with custom copy impl.)
9. Do not rely on comparison operator for PrecisionModel Type comparisons

First version of modified original source (obsolete, patches in separate branches):
https://github.com/bjornharrtell/jts-topo-suite/tree/no_circular_deps

java2estree:
https://github.com/bjornharrtell/java2estree

**Comment by bjornharrtell** [comment]
I have looked at VJET, GWT. VJET was promising but there was some parts missing still and now it seems dead. GWT might work someday but I can't get past the initial requirement that it needs an entry point to compile and will only compile it's dependencies.

**Comment by dr-jts** [comment]
At one point there was a thought about using Google AWT to do this.  Have you tried this?

I'm open to the idea of minor additions/enhancements to JTS if it makes it easier to do this.  In an ideal world those would also enable automatic conversion to other langs as well (C++, .NET, etc...). But that's probably a bit of a pipe dream.

**Comment by dr-jts** [comment]
The GWT requirement for a single entry point is a bit of a blocker for sure.  Is it possible to make a stub entry point that simply requires all the desired JTS packages?

**Comment by bjornharrtell** [comment]
I was not aware of GWT-AWT and haven't looked at it, but is AWT really relevant?

About plain GWT there is also the problem that compiled code is not exported to be accessable from JavaScript unless using JSNI which has limitations. There are prior art to automate JSNI exporting at https://code.google.com/p/gwt-exporter but I suspect you would hit lots of cases that it cannot handle. Might deserve a proper up to date evaluation though.

**Comment by dr-jts** [comment]
Sorry, I meant plain old GWT..  

Good point about the output from GWT being boxed in by JSNI.  Annoying... since clearly the key transpiler technology is in there.  Seems like there should be *some* way to make the JS output usable as a standalone module - but could be finicky to make work.  I guess it's not a priority for the Goog.

**Comment by bjornharrtell** [comment]
I tried to get GWT-exporter to work but failed. From what I can read it still misses support for collection types with probably is a big issue. The other big issue I see is that GWT outputs browser specific code with lots of bootstrapping stuff.

Perhaps another options is to look for a more clean AST representation toolset that works with both Java and JavaScript (perhaps there is one inside of GWT...)

**Comment by bjornharrtell** [comment]
Still find this subject interesting and is looking at generating ESTree (1) from Java then generate JavaScript from ESTree with something like https://github.com/davidbonnet/astring. Cannot find anything that generates ESTree from Java though... and would not be a small task to write but I'm considering trying.

1) https://github.com/estree

**Comment by dr-jts** [comment]
Have you seen https://github.com/metteo/jts?  This is a apparently a modified version of JTS which runs in GWT.  The developer was recently in contact with me and says that the next GWT 3.0 will be called j2cl and is a Java to Closure transpiler which "will have built in support for exporting Java APIs into JavaScript (JsInterop) by adding source only annotations on classes / interfaces ".

There's also this: http://jts4gwt.sourceforge.net/

**Comment by dr-jts** [comment]
https://github.com/metteo/jts has a number of changes to JTS src, but none seem radical.  Potentially these issues might go away with j2cl, or perhaps could be folded into base JTS.

 - splitting JTS into modules (core - common code, jvm - awt and some io classes, gwt - gwt specific additions / replacements)
 - 13 clone methods wrapped with //#if CLONE - //#endif and commented out for gwt module (core project still has them)
 - ~13 copy methods and constructors added in core classes which provide same functionality as clone but also work in gwt.
 - ByteArrayOutputStream in WKBWriter replaced with similar ByteArrayOutStream (internal change only for gwt module)
 - Character.isWhitespace() changed to Character.isSpace() in DoubleDouble (only for gwt module, this would have to be improved)
 - 1 use of Class#isAssignableFrom() replaced with lookup from predefined register (only for gwt module)
 - StreamTokenizer in WKTReader replaced with customized WKTTokenizer (also in core, but that could be changed easily)
 - DecimalFormat usage is replaced with gwt specific NumberFormat (only for gwt module)

**Comment by bjornharrtell** [comment]
Thanks haven't seen those. https://github.com/gwtproject/gwt/blob/master/dev/core/src/com/google/gwt/dev/jjs/JavaToJavaScriptCompiler.java looks promising so it will be interesting to see how that develops.

**Comment by bjornharrtell** [comment]
Started my own experiment with https://github.com/bjornharrtell/java2estree and it does seem to work for simple classes already. Will I finish it before Google? :)

**Comment by bjornharrtell** [comment]
Pretty good progress. Would probably be close to done if it weren't for Java overloading. Curse it!

**Comment by bjornharrtell** [comment]
So I cracked overloading and got trivial stuff (Coordinate, Envelope) working with generated code... then, with Geometry and related, I get in serious trouble with circular dependencies. Throwing in the towel I guess.

**Comment by bjornharrtell** [comment]
Seems I'm not giving up after all. I've partly tackled the circular dependency problem and even managed to get as far as a working GeometryFactort.createPoint.

**Comment by dr-jts** [comment]
Excellent!  Keep up the good work....

**Comment by bjornharrtell** [comment]
Thanks :) It's starting to get really promising now. Completely solved the circular dependency problem and can now create LineStrings too. Remaining issues seem almost trivial! (famous last words) 

Started a branch that contains the current output https://github.com/bjornharrtell/jsts/tree/1.0.0-wip

Assuming I will fully succeed in finite time there might be some desired adjustments to the Java source, similar as was required for GWT compatibility but not exactly the same issues. For instance on demand imports (package.*) are problematic but those can be fixed automatically by Eclipse.

**Comment by bjornharrtell** [comment]
Jumped the gun. Circular dependencies still bites me, I just postponed the effects it seems :(

I've researched it quite a bit and either get half baked solutions or hardliners saying the fix is to "refactor away the circular dependencies". I'm not sure how the Java compiler manages to deal with this but one day I'll find out I guess. I'm guessing that to actually refactor JTS to reduce/remove the circular dependencies is probably out of the question. One glaring example is that Geometry references its subclassed geometries.

**Comment by bjornharrtell** [comment]
So I think my mistake was that I was trying to treat each class as a separate module when in fact the whole should be treated as module, at least in the sense of the core jts classes. To my current understanding this is why the manually ported code works. It should be possible to generate code as a single module. Unfortunately this sets me back quite a bit.

On a side node, the definition of modules isn't universal of course but I'm guessing similar dependency restrictions will probably apply to the module support forthcoming in Java 9 (project Jigsaw).

**Comment by dr-jts** [comment]
Makes sense about "treating the whole as a module".  In fact there's a fair bit of implicit modularization in JTS now (in the sense that there's a set of core algorithms and data structures, and then various operations that depend on that core.  I have thought it would be nice to make this structure more explicit in some way.  If this was exposed in JSTS it might also be something that would make JS devs happy, in that they could then easily use only parts of JSTS.

Happy to discuss this idea further...

**Comment by dr-jts** [comment]
re the dependency of Geometry on subclasses... this should be easy to remove, and I think it's a good thing to do so.  If you have a list of other problem areas let me know and I can review whether/how they can be addressed.

**Comment by bjornharrtell** [comment]
Agreed, it would be great to be able to truly modularise JTS. But I'm not sure sure about the easy part. Did you consider that it might not be enough to remove the direct usage of subclasses in Geometry but also all the shortcuts to operations that Geometry have because of indirect dependencies? Alot of public API breakage.

**Comment by dr-jts** [comment]
Yeah, it's probably not possible (now) to separate Geometry from the subclasses.  But is that problem gone if you can group classes into a module?  It seems like it makes sense that all Geometry classes are grouped together as a unit.

In JTS-NG Geometry & subclasses become interrfaces.  And a goal is to abstract algorithms away from the implementations of geometry subclasses.  This should improve modularity.

**Comment by bjornharrtell** [comment]
Yeah I think it make sense that algorithms and datastructures depend on the geometry core as a single module (that might or might not be broken up internally as submodules), mostly because I think it's possible to reduce the geometry core to something quite small. What really needs to be gone is dependencies *from* geometry core *to* the algorithms and datastructures. For example, Geometry.isValid pulls in alot of the algorithms and datastructures which in turn depends on Geometry subclasses to make the matter worse (circular).

Interfaces might be a good pattern in Java but in JavaScript.. a duck is a duck if it quacks. :) I'm not a good Java programmer so I'm not sure what to recommend, but some libraries/frameworks seem to become lost in a sea of interfaces if you know what I mean...

**Comment by dr-jts** [comment]
Hmm, yeah, I think I understand the problem.  Seems like the issue is that Geometry supplies a whole bunch of methods which are really calls to operation classes.  It's convenient to have them as methods (rather than "free-floating" as static functions somewhere else), but it does introduce a circular dependency.  

Unfortunately I don't know of any really clean way to keep the methods but remove the dependency.  Reflection is one way, but it's a bit of a hack.  Or the operation calls can be hidden behind (yet another 8) interface, which can be implemented by a class supplied somewhere else (eg in the GeometryFactory).  There would still be a static dependency in the code, but it would be much smaller and could be special-cased out of the conversion code?

**Comment by dr-jts** [comment]
Actually I was thinking of doing just this in JTS-NG.  The original goal was to make the operations dependency explicit and more dynamic, so that different sets of operations could be bound at runtime.  An example use case is to switch to using geodetic operations for geographic coordinates.  This conversation lends weight to this being a useful thing to do.

**Comment by sweco-sebhar** [comment]
It sounds like you want to write JTS-NG in a dynamic language :)

Seriously I think interfaces provides little more than formality and that you will need to resort to reflection if you truly want to make things pluggable in runtime which I think is a dangerous/difficult path (in Java).

On modularisation in Java I'd like to think of it simply as what code should go in what jar and to keep dependencies one-way.

**Comment by bjornharrtell** [comment]
It sounds like you want to write JTS-NG in a dynamic language :)

Seriously I think interfaces provides little more than formality and that you will need to resort to reflection if you truly want to make things pluggable in runtime which I think is a dangerous/difficult path (in Java).

On modularisation in Java I'd like to think of it simply as what code should go in what jar and to keep dependencies one-way.

**Comment by dr-jts** [comment]
Oh no - Java all the way for JTS-NG baby!  Besides Java is going functional now...  8^)

Given the presence of operation methods on Geometry I don't think it's possible to have strictly one-way dependency between JARs, but it can be slimmed down to a point where it should be easy to port.  

I guess another issue is partioning operations so only the ones needed can be loaded.  This isn't really a concern in Java-land, since there are really no constraints on load module size.  For JS this might have to be addressed by special code in the port.

**Comment by bjornharrtell** [comment]
On the JVM, I much prefer Scala to Java ;) But for JTS I think Java makes sense, even for JTS-NG.

I  think you should consider the benefits of removing the operation methods on Geometry, at least for JTS-NG, with the aim to get rid of any circular dependencies. I'm actually making a fork right now that removes the geom ops as methods, as an experiment.

**Comment by bjornharrtell** [comment]
Experimental fork done. Moved all methods to become statics on RelateOp and OverlayOp respectively and replaced all old use to use the new statics (it's not that many places). Also removed the Comparable interface and impl. to get rid of the circular dependency on geometry subclasses. About an hours work I would say, so it's not too bad. Code compiles and buffers can be created :)

**Comment by dr-jts** [comment]
Dropping operation methods from Geometry is something to think about in JTS-NG.

I'd prefer to keep the Comparable interface.   Probably the subclass references can be removed by replacing them with abstract methods implemented by subclasses.

**Comment by bjornharrtell** [comment]
Ah yes, I removed the comparable interface because it was the easiest thing to do for my experimentation. I'll report back if this refactoring will resolve the automatic port issues.

**Comment by bjornharrtell** [comment]
It seems the changes had the desired effect when translating to JavaScript. No more (apparent) issues with circular dependencies and I can even run RelateOp and BufferOp even if they give unexpected results or crashes but those seem to be attributed to more specific Java to JavaScript translation issues that I think I can work out sooner or later.

I have no desire to maintain a fork of JTS... but I'll still try to complete the automatic porting stuff, it's just too much fun to not do. :)

Thanks for the discussions, much appreciated, and I look forward to future developments.

**Comment by dr-jts** [comment]
Great!  I'll look forward to hearing about a fully running prototype.  And will definitely try and accommodate this goal in JTS-NG, if not sooner.

Even if a fork is needed in the short term, that might be an easier path to generating JSTS than hand-rolling JS code.  The fork would be fairly minimal and easily testable.  It would also be quite stable, since the core Geometry classes rarely change.

**Comment by bjornharrtell** [comment]
Friday evening work has payed off. Already got to a major milestone - basic RelateOp functionality! For now it will only work with Point geometries but still, I think this is very promising.

Published prototypes built for browser use here:
http://bjornharrtell.github.io/jsts/prototype/basic.html
http://bjornharrtell.github.io/jsts/prototype/relate.html

The application code is at top of the bundled (unminified) js that is included in basic.html and in the bottom of the js in relate.html (for some reason). The basic example creates some geometries and envelopes, relate runs intersects (moved from Geometry to RelateOp) on two points. Note that there are no visible html output, but results are logged to the developer console of the browser.

Of interest is that modularity and reduced dependencies pays off already. Bundling only the basic application code results in a ~340 kb js file (166 kb minified) and the relate application code is ~730 kb (350 kb minified). This is because the bundling (with Browserify) will only pull in the modules that are used and of course that would not be possible if I were to translate the original Java code into a single module (if that is even possible). The unminified build of the original jsts is ~1400 kb.

**Comment by bjornharrtell** [comment]
Another major milestone. Got BufferOp working and what remains is currently unknown! :)

Next step is getting the code to run against the test suite, and get the format/viewer output code in there so results can be visually inspected.

I have written a list in the issue decription (up top) covering the changes I have done to the original Java source.

**Comment by dr-jts** [comment]
Nice!

A bunch of the code changes seem like niggly little issues - any chance that some of them can be cleaned up by a bit more work once the concept is proven?

**Comment by bjornharrtell** [comment]
I think only the Stack problems can be worked around quite easily. The others I'm afraid will prove next to impossible to work around.

Note that the actual modified source in the repo I linked is not at all representative of what is actually needed changes.

**Comment by dr-jts** [comment]
After a bit more thought, the only one that looks like a simple limit issue is:

Avoid overloading on methods with more than 3 arguments (addFillet in OffsetSegmentGenerator)

And I guess this can probably be avoided in some way - it's only an internal method.

It's a bit of a pain to have to avoid deprecated methods.  Why is this?

The biggest change is avoiding circular dependencies in Geometry, given the calls to classes which use Geometry!  But perhaps this can be encapsulated in a single class, which can be substituted at transpile time?

**Comment by bjornharrtell** [comment]
Removal of deprecations might be not needed, I'll look into it.

I don't understand your suggestion about circular deps. Its definitely the most invasive change but I see no way around it. Perhaps after a good nights sleep. :)

**Comment by bjornharrtell** [comment]
Also, the null argument resolution for overloads is also a mess to change in source but very hard to translate.

**Comment by dr-jts** [comment]
It was a comment along the lines of what we discussed earlier in this thread.  But now that I review that I remember that you pointed out that the problem is deeper than just changing out a single class.  I think I'm the one that needs to to understand the problem a bit better!

**Comment by dr-jts** [comment]
re null argument resolution: I have never liked this anyway.  Better to just use the method which allows skipping the null argument entirely (E.g use createPolygon(LinearRing) and createPolygon(LinearRing, LinearRing[]).  If that's the only fix needed that should be easy to do.  Or am I missing something?  Can you get a list of the methods which are problematic?

**Comment by bjornharrtell** [comment]
The problem are the methods that are overloaded to accept either `Coordinate[]` or `CoordinateSequence`. When the argument is null Java has magic logic to decide which function to actually call. The logic I'm refering to is explained here http://docs.oracle.com/javase/specs/jls/se7/html/jls-15.html#jls-15.12.2.5. I'm not hopeful about trying to get JavaScript to behave the same.

I have only made selective changes to JTS regarding this and might have broken things on the way but it works for the cases I've tried. I've introduced `createPolygon()` and `createLinearRing()` without arguments that creates empty geometries and also introduced a default constructor for `CoordinateArraySequence` that creates an empty instance. The only case I encountered as of yet that needed these changes was `createEmptyResultGeometry` in `BufferBuilder`, where an empty polygon was created with `createPolygon(null, null)` now replaced with `createPolygon()`.

**Comment by dr-jts** [comment]
Ah, ok, I understand the issue now.  The null Coordinate[]/CoordinateArraySequence issue is definitely confusing (Eclipse usually complains about this as well).  So this is a good thing to fix, and the changes you list make total sense.

**Comment by dr-jts** [comment]
Bjorn, could this technology be used to transpile JTS to languages other than JS?  Say Go or  C++  ?

**Comment by bjornharrtell** [comment]
AST transformation to other languages should be possible but for C++ a hard problem to solve is the memory allocation since it has no garbage collection. Might still be possible if combined with an existing GC implementation in C++. I'm not very familiar with Go but I know it has no classical inheritance which probably makes translation very hard.

**Comment by bjornharrtell** [comment]
Someone that knows LLVM and Clang very well can probably tell us more about how feasible it would be to translate to C++.

**Comment by bjornharrtell** [comment]
Got the test runner working and for BufferOp I got 15 passing tests out of 23 so that's pretty good. But unfortunately I get only 37 passing tests out of the full general suite which I count to 382 cases. Lots of pesky issues to solve and the Java fork has strayed a bit too far now.

**Comment by bjornharrtell** [comment]
After more fixes I count a total of 419 cases. Now passing 74 of them. Sorry for the constant updates. I think I need it for motivation on the painstaking path to finishing this.

I also tried to fix up the TopologyTestApp to work with the changed JTS core. Managed to get it to compile but it seems to also use reflection to find methods from the xml test case data so it will take alot of effort to fix. First time I had a real look at the contents of jtsapp folder and I must say, the amount of work put into it is impressive at least.

**Comment by bjornharrtell** [comment]
Almost lost hope but I cracked several hard ones today. Because of point 7 on the needed Java changes, RobustLineIntersector.computeIntersection was called instead of LineIntersector.computeIntersection which caused subtle errors down the line.

In the process of finding this I catched another issue with SweepLineEvent which relied on "most specific" overloaded constructors logic. I refactored SweepLineEvent to not rely on complex overloads and instead force creation via factory methods. The result is https://github.com/bjornharrtell/jts-topo-suite/blob/no_circular_deps/jts/java/src/com/vividsolutions/jts/geomgraph/index/SweepLineEvent.java.

At 134 passing tests out of 419.

**Comment by bjornharrtell** [comment]
Would like to continue work on this but the issue with cyclical dependencies is problematic and requires too invasive changes to the source. Should evaluate if https://github.com/rollup/rollup/wiki/Cycles helps.

**Comment by bjornharrtell** [comment]
Rollup does not help. Cycles cannot be resolved for inheritance between classes, whereas cycles in composition is fully supported. Unclear if this can be solved in the future...

**Comment by bjornharrtell** [comment]
Further research indicates that Java solves cycles using multi-pass compilation over all available source, iteratively resolving cycles when possible. This also applies to inheritance since it's a part of the static type system.

In JavaScript (and I think also ES6 classes) inheritance is, as with most stuff in JavaScript, dynamic and can be redefined in runtime. I think this makes this issue very unlikely, if at all possible, to ever be resolved in tooling/compiler/runtimes for JavaScript.

I have an idea for a work around though... Since I've been able to isolate the problem to be the Geometry class and some of the "shortcut" methods there it should be fairly simple to introduce a method to filter out problematic methods from Geometry class in the source translation itself, and instead add the missing methods via a "monkey patch" that can be applied to the end of the translated source. For the monkey patch to be trivial I would like to get all implementation details out from the problematic Geometry methods so that they are only trivial "shim" methods. This is already the case for the buffer methods (goes straight to BufferOp), but for example intersection and union there are some additional implementation in the methods themselves.

So @dr-jts, this means with more effort put into this project it should be possible to do the needed Java source changes without breaking API  too much and still get mostly automatic translation. I would like to work on patches but "upstream" seem chaotic now with 1.14 released to Maven central from the forked source at https://github.com/metteo/jts... any guidance on how to proceed?

**Comment by dr-jts** [comment]
The Maven JTS 1.14 is built from the same source as is in the master SVN repo.  I'm avoiding any changes to that until I can create a 1.14 distro to post on SourceForge (any day now...).

If you want to make patches, I'd say carry on to get the details worked out.  They should be straightforward to merge when everything is ready.

As for the concept of pushing all implementation logic down into lower-level classes, I think that sounds ok.

**Comment by bjornharrtell** [comment]
If possible I'd like to work on this in steps to ease reaching agreement on what changes you can accept upstream. I think it will be hard to review/discuss a final set of changes as a single unit.

The removal of on demand imports and preparations for handling circular dependencies are critical to be able to run the the translation at all so I'd like to start with that.

I'm done with two patches already:

1. On demand import removal (many lines changes but trivial):
https://github.com/bjornharrtell/jts-topo-suite/commit/01e98ad19c7ef2bb433ae890a1eb3070a3f22cf0

2. Comparable implementation refactor for Geometry class to avoid circular dependencies:
https://github.com/bjornharrtell/jts-topo-suite/commit/b01e253d5c8cc7d0f6cfedea96ca51bd18ff201c

We discussed the latter in https://github.com/bjornharrtell/jsts/issues/178#issuecomment-143030165.

Also critical will be moving out the "shortcut" methods implementation from Geometry, avoiding fields with same name as methods. None of these changes should affect current API or tests.

And the last critical change is the null argument resolution for overloads. You mentioned in https://github.com/bjornharrtell/jsts/issues/178#issuecomment-146306748 that you didn't like it anyway but to me it's not an easy fix since it affects API and perhaps tests too. I'll have a go at it and report back when I get there.

**Comment by bjornharrtell** [comment]
The current status of the above patches to 1.14 and my conversion toolkit is that I can produce valid buffers and unions with a fully automatic port. :)

**Comment by bjornharrtell** [comment]
I'm now at 268 passing tests and I'm convinced only details remain now to get on par or better than the old manual port. 

However, I managed to completely mess up patch no 8 above because of line-feed confusion as noted in http://sourceforge.net/p/jts-topo-suite/mailman/message/34760539 so I think I will await the result of the code sprint before putting more work into making the patches ready for review.

**Comment by dr-jts** [comment]
Nice work.  Sounds good about the patches.

**Comment by bjornharrtell** [comment]
Couldn't wait so now I'm at 302 passing tests, by only fixing things in the translation layer, with automated test runs now at Travis:

https://travis-ci.org/bjornharrtell/jsts/builds/104301971

**Comment by bjornharrtell** [comment]
I'm happy to report that with new takes on patches and improved translation I'm now passing 483 of the 495 general testcases and the failures might be explained by acceptable precision difference resulting for slightly different arithmetics of Java vs JavaScript.

Closing this now since the experimental 1.0.0 branch is now producing what seems to be a better port than the old manual one. A beta release and patches to upstream will be forthcoming.

**Comment by dr-jts** [comment]
Good stuff.  

It would still be nice to dig into the failures and see what's causing them, and if they are not significant then somehow making them pass perhaps by using a tolerance value.
