### ISSUE TITLE
isValid() returns ReferenceError of the line from several identical points

### ISSUE THREAD

**Issue by cpsTinK** [bjornharrtell/jsts#179]
The line from several identical points causes an error
     ReferenceError: coords is not defined
practically in all functions, even in isValid()

In JTS r405 the error isn't present, returns false (other functions return GEOMETRYCOLLECTION EMPTY)

LINESTRING (4373542.035048323 6520941.392254497, 4373542.035048323 6520941.392254497, 4373542.035048323 6520941.392254497, 4373542.035048323 6520941.392254497, 4373542.035048323 6520941.392254497, 4373542.035048323 6520941.392254497)

**Comment by bjornharrtell** [comment]
Sounds like a bug. If you want to contribute to fix this issue an implemented test case as a pull request would help. Specific test cases for older issues can be found at test/spec/jsts/issues and can be used as a starting point.
