### ISSUE TITLE
Incoorect row in IntersectionMatrix.set2

### ISSUE THREAD

**Issue by chpicone** [bjornharrtell/jsts#184]
Calculation error on method set2 when determine row value:
  var row = i / 3;
(e.g when i=1 row is 0.33333)
needs to replace with
  var row = Math.floor(i / 3);

**Comment by bjornharrtell** [comment]
Thanks for noting this error. If possible please try to make this change a PR.

**Comment by bjornharrtell** [comment]
Fixed by #185.
