### ISSUE TITLE
OL3-Buffer example failing. 

### ISSUE THREAD

**Issue by yatenj** [bjornharrtell/jsts#193]
Hi, 
Thanks for JSTS example.
I am able to run the buffer.html example successfully with OpenLayers 2.13.1.
But when I tried to run buffer-ol3.html example, I get following error in ol.js.

var reader = new jsts.io.WKTReader(); // success
var input = reader.read('POLYGON ((-69 -90, -69 -90, -69 -90, -69 -90, -69 -90, -69 -90, -69 -90, -69 -90, -69 -90, -69 -90, -69 -90, -69 -90))');

var buffer = input.buffer(20); // success
var parser = new jsts.io.olParser(); //success
input = parser.write(input); // Failed
for line input = parser.write(input); // Failed following error is occurred.
"Uncaught TypeError: Cannot read property 'length' of undefined" on line 183 of ol.js file.
I have configured function name in ol3-buffer.html and jsts.min.js file according to ol3 functions.

![ol3-buffer1](https://cloud.githubusercontent.com/assets/13831101/9323793/ef4805ae-45a1-11e5-8265-def071556848.png)
![ol3-buffer-error](https://cloud.githubusercontent.com/assets/13831101/9323794/ef49cd80-45a1-11e5-8c79-5497bd6ac5ab.png)

Please help.

**Comment by bjornharrtell** [comment]
I do not get this error. The stable release works with OpenLayers 3.4.0 and I've just fixed so that the example in master branch works with 3.8.2 but that does not seem to be related to your error.
