### ISSUE TITLE
PrecisionModel.prototype.equals always returns true

### ISSUE THREAD

**Issue by scotteckersall** [bjornharrtell/jsts#196]
in jsts/geom/PrecisionModel.js,
Firefox complains with "SyntaxError: unreachable code after return statement" here:

jsts.geom.PrecisionModel.prototype.equals = function(other) {
  return true;

  if (!(other instanceof jsts.geom.PrecisionModel)) {
    return false;
  }
  var otherPrecisionModel = other;
  return this.modelType === otherPrecisionModel.modelType &&
      this.scale === otherPrecisionModel.scale;
};

**Comment by bjornharrtell** [comment]
Issue remain in 1.0.0-beta1 but is reversed, always returning false.

**Comment by bjornharrtell** [comment]
Must have been mistaken, tried it out again and it works on master without changes from 1.0.0-beta1.
