### ISSUE TITLE
Is there a way to get jsts.min.js and javascript.util.min.js of latest version?

### ISSUE THREAD

**Issue by MukeZ** [bjornharrtell/jsts#206]
Hi,

Do I need to import all files in src? How to use min extension files as before?

Cheers

**Comment by bjornharrtell** [comment]
The latest version is available for download at https://github.com/bjornharrtell/jsts/releases including prebuilt minified files.

**Comment by MukeZ** [comment]
From your link, in jsts,js and jsts.min file (0.16.0)

ol3 convertToMultiPolygon is 
```polygons.push(this.convertToPolygon(multiPolygon.geometries[i]));```which does not work, but in olParser file this function is ```polygons.push(this.convertToPolygon(multiPolygon.geometries[i]).getCoordinates());``` and it works.

So I think they are have not been updated.

Cheers

**Comment by skorinko** [comment]
the question is still relevant. how to get the latest versions of jsts.min.js and javascript.util.min.js?

**Comment by ptsagkis** [comment]
Here is the latest version
https://cdn.rawgit.com/bjornharrtell/jsts/gh-pages/1.2.1/jsts.min.js

You don't need any more  javascript.util.min.js
