### ISSUE TITLE
Issue with GeometryGraph.addLineString

### ISSUE THREAD

**Issue by rbrundritt** [bjornharrtell/jsts#208]
The jsts.geomgraph.GeometryGraph.prototype.addLineString function fails if the line has less than 2 coordinates. The issue is the line: 

this.invalidPoint = coords[0];

The variable being tested is called 'coord' but this line of code is using 'coords ' and shouldn't have an 's' on it.

**Comment by bjornharrtell** [comment]
With 1.0 released, 0.x series is now unmaintained so I'm closing this.
