### ISSUE TITLE
version 17 tag do not have a lib folder

### ISSUE THREAD

**Issue by s093294** [bjornharrtell/jsts#214]
We tried to use the library from bower in our solution but had to go back to 
`    "jsts": "bjornharrtell/jsts#0.16.0"`
to get the lib folder.

Not sure if its intended, and if we should expect coming versions also to not have libs when pulling from bower.json file.

**Comment by bjornharrtell** [comment]
I had no intention to break bower or support it in earlier versions. I left out the lib folder because I prefer to keep built artifacts out of the repository. Is there some good way to support bower without keeping built artifacts in the repository?

**Comment by s093294** [comment]
I am also new to bower in terms of authoring packages. I agree its nice to keep build artifacts out of repositories. I dont know if a package, is added to the bower registry, can pull the data from the release page.


Maybe someone else has some comments - i will try to tweet the question out and see if someone can help.

**Comment by bjornharrtell** [comment]
With 1.0 released, 0.x series is now unmaintained so I'm closing this.

**Comment by s093294** [comment]
Thats okay. 

We ever really figured out how to handle the bower thing :)

I just read up on http://bob.yexley.net/creating-and-maintaining-your-own-bower-package

How strong do you feel about not have a dist folder that is updated before each release?

**Comment by bjornharrtell** [comment]
I really do not want a dist folder. :)

I would like to have JSTS working with http://jspm.io/. I'm not sure it does yet.

**Comment by s093294** [comment]
Would you be okay if I set up an automated build system that pushed the build to a clean repository and and made it consumable with bower? That said, I need to test if I can get notifications about tags/commits from a repositry that I am not the owner of.

I dont know jspm. Personally I rather not have to learn yet another package manager :D But what ever works that allows me to pull it in easily to my project as a dependency.

**Comment by bjornharrtell** [comment]
If you want to support Bower + JSTS yourself in any way, by all means go ahead.

PS. Bower is going out of style so you will have to let it go sometime. :)

**Comment by s093294** [comment]
what do you mean by going out of style? :) Personal opinion or something you got a reference to? :)

**Comment by bjornharrtell** [comment]
Might be a bit subjective but I'm not alone. See https://gofore.com/stop-using-bower (I haven't read it all). Many significant projects does not support Bower (OpenLayers) or is migrating from it (Ember Js).

That said I don't object to usage with Bower but I don't want to maintain it, at least not by putting builds in the repository.

**Comment by s093294** [comment]
Thats fair and understandable.
