### ISSUE TITLE
The Browser and Node.js builds should be fully ES5-compatible

### ISSUE THREAD

**Issue by bjornharrtell** [bjornharrtell/jsts#222]
Some reported problems / use of non ES5 API: 

- [x] Map
- [x] Array.fill
- [x] Object.defineProperty replaces length

**Comment by bjornharrtell** [comment]
Array.fill and Object.defineProperty use is gone.. but need polyfill for Map. One exists in https://github.com/zloirock/core-js.

**Comment by bjornharrtell** [comment]
No need to be fancy I think I should just include https://github.com/WebReflection/es6-collections in the ES5 browser build.

**Comment by rbrundritt** [comment]
I'm still seeing the Array.fill issue in browser version of rc5. The line of code that does this, looks like this: 

Z.coordArrayType=new Array(0).fill(null)

**Comment by bjornharrtell** [comment]
Thanks for the heads up. It needed to be tested. With bbd2e6d4159a1393a3f69dd24034a20125d631b0 it seems to be working in Internet Explorer 9 and forward which should be compatible enough, I hope.
