### ISSUE TITLE
Quadtree broken?

### ISSUE THREAD

**Issue by Pieter-Jan** [bjornharrtell/jsts#228]
I am on the latest version (1.0.0.rc4) and quadtree does not seem to be working.

I add an element to the index, and immidiately thereafter I remove the same element from the index, but I get an error in line 67 of nodeBase.js. It seems that my subNodes are still all "undefined". 

The bounding box of the element I added to the index is "-2500, -7000, 500, -5750". This means that the getSubnodeIndex function returns -1. This means that in the insert function we will just "add" and "return null" which keeps all our subnodes "undefined". When I execute the remove, the "isSearchMatch function returns true because this env was found, afterwards we are looping over all the subnodes with the !== null, which explicitly checks for "null" so the "undefined" passes through and boom ... crash

Can you fix this?

Thanks

**Comment by bjornharrtell** [comment]
Thanks for the report. I'll check if I can reproduce this... if so, it is something I'd like to get fixed asap and put out another RC.

**Comment by Pieter-Jan** [comment]
Thank you. Maybe I am doing something wrong but I cant seem to get it to work ...

**Comment by bjornharrtell** [comment]
I hope it works well with the fixes in rc5. Please reopen if not.

**Comment by Pieter-Jan** [comment]
Fix works! Thanks a lot for the super quick response & help!
