### ISSUE TITLE
LinearRing class missing

### ISSUE THREAD

**Issue by rbrundritt** [bjornharrtell/jsts#229]
Not sure if this is a design change or not, but it looks like the jsts.geom.LinearRing class is missing.

**Comment by bjornharrtell** [comment]
It's there but not exposed in the single file builds. Shouldn't be that useful as it can be created through GeometryFactory, but perhaps there is cases I'm not thinking of so I have added it and some others in 19ce98eb1ab96baf9cbe7f574e24ca07d7d124cf and I'm betting it's a safe change that won't have to warrant a new RC.
