### ISSUE TITLE
Current version of JSTS references "window"

### ISSUE THREAD

**Issue by rbrundritt** [bjornharrtell/jsts#230]
Past versions of JSTS didn't reference "window" where as this version does. For example: window.jsts. As a result this library won't work in a WebWorker anymore.

**Comment by bjornharrtell** [comment]
Would like to fix this but have limited experience with WebWorkers. Can you give a short example of code that dails?

**Comment by bjornharrtell** [comment]
Seems a good way to fix this is to do like underscore does it here https://github.com/jashkenas/underscore/blob/master/underscore.js

**Comment by rbrundritt** [comment]
Yes, using self instead of window looks like it would resolve this issue. Let me know if you still want a code sample with a WebWorker.

**Comment by bjornharrtell** [comment]
Couldn't get the underscore method work, perhaps botched in the build process - but it seems Browserify can handle it (https://github.com/substack/insert-module-globals/issues/10) so I've switched to let it take care of it. Please reopen if not resolved.
