### ISSUE TITLE
Algorithm namespace no longer available

### ISSUE THREAD

**Issue by rbrundritt** [bjornharrtell/jsts#233]
In version 1.0.0.0 it looks like the jsts.algorithm namespace is no longer available.

**Comment by bjornharrtell** [comment]
Correct. I'll expose the public classes from that namespace in the next release.

**Comment by bjornharrtell** [comment]
Need to rename member CGAlgorithm.length as it is a reserved name in JavaScript.

**Comment by bjornharrtell** [comment]
Um, CGAlgorithms.length was already renamed. The issue was actually in a dependency of CGAlgorithms3D which I won't aim to include in 1.0.0.

**Comment by bjornharrtell** [comment]
Above changes done in faf8a7fbf478b11789711d10d4f8c7c5d2c4e928.
