### ISSUE TITLE
ConvexHull much slower

### ISSUE THREAD

**Issue by rbrundritt** [bjornharrtell/jsts#234]
This is a low priority issue.

It seems like the convex hull algorithm is a lot slower in JSTS version 1.0.0.0 than it was before. I have a sample where I drag pushpins on a map and update the convex hull as the user drags the pushpins, so I've set it up to do a lot of convex hull calculations fast for testing. It feels like the calculations is about twice as long or longer. 

I'm also noticing that the calculation throws an error every now and then a bit randomly. Not sure of the cause yet, but will keep looking into this.

**Comment by bjornharrtell** [comment]
Ok, I agree the performance issue in this case, while interesting and could be profiled, is not a high priority. The "error and randomly" behavior does not sound good, but the general tests pass so I'll push this past 1.0.0 if you cannot provide more details at this point.

**Comment by rbrundritt** [comment]
I dug deeper into my code and found that it wasn't the convex hull algorithm throwing an error, but actually the isValid function when I test the convex hull polygon, after normalizing it. Here is the normalized of the polygon that fails with isValid(): 

"POLYGON((460901.19200082554 -33906.696118606975,3961797.469018929 -2530706.105361609,2293179.400371934 -4841460.21827416,599984.6734172448 -3210077.352238564,460901.19200082554 -33906.696118606975))"

**Comment by bjornharrtell** [comment]
Created a separate issue for the isValid failure at #236.

**Comment by bjornharrtell** [comment]
@rbrundritt, the isValid issue should be resolved in rc8. Please report back if this has had any effect on performance of ConvexHull or not.

**Comment by rbrundritt** [comment]
Performance is still a bit slower than before, but the isValid issue is fixed.

**Comment by bjornharrtell** [comment]
I made up some unscientific test code (below) which I measure 3.15 seconds runtime with 0.17 and 2.26 seconds with 1.1.0.

I'll close this for now. Feel free to reopen with a proper example that proves the new version slower.

```js
var factory = new jsts.geom.GeometryFactory()
var reader = new jsts.io.WKTReader()
var b = reader.read('LINESTRING(0 0, 1 20, 50 20, 100 100, 200 200, 200 50, 1 1)')
for (var i = 0; i < 100; i++) {
  b = jsts.operation.buffer.BufferOp.bufferOp(b, 10)
}
var points = b.getCoordinates().map(c => factory.createPoint(c))
points.forEach(p => new jsts.algorithm.ConvexHull(jsts.operation.buffer.BufferOp.bufferOp(p, 10)).getConvexHull())
```
