### ISSUE TITLE
Equidistant Buffer possible?

### ISSUE THREAD

**Issue by DenisCarriere** [bjornharrtell/jsts#238]
Is it possible to generate a buffer that is equidistant? Reading your docs, it seems that the radius input is only in degrees, would it possible to input a radius of 10km or 10miles? This way the buffer doesn't look like an egg shape.

![image](https://cloud.githubusercontent.com/assets/550895/13376294/87dca334-dd86-11e5-9ef7-8d35156274de.png)

If I create a buffer near the Zero (0) latitude it looks like a real circle, but as we go higher in latitudes, the shapes get very skewed.

![image](https://cloud.githubusercontent.com/assets/550895/13376335/a7cc47e8-dd87-11e5-9188-a93764ec3e69.png)

Javascript code I used:

```javascript
var jsts = require('jsts')

var radius = 5
var reader = new jsts.io.WKTReader()
var geom = reader.read('POINT (-75 45)')
var buffered = geom.buffer(radius)

var writer = new jsts.io.GeoJSONWriter()
buffered = writer.write(buffered)

var feature = {
  type: 'Feature',
  geometry: buffered,
  properties: {}
}
```

**Comment by bjornharrtell** [comment]
AFAIK there are no geodetic formulas in JTS/JSTS so I think the answer is no.
