### ISSUE TITLE
Missing protected class from AST conversion

### ISSUE THREAD

**Issue by ThomasG77** [bjornharrtell/jsts#240]
According to your README

> JSTS was made using automatic translation of the original JTS Java source via AST to AST transformation

I was trying to make a custom build for using `jsts.util.GeometricShapeFactory`. I encountered the following issue.
One class required for it hasn't been correctly transformed.

If you compare [JS version](https://github.com/bjornharrtell/jsts/blob/master/src/org/locationtech/jts/util/GeometricShapeFactory.js) to [Java version](https://sourceforge.net/p/jts-topo-suite/code/HEAD/tree/tags/Version_1.14/jts/java/src/com/vividsolutions/jts/util/GeometricShapeFactory.java#l405), you will see both reference in the constructor a `new Dimensions()`.

Whereas in the Java version, the function is available as [a protected class](https://sourceforge.net/p/jts-topo-suite/code/HEAD/tree/tags/Version_1.14/jts/java/src/com/vividsolutions/jts/util/GeometricShapeFactory.java#l405) within the same file `GeometricShapeFactory`, on the JS side, it's not available and it fails when I declare a `new GeometricShapeFactory()`

**Comment by bjornharrtell** [comment]
Nice catch. `GeometricShapeFactory` is one of the (few?) untested public classes which is why this has gone unnoticed. To get this fixed some trivial testcases will be needed.

**Comment by bjornharrtell** [comment]
I've fixed the conversion so it might work now, but I cannot verify since I have no tests and no time to make any at this time. @ThomasG77 please get back to me if you find time to test this now.

**Comment by bjornharrtell** [comment]
Closing this as it's part of the 1.1.0 release. Feel free to reopen if issues remain.
