### ISSUE TITLE
projection issue with polygon intersect - Cannot read property 'getAxisOrientation' of undefined

### ISSUE THREAD

**Issue by cartochris** [bjornharrtell/jsts#241]
Hi

I have a WFS service that I am using to search against with a user defined polygon. My WFS and map are in the EPSG:27700 projection and I am finding an error displaying when it tries to carry out the intersect which is:

Uncaught TypeError: Cannot read property 'getAxisOrientation' of undefined

Are there any known issues when trying to carry out polygon intersects with projections other than the usual ones like 3857?

Thanks

**Comment by bjornharrtell** [comment]
I doubt your error has anything to do with JSTS. Feel free to provide details that indicate otherwise and reopen.
