### ISSUE TITLE
WKTWriter.toLineString is not a function

### ISSUE THREAD

**Issue by bschantz** [bjornharrtell/jsts#244]
Throughout the codebase,` WKTWriter.toLineString` is called as a static method. In WKTWriter.js, it's defined by calling `extend()` on `WKTWriter.prototype`, which creates an instance method, which causes the exception `WKTWriter.toLineString is not a function` to be thrown.

Defining the method with `extend(WKTWriter, { ...` creates a static method and should resolve the issue. I've created a pull request with a simple test case that I'll submit shortly.

**Comment by bjornharrtell** [comment]
Fixed by #245.
