### ISSUE TITLE
Class.isAssignableFrom used but not ported from Java

### ISSUE THREAD

**Issue by schmidtk** [bjornharrtell/jsts#246]
[GeometryExtracter](https://github.com/bjornharrtell/jsts/blob/6cef5d221c082da36a6bc63f6b7da0216aaaf8ac/src/org/locationtech/jts/geom/util/GeometryExtracter.js#L24) calls `isAssignableFrom` which is not defined, causing an error.

I encountered this trying to call union on a GeometryCollection.

**Comment by bjornharrtell** [comment]
Thanks for the report, I can reproduce the issue with the above added test case.
