### ISSUE TITLE
"this.parse is undefined" error when reading a GeoJSON object

### ISSUE THREAD

**Issue by rabidllama** [bjornharrtell/jsts#249]
When I try and use the read method of a jsts.io.GeoJSONReader() on any GeoJSON object I get an error message that "this.parse" is undefined. I am using 

<script src="https://cdn.rawgit.com/bjornharrtell/jsts/gh-pages/1.0.2/jsts.min.js"></script> 

and the code being used is 

var feature = {
	type: 'Feature',
	geometry:	{
		type: 'Point',
		coordinates:	[8.7, 49.415]
	},
	properties:	{
	}
};
var reader = new jsts.io.GeoJSONReader();
var input = reader.read(feature);

**Comment by bjornharrtell** [comment]
As stated by http://bjornharrtell.github.io/jsts/1.0.2/doc/GeoJSONReader.html the read method expects a GeoJSON Geometry not a Feature.

**Comment by rabidllama** [comment]
Ah cool, I was switching between versions as the Polygon was playing up and getting wrong coords in an older version - I must have got my wires crossed.

Thanks
