### ISSUE TITLE
Google Map Polygon with JSTS (Self-Intersecting Polygon or Closed Points) Problem

### ISSUE THREAD

**Issue by sefakdas** [bjornharrtell/jsts#257]
Hello,

I use jsts plugin for polygon with google directions area with distance. 

Image : http://i.hizliresim.com/57v46A.png

Before reduce the distance;
Image : http://i.hizliresim.com/4rnDJY.png

Before increase the distance problem fixed. But i want icrease the distance.

I think that because of the problems point to stay open. Is there a way to close point by itself?

Code;
[codes.txt](https://github.com/bjornharrtell/jsts/files/214806/codes.txt)

**Comment by bjornharrtell** [comment]
This is too broad. Please provide a specific and isolated test case that clearly demonstrate what the problem is.
