### ISSUE TITLE
ReferenceError: GeometryComponentFilter is not defined on polygon intersection

### ISSUE THREAD

**Issue by Ivan31415** [bjornharrtell/jsts#258]
steps to reproduce

1. link https://cdn.rawgit.com/bjornharrtell/jsts/gh-pages/1.1.0/jsts.min.js
2. execute code

`var coordinates = [new jsts.geom.Coordinate(50.3282361844247, 43.051352042895246),
                    new jsts.geom.Coordinate(50.3286311088063, 43.05588339079827),
                    new jsts.geom.Coordinate(50.3289594043318, 43.05119738555413),
                    new jsts.geom.Coordinate(50.32935432871337, 43.0557287321717),
                    new jsts.geom.Coordinate(50.3282361844247,43.051352042895246)];`

`var polygon1 = geometryFactory.createPolygon(geometryFactory.createLinearRing(coordinates));`
`var polygon2 = geometryFactory.createPolygon(geometryFactory.createLinearRing(coordinates));`

`polygon1.intersection(polygon2);`

**javascript Error: GeometryComponentFilter is not defined**

**Comment by Ivan31415** [comment]
note that polygon area is small - 4.648357212216165e-13

**Comment by bjornharrtell** [comment]
Thanks for the report and example code, seems like this a bug in JSTS.

**Comment by bjornharrtell** [comment]
This case should now fail with a TopologyException with a proper message which I think is to be expected. The polygon does not pass a test for validity. I have not checked if upstream will fail in the same way, feel free to reopen if it does not.
