### ISSUE TITLE
Internet Explorer 11 compatibility

### ISSUE THREAD

**Issue by jvail** [bjornharrtell/jsts#259]
Hi,
I have some errors when using union&simplify with jsts 1.1.0 with IE11.

In [HashMap](https://github.com/bjornharrtell/jsts/blob/4dc559aa76f6631d555f1438c609b914c025f967/src/java/util/HashMap.js#L7) you might want to check for Map.prototype.values as well (not implemented in IE11 ...) 
```javascript
var MapInternal = Map;
if (typeof Map === 'undefined' || !Map.prototype.values) {
  MapInternal = MapAlternative;
}
```

Using TopologyPreservingSimplifier gives me an error in ...
```javascript
TaggedLineString.extractCoordinates = function (segs) {
  	var pts = new Array(segs.size() + 1).fill(null);
  	var seg = null;
  	for (var i = 0; i < segs.size(); i++) {
  		seg = segs.get(i);
  		pts[i] = seg.p0;
  	}
  	pts[pts.length - 1] = seg.p1;
  	return pts;
  };
````
seg.p1 fails because seg is null. I could not find the source of the error so far.

... and finally IE is complaining about a missing (polyfill for) Array.from.

Thank you
Jan

**Comment by bjornharrtell** [comment]
Thanks for the report, will want to get this fixed when time permits.

**Comment by jvail** [comment]
Thanks! Let me know if you need someone to test the release with IE.

**Comment by bjornharrtell** [comment]
Would be great. With 81dd8d7a2ed3c53d38b61872cdc7b981a18296a1 I hope to have fixed both the issue with HashMap and Array.from (by not using it) but it's untested in IE. Can you build from master yourself to try it out?

Also, I'm a bit uncertain but do you mean that the failure TopologyPreservingSimplifier is related to IE or not?

**Comment by jvail** [comment]
> Also, I'm a bit uncertain but do you mean that the failure TopologyPreservingSimplifier is related to IE or not?
Well, related to IE in that sense that I had no problems with union or simplify in Chrome but simplify failed with IE (even after solving the Map and Array.from problem). But probably it works now. I'll give it a try with 81dd8d7. 

> Can you build from master yourself to try it out?
Last time I got an error with uglify but the first step in the build script did work. That is enough for testing - I guess.

**Comment by jvail** [comment]
Magically  81dd8d7 fixes all problems above (the simplify error in simplify as well). I testet a build from "rollup -c rollup.config.js > jsts.js". :thumbsup:
Thanks Björn

**Comment by bjornharrtell** [comment]
Great to hear it, thanks for testing!
