### ISSUE TITLE
STRtree query function error for some inputs

### ISSUE THREAD

**Issue by patakye** [bjornharrtell/jsts#262]
i have a situation where i have an STRtree object built
inside the tree we have the following objects: 

![image](https://cloud.githubusercontent.com/assets/7260732/14757638/7a80cd38-08aa-11e6-9c23-c200ef607aca.png)

We have 7 vertical lines at x = 0, 10, 20, 30, and at 0, and then -10, -20, and 
We have 6 horizontal lines with y = -10, -20, -30, -40, -50, -60

i am calling index.query() with the following parameters: 

![image](https://cloud.githubusercontent.com/assets/7260732/14757648/a01c9b80-08aa-11e6-83f3-2bb20504e110.png)

The result should be that the vertical line at 0,0 is returned, but it returns an empty array []

Can you tell me why?

**Comment by patakye** [comment]
i would add to this that the vertical line at 0,0 only comes out from the query call if the input envelope is -2,2 (or larger i presume) ...

**Comment by bjornharrtell** [comment]
I'm not sure why this might be happening. Perhaps it's because you use infinity, perhaps that is not supported upstream either.

Needs further investigation. If you want to help, what needs to be done is testing the same at upstream and provide an isolated test case.

**Comment by patakye** [comment]
thank you sir, i figured it out .. we had multiple jsts files included and it could not recognize certain objects as from the jsts library, leading to strange logic .. our fault!  thank you

**Comment by bjornharrtell** [comment]
Thank for getting back on this.
