### ISSUE TITLE
'Map' is undefined error in IE10

### ISSUE THREAD

**Issue by natonic77** [bjornharrtell/jsts#263]
Getting the following error when loading jsts 1.1.1 on my page in IE10: "'Map' is undefined" - prevents jsts from fully initializing.  I ran across this in another project here: https://github.com/frankwallis/plugin-typescript/issues/70 and wonder if it is the same sort of issue.

**Comment by bjornharrtell** [comment]
That's strange, I wonder why only IE 10 is affected. The conditional that decides if a polyfill should be used was a bit dodgy though so I've changed that potentially fixing things, can you make a local build and try it out?

**Comment by natonic77** [comment]
Will try to do this - I work in a pretty isolated environment so setting up a local build will take a little time.  In the mean time I had a quick look at the fix and wondered if it is the let statement in the code.  From this: https://msdn.microsoft.com/en-us/library/dn263046(v=vs.94).aspx it would seem that 'let' might not be supported in IE10 (seems unlikely this is it - I imagine this isn't the only place you've used let in the code).

**Comment by sweco-sebhar** [comment]
Can't be it. When building the code is transpiled ro ES5 code so let becomes var.

**Comment by bjornharrtell** [comment]
Can't be it. When building the code is transpiled ro ES5 code so let becomes var.

**Comment by natonic77** [comment]
I had some trouble making a local build.  I'm sure it is mostly my ignorance as I haven't done much development with node.  I pulled down the repo did an 'npm install' followed by an 'npm run-script build'.  Build failed with an error in strtree.js indicating that the module can't import itself (got this error on a few others too.  I saw there was a change related to all the files reporting this error about 20 days ago, but I'm sure I've missed a step in setting up my environment since your CI builds are working (including the one from yesterday).  Sorry.  Happy to make a change to my env or test the output from your CI build server if that is available somewhere.

**Comment by sweco-sebhar** [comment]
Yeah seen that issue from others but no idea why that happens. I can always blame your OS I guess. :)

Here is a current build from master:
[jsts.min.js.zip](https://github.com/bjornharrtell/jsts/files/236523/jsts.min.js.zip)

**Comment by bjornharrtell** [comment]
Yeah seen that issue from others but no idea why that happens. I can always blame your OS I guess. :)

Here is a current build from master:
[jsts.min.js.zip](https://github.com/bjornharrtell/jsts/files/236527/jsts.min.js.zip)

**Comment by natonic77** [comment]
That seems to have fixed the problem.  Will exercise a bit more today, but I think you've got it.  Thanks.

**Comment by bjornharrtell** [comment]
Great, thanks for verifying.
