### ISSUE TITLE
Prototyping creates incompatibility !!

### ISSUE THREAD

**Issue by Montago** [bjornharrtell/jsts#264]
I'm building a Google Maps, Polygon editor using another framework called Wicket ( http://arthur-e.github.io/Wicket/sandbox-gmaps3.html ) and JSTS breaks functionality in that framework. 

It seems that the use of prototyping in this framework or lack of namespacing / containment is the fault !

Could you please checkup on prototyping of Javascript objects like Array and similar and please remove them in order for this framework to function flawlessly in mixed framework environments ?

Thanks !

**Comment by bjornharrtell** [comment]
If there is any incompatibility caused by JSTS I would be happy to have it fixed but you will need to provide more specifics and/or proof to convince me that JSTS really is at fault here.

**Comment by Montago** [comment]
Protoyping is generally considdered bad practice because of the risk of framework clashing

eg: 
Framework A: Array.protoype.Fill = XX
Framework B: Array.protoype.Fill = YY

prototyping on Array also has a bad effect on code that uses the property iterator (for-in) functionality (which is also bad practice) 

I managed to fix the compatibility problem with Wicket by re-writing all the Wicket code that used For-in
