### ISSUE TITLE
WKT Multipolygon [Difference] to Polygon = Polygon

### ISSUE THREAD

**Issue by Montago** [bjornharrtell/jsts#265]
I've made a tool that lets the user draw a freehand polygon for use in polygon manipulation..

Polygon A is a Multipolygon: 
MULTIPOLYGON(((12.34366298750956 55.7642131648377,12.34366298750956 55.80130975155818,12.49969482421875 55.80130975155818,12.49969482421875 55.79819333412856,12.49969482421875 55.7897010697495,12.49969482421875 55.781206953552704,12.49969482421875 55.77425584458219,12.49969482421875 55.767303495700936,12.49969482421875 55.7642131648377,12.490081787109375 55.7642131648377,12.43927001953125 55.7642131648377,12.396697998046875 55.7642131648377,12.3651123046875 55.7642131648377,12.34366298750956 55.7642131648377)),((12.544326782226562 55.80130975155818,12.78739550263765 55.80130975155818,12.78739550263765 55.76305453026331,12.7825927734375 55.76344054384817,12.76885986328125 55.7642131648377,12.748260498046875 55.7642131648377,12.707061767578125 55.7642131648377,12.671356201171875 55.7642131648377,12.632904052734375 55.7642131648377,12.588958740234375 55.7642131648377,12.544326782226562 55.7642131648377,12.544326782226562 55.7649857705176,12.544326782226562 55.77155230069221,12.544326782226562 55.77927621431672,12.544326782226562 55.78854289022504,12.544326782226562 55.79935122671461,12.544326782226562 55.80130975155818)))

and the free hand polygon B is
POLYGON((12.503128051757812 55.840626886363616,12.5079345703125 55.840626886363616,12.514114379882812 55.84101243369094,12.523040771484375 55.84101243369094,12.555313110351562 55.83947022144136,12.583465576171875 55.834843217637676,12.608871459960938 55.8271303210363,12.62603759765625 55.81748704921519,12.639083862304688 55.80398245276398,12.647323608398438 55.79008712193881,12.650070190429688 55.77193853272883,12.645950317382812 55.75919085473824,12.634963989257812 55.74682548924085,12.62054443359375 55.73522939875256,12.59857177734375 55.72595004523509,12.564239501953125 55.7182155657009,12.538833618164062 55.717055261645484,12.511367797851562 55.71898908258864,12.485275268554688 55.72672340893841,12.46673583984375 55.737162319794564,12.451629638671875 55.748371374300866,12.437210083007812 55.76459946959135,12.431716918945312 55.78236535117594,12.432403564453125 55.79819333412856,12.439956665039062 55.80977071070354,12.4530029296875 55.821344644770775,12.469482421875 55.83214387781303,12.489395141601562 55.839855780238864,12.503128051757812 55.840626886363616,12.503128051757812 55.840626886363616))

the result of Difference should be a Multipolygon ... but instead its only a cut-piece of one of the polygons in A :-( 

my code: 
var wktReader = new jsts.io.WKTReader();
var wktWriter = new jsts.io.WKTWriter();

var jsts_difference = function (wkt_a, wkt_b)
{
	var a = wktReader.read(wkt_a);
	var b = wktReader.read(wkt_b);
	var diff = a.difference(b);
	return wktWriter.write(diff);
}

what am i doing wrong ?
is this not supported ?

**Comment by Montago** [comment]
Are there any rules, whether a polygon needs to be clockwise or counterclockwise ??

i'm normalizing my polygons to be one of them.. in order for google maps to work properly...

**Comment by Montago** [comment]
This implementation with Openlayer + polygons work... 
http://jsfiddle.net/Montago/06qag6so/

while this on with your example code doesn't
https://jsfiddle.net/Montago/0s38brtL/1/ (notice the 4th box)

**Comment by Montago** [comment]
I'm beginning to suspect that the problem is WKTWriter ...

**Comment by bjornharrtell** [comment]
This is not a support forum. Please do not open issues until you have something substantial to support that your issue have anything to do with JSTS.
