### ISSUE TITLE
CascadedPolygonUnion not working with normal javascript array

### ISSUE THREAD

**Issue by Pieter-Jan** [bjornharrtell/jsts#270]
Hello,

I tried using jsts.operation.union.CascadedPolygonUnion.union(geoms) where geoms is a normal js array but it complains about isEmpty not existing. I see in your code that you use arrayList internally but it is not exposed. Can this be fixed?

Thanks

**Comment by bjornharrtell** [comment]
I will consider exposing ArrayList in a future version. But in the case of CascadedPolygonUnion you don't strictly need it. Details about how to make use of it indirectly can be found at https://groups.google.com/forum/#!topic/jsts-devs/2bMP9TfVjFo.

**Comment by bjornharrtell** [comment]
For the record I'm still not convinced that exposing ArrayList in the single file build is a good idea.
