### ISSUE TITLE
MCPointInRing not exposed anymore

### ISSUE THREAD

**Issue by Pieter-Jan** [bjornharrtell/jsts#271]
https://github.com/bjornharrtell/jsts/blob/master/src/org/locationtech/jts/algorithm.js

I see this algorithm is not exposed anymore. Is there a specific reason for that? Thanks!

**Comment by bjornharrtell** [comment]
No, it would make sense to include it since it's not available for use in any other way it seems. There might be more specific classes that might make sense to export, if you know others that might be useful I'd like to know.

**Comment by Pieter-Jan** [comment]
Not yet. I am trying to make an old piece of code work with the new version of jsts and am stuck with this.  The other functions in my piece of code all seems to be exposed. THanks!

**Comment by Pieter-Jan** [comment]
I created a PR for this issue. I tried building jsts myself but I get the following error:

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at WriteWrap.afterWrite (net.js:763:14)

**Comment by bjornharrtell** [comment]
Fixed in master. No idea about your build error. Attaching a build here, as it would be great if you could try it out to see if any other classes need exported for your case so that can be done before a new release.

[jsts.min.js.zip](https://github.com/bjornharrtell/jsts/files/308376/jsts.min.js.zip)

**Comment by Pieter-Jan** [comment]
Thanks! Sorry I have not been working on this project for a few days. Now I have the problem that jsts.operation.union.CascadedPolygonUnion.union is not defined anymore? Has this function been moved?

**Comment by Pieter-Jan** [comment]
After some further investigation it seems like it was removed in commit hash 12df71d47f79442ef01d1e4d2ed695c5849c16fb. Was this an accident?

**Comment by bjornharrtell** [comment]
Exposing `CascadedPolygonUnion` would also require exposing ArrayList, just as in #270 which also describes a workaround. Initially I was thinking ArrayList should be kept as an internal implementation detail but perhaps I need to reconsider.

**Comment by Pieter-Jan** [comment]
oh right sorry I forgot about that. That seems to be working thanks!
