### ISSUE TITLE
ArrayList Iterator remove method unsupported

### ISSUE THREAD

**Issue by evansiroky** [bjornharrtell/jsts#278]
When using the PrecisionModel in a GeometryFactory and performing a difference on specific geometries, an OperationNotSupported error is thrown.  See attached test case: [test.zip](https://github.com/bjornharrtell/jsts/files/349195/test.zip).

**Comment by bjornharrtell** [comment]
Thanks, I'm pretty sure this line is where the error originates:
https://github.com/bjornharrtell/jsts/blob/1.2.0/src/org/locationtech/jts/operation/overlay/OverlayOp.js#L99

Should be possible to fix by implementing the missing ArrayList iterator method.

**Comment by bjornharrtell** [comment]
Should be fixed in master now. However, I don't think your use of `PrecisionModel` has any effect here. I think you need to simplify the input geometry explicitly with `GeometryPrecisionReducer` or some other means to get it to work.

**Comment by evansiroky** [comment]
Confirmed fixed.  Thanks!  I tried the GeometryPrecisionReducer and ran into what might be another bug.  See #279.
