### ISSUE TITLE
ES5 build is not up-to-date

### ISSUE THREAD

**Issue by samcfc** [bjornharrtell/jsts#280]
Hello, I am not able to rebuild the es5 version of your lib from the last commit.
I am not very confident with babel and es6 and I got the following message

/usr/local/lib/node_modules/rollup/src/Bundle.js:22
                this.cachedModules = new Map();
                           ^
ReferenceError: Map is not defined
    at new Bundle (/usr/local/lib/node_modules/rollup/src/Bundle.js:22:28)

Could you please build it, because I am very interested by your last fix about ArrayList:remove

Thank you

**Comment by bjornharrtell** [comment]
When it is done.

**Comment by samcfc** [comment]
Ok, got it.

Thank you for your lib and your quickness to reply
