### ISSUE TITLE
Vertex is not accessible

### ISSUE THREAD

**Issue by drnextgis** [bjornharrtell/jsts#286]
``` js
var v = new jsts.triangulate.quadedge.Vertex(10, 20);
VM931:1 Uncaught TypeError: Cannot read property 'Vertex' of undefined(…)
```

**Comment by bjornharrtell** [comment]
Why do you need to use this class?

**Comment by drnextgis** [comment]
I need `classify` method of Vertex for classifying a vertex with respect to another vertex. I see this method in API docs but cannot use it. Why?

**Comment by bjornharrtell** [comment]
I have to manually choose what is to be exported in the ES5 build of JSTS, so I've not exported everything. Since you've got a use case I'll add it to exports, but be aware you are using practially untested parts of the code.

**Comment by drnextgis** [comment]
Thanks!
