### ISSUE TITLE
Buffer distance is less then the distance supplied( in meter).

### ISSUE THREAD

**Issue by Anupam-** [bjornharrtell/jsts#287]
While creating buffer around geometry, its not actually creating buffer according to supplied distance(in meter). As I measured while creating buffer for 100 meters around a point I am getting buffer of 60 meters.
Please find my fiddle: [(http://jsfiddle.net/anupam_001/486hse1o/)]

**Comment by bjornharrtell** [comment]
JSTS does not know about projections. The buffer radius will be the correct number of units. In this case you have two sources of errors:

1. I'm not sure the scale line is correct
2. 100 "meters" in web mercator will be more or less than 100 actual meters depending on where you are on the earth.
