### ISSUE TITLE
Why is no PrecisionModel in build for browser?

### ISSUE THREAD

**Issue by cpsTinK** [bjornharrtell/jsts#288]
We used JSTS 0.17.0 before
```javascript
var jstsPrecModel = jsts.geom.PrecisionModel( 100 ),
    jstsGeomFactory = new jsts.geom.GeometryFactory( jstsPrecModel ),
    jstsOL = new jsts.io.OpenLayersParser( jstsGeomFactory ),
    jstsJSON = new jsts.io.GeoJSONParser( jstsGeomFactory ),
    geom3 = jsts.precision.EnhancedPrecisionOp.intersection( geom1, geom2 );
```
These classes are in sources 1.2.1, but in build for browser of these classes are unavailable.

> An ES5 (the most common JavaScript variant) compatible build for browsers is available [here](https://cdn.rawgit.com/bjornharrtell/jsts/gh-pages/1.2.1/jsts.min.js).

Why?

**Comment by bjornharrtell** [comment]
PrecisionModel is exposed since 1.2.1 so I guess you mean the EnhancedPrecisionOp class. Reasons why it's not exposed is has no test coverage and I have never used it myself so I'm not sure it actually works. So for now I prefer to keep it out of the build.

**Comment by cpsTinK** [comment]
And parser OpenLayers 2 will no longer be supported?

**Comment by bjornharrtell** [comment]
No, for OpenLayers 2 you will have to go though an intermediate format like GeoJSON.
