### ISSUE TITLE
import jsts from 'jsts' results in undefined jsts

### ISSUE THREAD

**Issue by boriscosic** [bjornharrtell/jsts#289]
var jsts = require('jsts') works but in version 1.2.0 I could also do import jsts from 'jsts'; The latter now produces an undefined jsts.

**Comment by bjornharrtell** [comment]
It's unknown to me what might have caused this change, but `import jsts from 'jsts'` shouldn't have worked before either. What should work is `import * as jsts from 'jsts'` but I haven't tested it.

**Comment by boriscosic** [comment]
That worked, thanks for this great library!
