### ISSUE TITLE
Importing a GeoJSON creates the wrong figure

### ISSUE THREAD

**Issue by rpadovani** [bjornharrtell/jsts#292]
Sorry for the generic title, but I'm actually not sure of what is the error.

I have a GeoJSON Polygon, created following the SRID 4326, and I want to calculate the area (for the following example is 5806515.07382393)

So, I've created this simple example function:

```
'use strict';

const data = {
        "type":"Polygon",
        "coordinates": [[[11.5576574300632,48.1279037312948],[11.5518627148077,48.1539549221445],[11.5761566162109,48.1582992626563],[11.5775299072266,48.1202675272745],[11.5576574300632,48.1279037312948]]]
};

const jsts = require('jsts');
const precisionModel = new jsts.geom.PrecisionModel();
const factory = new jsts.geom.GeometryFactory(precisionModel, 4326);
const geojsonReader = new jsts.io.GeoJSONReader(factory);

const border = geojsonReader.read(data);

console.log(border.getArea())
```

It gives as area  `0.0007016786703307461` - what do I do wrong?

**Comment by bjornharrtell** [comment]
You are working with degrees and expect area in m² which requires an implementation that knows about the relationship between these units. JSTS does not know about projections and assumes planar coordinates. The SRID that can be supplied to GeometryFactory is only for metadata.
