### ISSUE TITLE
Could you publish this package without .babelrc? Fails in React Native

### ISSUE THREAD

**Issue by tsemerad** [bjornharrtell/jsts#293]
I have found that the jsts package is causing problems when used in React Native. The jsts package published on NPM has a .babelrc file that requires the "es2015" preset. React Native compiles with babel, and is known to not work with `babel-preset-es2015`. Installing and using jsts results in an error, but removing the .babelrc file from the installed jsts package resolves the issue. Is the .babelrc file even needed in the published NPM package since the library is already compiled to the `dist` directory?

I filed a related issue in the Turf library [here](https://github.com/Turfjs/turf/issues/505).

**Comment by bjornharrtell** [comment]
Thanks for reporting. I'll consider it for the next release.

If i remember correctly the .babelrc is required only for running the tests.
