### ISSUE TITLE
In IE8 browser,  buffer multipoint has problem

### ISSUE THREAD

**Issue by HogwartsRico** [bjornharrtell/jsts#296]
In IE8 browser,  buffer multipolygon has problem,And the browser don't throw error or any information.  

but ,in the chrome , firefox  or  opera ,it works  
and in ie8 browser,buffer polyline polygon ,point all works ,only the multipoint has problem

in the IE8 console    
![1](https://cloud.githubusercontent.com/assets/3449649/20589226/2a85e5b0-b256-11e6-8aae-e032280d21d8.PNG)  

in the Chrome  console    
![2](https://cloud.githubusercontent.com/assets/3449649/20589227/2ab46afc-b256-11e6-99fd-a067b04e12c9.PNG)

my multipoint string

```
"MULTIPOINT(120.13630366436 30.1909462208 ,120.14111018291 30.192319511816 ,120.14248347393  30.186483024999 ,120.15861964336 30.254804253027)";
```

**Comment by bjornharrtell** [comment]
Sorry, I'm not interested in supporting IE8.
