### ISSUE TITLE
Error in some cases "found non-noded intersection between LINESTRINGs"

### ISSUE THREAD

**Issue by rulyotano** [bjornharrtell/jsts#298]
I this error in some cases, and I can't understand the reason for it:

` TopologyException: found non-noded intersection between LINESTRING ( -52.38894509399756 -12.774978654107324, -52.38894506358076 -12.774978749731966 ) and LINESTRING ( -52.38894549397294 -12.774978741474133, -52.38864848514676 -12.774913865697423 ) [ (-52.38894509399756, -12.774978654107324, undefined) ]`

When I get this error? In several cases. For instance, I have a list of several polygons (lets call it `set A`), then I make an union of this polygons, and then calculate the area: 

`var unionGeometry = (new jsts.geom.GeometryFactory()).buildGeometry(geoList);
 if (!unionGeometry)
      return;
  var workedArea = polygonCalculationService.getGeometryArea(unionGeometry.union());` 

In this scenario, lets say that I have a subset of `A` named `A'`, in some cases with `A` I have no error and with `A'` does, in other cases I get the error with `A` and not with `A'`, and so on.

There are other cases where I get the error, others operations like intersection. The thing is that I can't find a reason for it, with some data I get the error, and with some other doesn't.

**Comment by bjornharrtell** [comment]
`TopologyException` are indications of precision issues in the input. Reducing precision might help.

**Comment by rulyotano** [comment]
What is that of Reducing precision???

**Comment by bjornharrtell** [comment]
Please seek further information elsewhere, this is an issue tracker not a support forum.

**Comment by rulyotano** [comment]
Ok, the only thing is that this seems an issue for me. If in random scenarios (real ones with real geo-polygons data) raise errors, then the entire library becomes useless :(

**Comment by bjornharrtell** [comment]
Please stop using this library if it makes you unhappy and you think others should resolve your issues without putting any effort into it yourself.

**Comment by rulyotano** [comment]
It is a shame! Really seems the library had good perspectives.

**Comment by bjornharrtell** [comment]
I've added this to the Caveats section in the README.md:

In some cases you might get a TopologyException thrown as an Error. This is expected if a calculation fails due to precision issues. To resolve this issue try reducing precision in the input and at the same time make sure the input is valid as defined by the OGC Simple Features specification.

If you still get TopologyException after reasonable effort to reduce the precision and the input is valid feel free to report it as an issue here including a reproducible example or test case.

**Comment by rulyotano** [comment]
Thanks a lot!!! I tried to reduce the precision for the input, but seems not working very well for this cases with Geo Points, also tried to use a custom precision (with less precision, like 100000000) model and geometry factory in the GeoJSON reader, but also doesn't helped.  A trick that read in some place, and seems to work for this case (at least in almost test cases I have done) is to apply `.buffer(0)` to the geometry before apply the `union` or `intersection` operations. Thanks again.

**Comment by bjornharrtell** [comment]
Buffering by 0 is a trick that can heal invalid geometries but it is not foolproof.

Setting `PrecisionModel` on the factory or reader will not automatically reduce precision, see http://bjornharrtell.github.io/jsts/1.3.0/apidocs/org/locationtech/jts/geom/GeometryFactory.html. One way to reduce precision is to use `GeometryPrecisionReducer`, see http://bjornharrtell.github.io/jsts/1.3.0/apidocs/org/locationtech/jts/precision/GeometryPrecisionReducer.html.
