### ISSUE TITLE
Uncaught TypeError: jsts.operation.union.CascadedPolygonUnion is not a constructor

### ISSUE THREAD

**Issue by tjhall13** [bjornharrtell/jsts#301]
CascadedPolygonUnion appears to have disappeared from `operation.union` in https://github.com/bjornharrtell/jsts/commit/12df71d47f79442ef01d1e4d2ed695c5849c16fb. Can this be added back in please?

**Comment by bjornharrtell** [comment]
Read https://github.com/bjornharrtell/jsts/issues/270 and related info and think about if there really is a use case that requires direct use of CascadedPolygonUnion. If you have a good case, reopen and I'll consider it exposing again.
