### ISSUE TITLE
Valid GeoJSON returns invalid geometry

### ISSUE THREAD

**Issue by dougajmcdonald** [bjornharrtell/jsts#304]
Just getting started with JSTS and I create a GeoJSON rectangle which looks like this:

`{"type":"Polygon","coordinates":[[[-5.671174693968908,54.520303357905846],[-5.671174693968908,54.65793327448387],[-6.170131491994141,54.65793327448387],[-6.170131491994141,54.520303357905846],[-5.671174693968908,54.520303357905846]]]}`

Popping this into: http://geojsonlint.com/ returns the shape I'd expect.

I'm then wanting to use this GeoJSON to see if other geometries are contained within in. I've tried to create a JSTS geometry like this:

```
    const reader = new jsts.io.GeoJSONReader();
    const geometry = reader.read(myGeoJSON);
    console.log(geometry.isValid()); // false
```

Feels like I'm missing something simple here but can't quite figure it out.

I've also tried manually create a polygon like this:

```
    const gf = new jsts.geom.GeometryFactory();
    const polygon = gf.createPolygon(gf.createLinearRing(
      [bounds._ne.lng, bounds._sw.lat],
      [bounds._ne.lng, bounds._ne.lat],

      [bounds._sw.lng, bounds._ne.lat],
      [bounds._sw.lng, bounds._sw.lat],

      [bounds._ne.lng, bounds._sw.lat]
      ));
     console.log(polygon.isValid()); //TypeError: g.isEmpty is not a function
```

Any info / tips would be greatly appreciated.

**Comment by bjornharrtell** [comment]
When I run your first example `geometry.isValid()` returns `true`.

What makes you think you can call `createLinearRing` in that manner? If you check out the API docs you should see it does not accept arguments in that way.

**Comment by dougajmcdonald** [comment]
Interesting, what version are you running to get true? I'll check mine tomorrow AM but it was fresh from NPM this morning. 
I took a guess at that linear ring as I couldn't find a decent example on how to create a polygon from coords.  The only Api I could find was from the original Java library.

**Comment by bjornharrtell** [comment]
I used 1.3.0 so it should be the same. If you take a look at the main README.md it explains that the API preserved from the Java version. Closing this now as there does not seem to be any evidence of an issue with JSTS.

**Comment by dougajmcdonald** [comment]
@bjornharrtell thanks for the feedback, I figured out the problem. For some reason I'd missed a set of square brackets around my coordinates (but put them on when posting the question).

As a separate point the one thing I'm finding hard to work with with JSTS is the lack of examples compared to say turf. 
The difference between:
https://github.com/turf-junkyard/turf-polygon and http://bjornharrtell.github.io/jsts/1.3.0/apidocs/org/locationtech/jts/geom/Polygon.html is that I can't easily determine how to create a polygon via JSTS from the API.

The API suggests I need to make a liner ring, and an array of holes and a geometry factory. I then have to go and look at http://bjornharrtell.github.io/jsts/1.3.0/apidocs/org/locationtech/jts/geom/LinearRing.html to try and work out how to create one of those. At this point I now have to go and work out what i need for a Coordinate sequence http://bjornharrtell.github.io/jsts/1.3.0/apidocs/org/locationtech/jts/geom/CoordinateSequence.html which has a weird description where it isn't clear what format I need to put coordinates into.

I feel like some simple examples would go a hugely long way to reducing the barrier to entry for those of us with no experience with the Java version. 

The library looks great, but it's not documented in a particularly accessible way. I'd be happy to help in some way regarding documentation if I can?

**Comment by bjornharrtell** [comment]
I agree that the barrier is rather high and experience with the upstream Java project is almost a requirement.

Turf is actually using JSTS (for some operations) so it can be seen as the "user friendly" frontend to JSTS. You should consider that Turf is backed by Mapbox which is a large company and so has another level of support than JSTS which is largely a one man project.

While a suite of examples would be nice I'm not sure it's as simple as "some examples". You can use JSTS for alot of different use cases and complexity levels. To be useful you'd need to create quite a few examples and that would be alot of work.

That said, I did create this very basic example page:
http://bjornharrtell.github.io/jsts/

If you'd like to help expand it would be great, but I want to keep it at a low level of complexity.

Normally you would create geometry via a format like WKT or GeoJSON, so I'd say using the GeometryFactory directly is in the category of more advanced use.

For more involved examples I think it would be best to make them as manual test cases, similar to the ones I got at https://github.com/bjornharrtell/jsts/tree/master/test/manual. Would be great if there was a good way to present these test cases online with the code inlined. That would actually be a given accepted contribution. :)
