### ISSUE TITLE
Was this repo recreated?

### ISSUE THREAD

**Issue by esromneb** [bjornharrtell/jsts#306]
I seem to remember an older version of this repo with history from like 6 years ago.  (for instance https://web.archive.org/web/20150811094825/https://github.com/bjornharrtell/jsts )  What happened and how can I get a copy of that old repo? I'm looking for examples/overlay.html  Thanks.

**Comment by bjornharrtell** [comment]
You seem to have very good memory. Take a look at the archived branch at https://github.com/bjornharrtell/jsts/tree/0.x.
