### ISSUE TITLE
ol is not defined 

### ISSUE THREAD

**Issue by zhhuan** [bjornharrtell/jsts#308]
I use openlayers and jsts to do buffer analysis. however browser always failed this error ** ol is not defined**。 I use the riot importing the jsts and openlayers , openlayers's version is 4.1.0 and jsts's version is 1.2.0。
` var format = new ol.format.GeoJSON();` success
`var features = format.readFeatures(json, {featureProjection: 'EPSG:3857'});` success
`var parser = new jsts.io.OL3Parser();`  success
`var point = new ol.geom.Point([14135270.238049889, 4513071.4242111845]);`
`var jstsPoint = parser.read(point); `  failed with next error
![image](https://user-images.githubusercontent.com/10020346/27112943-78cc0882-50ec-11e7-9924-d286b8216c3f.png)

**Comment by bjornharrtell** [comment]
Should work using an undocumented feature. See https://github.com/bjornharrtell/jsts/pull/290.
