### ISSUE TITLE
cut the fat :)

### ISSUE THREAD

**Issue by Montago** [bjornharrtell/jsts#309]
There is a Memory Utility that can print how much memory is used - but its not compatible with Javascript ?

Runtime.getRuntime() is not known by web browsers (and to my knowlewdge Node.js) 

remove it ?

This smells like a Java relic - there might be more cases ?

**Comment by bjornharrtell** [comment]
Correct. :) Most of the code is autotranslated and I've filtered out stuff that was entirely unused or Java-specific. The remaining stuff is either mixed with other code that *is* used or is too small be of significance.

That said, if I am ever able to translate to TypeScript instead (related to https://github.com/bjornharrtell/jsts/issues/285) with most type information intact perhaps the "fat" can be compiled away by the TypeScript compiler.

Closing as this is a non-trivial issue that I have no current plan to work on. I will not accept manual modifications to reduce the fat, but will accept improvements to the translation (https://github.com/bjornharrtell/java2estree).

**Comment by Montago** [comment]
Will the java2estree be the project you'll use to translate into TypeScript ?

**Comment by bjornharrtell** [comment]
It could be, but if there is a better/existing tool I would use that. Originally I thought I could use an existing Java to JavaScript transpiler like GWC but it could keep the Java API intact so I decided to write my own transpiler but it's very brute force and will probably not work for anything else than JTS. I haven't investigated if GWC have evolved these days or if there is another suitable tool.

**Comment by Montago** [comment]
It wouldn't take THAT long to manually translate all the JS to TS ... 

The CJS format looks very similar to TypeScript and the import references makes it very easy. 

basically most of the bulk would be to copy-paste the code around into Classes ... and along doing so, add the types. 

One thing you could do, would be to add the return type of methods as a comment in the code - that would help very much. 

and if it followed some standard i might be able to write a transpiler (or anyone else could do it)

**Comment by Montago** [comment]
does JTS still receive updates ?

**Comment by bjornharrtell** [comment]
You'd have to ask that upstream. In my opinion, a future replacement of JTS and/or JSTS needs a complete rewrite and should be a lot more modular. I have no personal interest in manual translation, but you're welcome to fork. :)

**Comment by bjornharrtell** [comment]
In addition, I don't see it worthwhile to transpile the already transpiled JavaScript to TypeScript. In my opinion it would be better to transpile Java directly to TypeScript.

**Comment by Montago** [comment]
I agree that JTS should be more modular ..

we currently struggle with the size of the library - having 450KB of code.. 
would be nice if you could either pick the parts you need or let the compiler do it.
