### ISSUE TITLE
Class Angle is missing

### ISSUE THREAD

**Issue by lildadou** [bjornharrtell/jsts#310]
It seems to me that there are still many other classes.

**Comment by bjornharrtell** [comment]
It's there (https://github.com/bjornharrtell/jsts/blob/master/src/org/locationtech/jts/algorithm/Angle.js) just not exposed in the single file build. Why do you need it?

**Comment by lildadou** [comment]
Thank you for answering.

I have a list of GPS points and for each of them I wanted to know the angle between the y-axis and the next point. I then use this angle to apply a rotation to an icon arrow-shape in a map.

**Comment by bjornharrtell** [comment]
Fixed by https://github.com/bjornharrtell/jsts/commit/1e2e508f23d9212108d2dade996b4cc378a7932d.
