### ISSUE TITLE
kdTree missing in 1.4.0

### ISSUE THREAD

**Issue by sainsb** [bjornharrtell/jsts#314]
How does one access the kdTree index in v1.4.0? Chrome devtools shows me that the (constructor) method is not accessible.
![image](https://user-images.githubusercontent.com/1097798/29473352-65805b90-840c-11e7-9e86-05e44f177881.png)

However, I can see that the kd-tree code is still within the file...

thank you very much - awesome work!

**Comment by bjornharrtell** [comment]
It's just that it's not exposed in the single file build, which is kind of a manual selection of the most common classes.

I'm missing tests for this class so I'm not sure the port actually works which is also the main reason it's not exposed.

**Comment by bjornharrtell** [comment]
Fixed by https://github.com/bjornharrtell/jsts/commit/698f522d6e493bc3274c344c91127ba0b775160d.
