### ISSUE TITLE
Please, consider adding BSD license to the source

### ISSUE THREAD

**Issue by delfrrr** [bjornharrtell/jsts#316]
http://bjornharrtell.github.io/jsts/ says that

> STS is licensed under a dual BSD/EPL license

But I cannot find a notion of BSD license in a package.json / project root / README

Thank you!

**Comment by bjornharrtell** [comment]
The EDL license is identical to BSD.

https://github.com/bjornharrtell/jsts/blob/master/LICENSE_EDLv1.txt

In either case I don't control the licensing since this project is a direct port of the upstream.

**Comment by delfrrr** [comment]
EDL does not seem to be OSI approved and ELP has restrictions. But if EDL is identical to BSD it should allow you to sublicense it under BSD.

**Comment by bjornharrtell** [comment]
That might be right but I insist on it happening upstream, if at all.
