### ISSUE TITLE
linemarge is not available

### ISSUE THREAD

**Issue by am2222** [bjornharrtell/jsts#320]
Hi,
While I am using linemarge it says it is not a function, This is my code
```
`var format = new ol.format.GeoJSON();
    var features = format.readFeatures(route, {featureProjection: 'EPSG:3857'});
    var feature = features[0];
    // convert the OpenLayers geometry to a JSTS geometry
    var jstsGeom = jstsParser.read(feature.getGeometry());

    for (i = 1; i < features.length; i++) {


        var feature2 = features[i].getGeometry();

        // create a buffer of 40 meters around each line
        var uniun = jstsGeom.linemerge(jstsParser.read(feature2));


        // convert back from JSTS and replace the geometry on the feature
       // feature.setGeometry(parser.write(buffered));

    }`
```

The above code works well with union but I need to merge lines. Is there anything that I am doing wrong?
thanks

**Comment by bjornharrtell** [comment]
There is no such method, why did you think so?

You might be looking for https://github.com/bjornharrtell/jsts/blob/master/src/org/locationtech/jts/operation/linemerge/LineMerger.js. It's however a rarely used class and missing tests so I'm not sure it works, feel free to report any specific reproducable problems with it.

**Comment by am2222** [comment]
@bjornharrtell  Yes I searched and found it. so I thought it is included in. Can I use it separately with the main library if I just reference it in webpage?or I must recompile it?

**Comment by bjornharrtell** [comment]
It's in the bundled version, not sure why you cannot seem to find it?

**Comment by am2222** [comment]
@bjornharrtell  I am using this version :https://cdn.rawgit.com/bjornharrtell/jsts/gh-pages/1.5.0/jsts.min.js is not it included?

**Comment by am2222** [comment]
@bjornharrtell  I think I am using this function is a wrong way. as It returns a class when I call it using consol.
