### ISSUE TITLE
import * as jsts from 'jsts' results in undefined jsts when import * as ol from 'openlayers' are in same ts file

### ISSUE THREAD

**Issue by mcardoso27** [bjornharrtell/jsts#322]
Hi, i created an Angular 5 project in which i installed by npm the openlayers module and jsts module. I did the following steps:

1. ng new testProject
2. cd /testProject
3. npm install --save openlayers
4. npm install --save jsts
5. npm install --save  _at_types/openlayers
6. npm install --save _at_types/jsts

Here is my app.component:

```
import { Component, OnInit } from '@angular/core';
import * as ol from 'openlayers';
import * as jsts from 'jsts';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {

  ngOnInit() {
    console.log('OPENLAYERS: ', ol);
    console.log('JSTS: ', jsts);
  }
}
```

And this result in undefined jsts variable.

**Comment by bjornharrtell** [comment]
There is no jsts module, you need to import individual modules. Only the ES5 bundle define a global jsts.

**Comment by mcardoso27** [comment]
Sorry but i still can not make it work. How should I import the modules? I tried with
`import { io, geom } from 'jstst'`
but without succes.

**Comment by bjornharrtell** [comment]
Look at http://bjornharrtell.github.io/jsts/index_modules.js (live running at http://bjornharrtell.github.io/jsts/index_modules.html) does that help?

**Comment by mcardoso27** [comment]
Yes, that works. However, typings is not working. When i use 
`import * as jsts from 'jsts';`
typing work well, but in run time this result in undefined jsts variable. How can I do to import and that the typing works?

**Comment by bjornharrtell** [comment]
Sorry, that I have no idea about.
