### ISSUE TITLE
PrecisionModel improvements for I/O classes

### ISSUE THREAD

**Issue by cklein05** [bjornharrtell/jsts#326]
Hi Bjorn,

we are using JSTS for computing unions and differences on polygons with a fixed precision model and found, that `TopologyException`s are thrown quite more often, compared to JTS or GEOS. After investigating on this, we've found a couple of things to be improved in JSTS. Here's the first one.

Most of the I/O classes work differently than those in JTS, which, of course, is not problematic. However, in order to honor the set `PrecisionModel`, function `reducePrecision` is applied after the conversion. There is such a function in class `WKTReader` and one in class `GeoJSONReader`. Both these are different and neither is correct, since both do nothing on polygons, which have `shell` and `holes` properties. Those are not handled by any of these functions. Also, in class `GeoJSONReader`, the function works with the wrong properties.

Here's an implementation of the `reducePrecision` function, which should work for all geometries. Additionally, you could consider moving this function to a separate file `IOPrecisionHelper.js` and use it from all other I/O classes, in order to make it easier to maintain. For example, class `OL3Parser` does currently not apply any precision model, which, for my mind, it should as well.

~~~javascript
reducePrecision (geometry) {
	if (geometry._coordinates) {
		this.precisionModel.makePrecise(geometry.getCoordinate())
	} else if (geometry._points) {
		for (let i = 0, len = geometry._points._coordinates.length; i < len; i++) {
			this.precisionModel.makePrecise(geometry._points._coordinates[i])
		}
	} else if (t._shell) {
		this.reducePrecision(t._shell);
		if (t._holes) {
			for (let i = 0, len = t._holes.length; i < len; i++) {
				this.reducePrecision(t._holes[i])
			}
		}
	} else if (geometry._geometries) {
		for (let i = 0, len = geometry._geometries.length; i < len; i++) {
			this.reducePrecision(geometry._geometries[i])
		}
	}
}
~~~

**Comment by bjornharrtell** [comment]
Hmm the situation is a bit messy but AFAIK JTS isn't consistent here. WKB and WKT readers appears to round to precision, while the GeoJSON reader does nothing and instead encourages the user to postprocess.

The buggy implementation in JSTS is inherited from version 0.x where `makePrecise` on `PrecisionModel` did not work. I think it does work now and I should probably make the WKT reader use that and remove any buggy implementation.

**Comment by dr-jts** [comment]
The difference in precision handling between WKT/WKB and GeoJSON does seem inconsistent.  I can't recall why that was done.  It may well just be an oversight.  Feel free to post a JTS issue to either fix or confirm.

**Comment by dr-jts** [comment]
I'll also point out that in general for polygons simply reducing the precision of the coordinates may not produce valid output (owing to the phenomenon of "topology collapse").  

JTS does have [GeometryPrecisionReducer ](https://github.com/locationtech/jts/blob/master/modules/core/src/main/java/org/locationtech/jts/precision/GeometryPrecisionReducer.java) which enforces valid topology (although it currently does this using buffer(0), which is a slow and sometimes buggy hack.  Hopefully a better implementation will be implememented, when funding is available.

**Comment by bjornharrtell** [comment]
Thanks for the input @dr-jts. I've cleaned up the current implementation and it should now be as in upstream as of https://github.com/bjornharrtell/jsts/commit/77782354a38b6bf7bd90aeb0737f51d2a9500c5a.
