### ISSUE TITLE
Wrong implementation of method java.util.ArrayList.add

### ISSUE THREAD

**Issue by cklein05** [bjornharrtell/jsts#327]
There is a severe problem with the 2-parameter overload of the `add` method in class `java.util.ArrayList`, which in Java has the signature
~~~java
public void add(int index, E element)
~~~
In JavaScript, this is implemented with `Array.splice`. However, this method takes a 2nd numeric parameter that specifies, how many elements should be deleted at the specified index prior to inserting the provided elements:
~~~javascript
array.splice(index[, deleteCount[, element1[,  element2 [, ...]]]])
~~~
See [Array.splice on MDN](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Array/splice)

In case of the ArrayList, this parameter should be set to 0 (zero), of course. In the current implementation of the `ArrayList`, the element to insert is passed as the 2nd parameter, which actually does not delete any elements, but also does not add the specified element, which leads to very different results for algorithms, that use array lists with _inserting_ elements.

We've found this issue through class `SimpleSweepLineIntersector`, which adds edges to an `events` list, but inserting elements to an `ArrayList` is as well used in other places throughout the library.

**Comment by bjornharrtell** [comment]
Ouch.. I wonder why I don't see this breaking things.

**Comment by bjornharrtell** [comment]
Fixed by https://github.com/bjornharrtell/jsts/commit/a661df3e60b78619b13a3c00444cf319c898821a
