### ISSUE TITLE
Geometry.coveredBy regression in 1.5.0

### ISSUE THREAD

**Issue by cklein05** [bjornharrtell/jsts#329]
In file `monkey.js`, the `Geometry` type is extended with a couple of convenience methods. As of version 1.5.0, the `RelateOp` class no longer has a method called `coveredBy`, which is still called from method `Geometry.coveredBy`. A simple solution is to modify method `coveredBy`, so that it calls `RelateOp.covers` with arguments exchanged:
~~~javascript
coveredBy: function (g) {
	return RelateOp.covers(g, this);
},
~~~

In Java, `coveredBy` is implemented by calling `covers` on the passed geometry `g`, using `this` as argument. However, the solution above requires less function calls.

**Comment by bjornharrtell** [comment]
Fixed by https://github.com/bjornharrtell/jsts/commit/8da5a0c6dcc51b21e38396eb6046b8c8346c1a26.
