### ISSUE TITLE
JSTS using Java Generics

### ISSUE THREAD

**Issue by cklein05** [bjornharrtell/jsts#330]
In class `jst.index.strtree.STRtree` there is (still) a Java Generic definition in line 154:
~~~javascript
var kNearestNeighbors = new java.util.PriorityQueue<BoundablePair>(k, new BoundablePairDistanceComparator(false));
~~~
Actually and interestingly this can be parsed by JavaScript without error, since it is evaluated as a chained comparison. Of course, it does not do what one might expect :)

**Comment by bjornharrtell** [comment]
Fun observation :)

**Comment by bjornharrtell** [comment]
The use of generic java.util.PriorityQueue from  was introduced in https://github.com/locationtech/jts/pull/75. @dr-jts, was that intentional? Considering the upstream is otherwise (almost) generics free.

**Comment by bjornharrtell** [comment]
Another point is that I have no port of `java.util.PriorityQueue` generic or otherwise so this will not be trivial to fix.

**Comment by dr-jts** [comment]
Not intentional, just an oversight. 

Is it possible to replace with the JTS PriorityQueue?

**Comment by bjornharrtell** [comment]
Fixed by https://github.com/bjornharrtell/jsts/commit/bef0162efeb6fd19a2e5ac2f5cc43cf6e0bf9204 which is based on the unmerged https://github.com/locationtech/jts/pull/259.
