### ISSUE TITLE
GeometryFactory incorrectly referenced in Geometry convenience methods

### ISSUE THREAD

**Issue by cklein05** [bjornharrtell/jsts#331]
In file `monkey.js`, the geometry's `GeometryFactory` is referenced through property `this.factory` in methods `intersection`, `symDifference` and `difference`. Actually, the `GeometryFactory` is stored in `this._factory`.

**Comment by bjornharrtell** [comment]
This is due to `monkey.js` being partially manually made and I've forgot to update some of it after private members was renamed in transpilation. Fixed by https://github.com/bjornharrtell/jsts/commit/9eec04abfab161e3cf602d9b747a9d51f1260204.
