### ISSUE TITLE
OL-Parser ES6 Support

### ISSUE THREAD

**Issue by KaiVolland** [bjornharrtell/jsts#332]
Currently the `OL3Parser.js` does many `instanceof` checks against the standard version of `ol`. So the parser can't be used with OL as ES6 modules as these checks will fail (code not tested): 

```javascript
import Point from 'ol/geom/point';
const point = new Point();
console.log(point instanceof ol.geom.Point); // false
```
Is there a way to use `jsts` features with OL as ES6 modules?

If not, are you interested in a PR for a `OL_ES6_Parser.js`?

**Comment by bjornharrtell** [comment]
You should be able to inject the ol module at runtime but looks like there might be some bugs with that. Will see what I can do. (No need for a special purpose parser)

**Comment by bjornharrtell** [comment]
Actually I can't verify the problem. It should use injected ol. See https://github.com/bjornharrtell/jsts/blob/1307dbf2e53cee1670d965abe06d736e4e887946/src/org/locationtech/jts/io/OL3Parser.js#L19 (second parameter) and report back if it doesn't work after trying that.

**Comment by KaiVolland** [comment]
I think you can't import OpenLayers completely as an ES6 module.

If i use
```javascript
import ol from 'ol';
```
like in the [OL API Docs](http://openlayers.org/en/latest/apidoc/ol.html) you don't get the whole lib but an object with some statics.

Do you have an example of creating an instance of the `OL3Parser` with OpenLayers as an ES6 module?

**Comment by bjornharrtell** [comment]
You are right, individual symbols need to be imported. I will try to add API to optionally inject the needed classes from http://openlayers.org/en/latest/apidoc/ol.geom.html in the next version.

**Comment by bjornharrtell** [comment]
As a workaround it may work to supply a custom ol object with the ol.geom.* classes as needed and inject that.

**Comment by bjornharrtell** [comment]
Implemented inject method with https://github.com/bjornharrtell/jsts/commit/433011d4159955a8336d291533db89b6e7ff1a1d. Cannot easily test it at this time though so @KaiVolland if you can try it out it would be valuable and shorten time to get a new release done.

**Comment by bjornharrtell** [comment]
Travis detected a syntax error - fixed by https://github.com/bjornharrtell/jsts/commit/1fdd85eac262ed9fbcca8572995c67d3d3f98478.

**Comment by KaiVolland** [comment]
The injection worked well and the read method returns a jsts object as expected.
But sadly the resulting geometry does not include the `buffer` method.

Here is my code:
```javascript
// import JstOl3Parser from 'jsts/org/locationtech/jts/io/OL3Parser'; // PRODUCTION
import JstOl3Parser from 'jsts/src/org/locationtech/jts/io/OL3Parser'; // DEVELOPMENT

import Point from 'ol/geom/point';
import LineString from 'ol/geom/linestring';
import LinearRing from 'ol/geom/linearring';
import Polygon from 'ol/geom/polygon';
import MultiPoint from 'ol/geom/multipoint';
import MultiLineString from 'ol/geom/multilinestring';
import MultiPolygon from 'ol/geom/multipolygon';
import GeometryCollection from 'ol/geom/geometrycollection';

/**
 *
 * @class
 */
class TopologyUtil {

  static parser = new JstOl3Parser();

  /**
   *
   * @param {ol.geometry} geometry
   * @param {Integer} buffer
   */
  static addBuffer (geometry, buffer = 0) {
    const jstsGeom = TopologyUtil.parser.read(geometry);
    const buffered = jstsGeom.buffer(buffer);
    return TopologyUtil.parser.write(buffered);
  }
}

TopologyUtil.parser.inject(
  Point,
  LineString,
  LinearRing,
  Polygon,
  MultiPoint,
  MultiLineString,
  MultiPolygon,
  GeometryCollection
);

export default TopologyUtil;

```

**Comment by bjornharrtell** [comment]
This is expected when using modules. See https://github.com/bjornharrtell/jsts/issues/323.
