### ISSUE TITLE
Small bug in class CommonBits

### ISSUE THREAD

**Issue by cklein05** [bjornharrtell/jsts#333]
Hey Bjorn,

there is still a small bug in class `jts.precision.CommonBits`, which is clearly my fault. In line 24, `this._commonBits` is set to zero:
~~~javascript
23		if (numSignExp !== this._commonSignExp) {
24			this._commonBits = 0;
25			return null;
26		}
~~~
In my modified version of this class, there was a call to the now nonexistent method `clear()`, which, in our development version set both the `Long`'s the low and high word to zero. However, I changed my mind and removed `clear()`, as there is no such method in Java's `Long` type.

Likely you changed this to `this._commonBits = 0;`, in order to avoid errors due to calling a nonexistent method. However, with this solution, an error is thrown when method `getCommon()` is called, which in turn calls `Double.longBitsToDouble`, which expects an object with `high` and `low` properties.

The simplest solution would be to change line 24 into two lines, setting both `high` and `low` properties to zero. Ensure, values are casted to 32 bits (maybe some runtimes can benefit from this).
~~~javascript
23		if (numSignExp !== this._commonSignExp) {
24			this._commonBits.high = 0 | 0;
25			this._commonBits.low = 0 | 0;
26			return null;
27		}
~~~

**Comment by bjornharrtell** [comment]
Ah! Initial problem was because I simply didn't see the diff on those lines on a bit too quick review. New suggested solution commited as of https://github.com/bjornharrtell/jsts/commit/d1e8cc718c5b5238de3144633e41b953dae3cf58.

**Comment by cklein05** [comment]
That was really fast :+1:
