### ISSUE TITLE
[Question] Is it possible to use OL3Parser server-side?

### ISSUE THREAD

**Issue by F3L1X79** [bjornharrtell/jsts#335]
Hi bjornharrtell, 
Thank you so much for all your work on jsts.

I was wondering if I can use jsts with OL3Parser server-side?

Actually this is my code:
```
global.window = {};
global.navigator = {
    userAgent: ''
};
var jsdom = require("jsdom");
var JSDOM = jsdom.JSDOM;
global.document = new JSDOM('<!DOCTYPE html>').window.document;
var Vector = require('ol/source/vector');
var Feature = require('ol/feature');
var Linestring = require('ol/geom/linestring');
var Point = require('ol/geom/point');
var jsts = require('jsts');
var ol3Parser = new jsts.io.OL3Parser();
console.log(ol3Parser);
```

Then ol3Parser.ol is false:
```
Fi {
  geometryFactory: 
   se {
     _precisionModel: ie { _modelType: [Object], _scale: null },
     _coordinateSequenceFactory: Zt {},
     _SRID: 0 },
  ol: false }
```

So, when later in my code, when I do:
```
var lineString = new Feature({
         geometry: new Linestring([10, 10])
});
ol3Parser.read(lineString.getGeometry());
```

I got this error:
```
TypeError: Cannot read property 'Point' of undefined
    at Fi.read (/node_modules/jsts/dist/jsts.min.js:8:249795)
```

I do not have the problem client-side - and client-side the attribute ol of ol3parser is set. This is why I guess it is the cause. Do you have any clue?
Thanks a lot for reading and sorry for this long post...

**Comment by bjornharrtell** [comment]
It's not been tested (AFAIK) but it could work if you use the alternative method to inject OpenLayers classes - this one here - https://github.com/bjornharrtell/jsts/blob/1.6.0/src/org/locationtech/jts/io/OL3Parser.js#L29

Let me know how that works out. :)

**Comment by F3L1X79** [comment]
Worked like a charm!
Thank you so much for the fast answer!
