### ISSUE TITLE
Can not instantiate jsts.operation.overlay.snap.GeometrySnapper

### ISSUE THREAD

**Issue by pietrucha** [bjornharrtell/jsts#336]
Using: 
`new jsts.operation.overlay.snap.GeometrySnapper(geom);`
I get: 
> TypeError: Cannot read property 'GeometrySnapper' of undefined.

**Comment by bjornharrtell** [comment]
Currently not included in the ES5 build. Might be considered for the future.

**Comment by bjornharrtell** [comment]
Fixed by https://github.com/bjornharrtell/jsts/commit/467c18b246c1fa320f956bc9283dabe1d108db94.
