### ISSUE TITLE
The polygon is getting destroyed when i try to make a union of it.

### ISSUE THREAD

**Issue by tarrun** [bjornharrtell/jsts#338]
I have a list of polygons which are perfectly visible on the map, just the thing is that a little spacing is coming between them, so that i want to merge all of them to a single polygon. When i try apply union on all of them a polygon with lots of cuts is coming is response( I have attached both the images of polygons )
Before:
![polygons-with-little spacing](https://user-images.githubusercontent.com/8327877/40407859-5b94dd0c-5e83-11e8-8bd4-dbe4cc9e51ef.png)

After applying union:
![after-union-of-polygons](https://user-images.githubusercontent.com/8327877/40407867-5d4f0f00-5e83-11e8-93e9-c5f7ff0e519d.png)

**Comment by bjornharrtell** [comment]
Again, it seems you have poor data = poor results.

**Comment by tarrun** [comment]
It is completely a nonsense response, I am using data from with a standard format designed for representing simple geographical features, along with their non-spatial attributes. It seems like you don't have a valid solution to my problem, So you are replying by blaming the data.

Seriously disappointed.

**Comment by bjornharrtell** [comment]
Feel free to be disappointed and to find a solution to your own problems.

**Comment by GregersP** [comment]
@tarrun try to union or dissolve those polygons in for instance [OpenJump](http://www.openjump.org/).
It will become clear to you, that they cannot be dissolved/unioned due to you poor data.

A trick you might use to mitigate your poor data quality, is buffer each part by x, union them, then buffer the union by -x.

**Comment by tarrun** [comment]
@GregersP Thank you very much for the trick.
