### ISSUE TITLE
Coordinate.clone is returning null

### ISSUE THREAD

**Issue by thedoctordiaz** [bjornharrtell/jsts#340]
https://github.com/bjornharrtell/jsts/blob/edcb00673d3a62bfb4882f23a97ce3f4e15c9f95/src/org/locationtech/jts/geom/Coordinate.js#L99

Coordinate.prototype.clone is returning null. always. I can't believe this is correct. The java implementation calls super.clone() and a jsts library that I have from 2013 calls new Coordinate.

**Comment by bjornharrtell** [comment]
Agreed, seems something is wrong here. Will look into it when time permits.

**Comment by bjornharrtell** [comment]
On second thought, clone is deprecated upstream and will not be fixed here. Instead you should use copy which is the replacement for the deprecated clone method.
