### ISSUE TITLE
JSTS 1.6.0 - ES5 compatibility issue

### ISSUE THREAD

**Issue by allknower** [bjornharrtell/jsts#341]
I use jsts with Sencha Cmd v6.5 and have compilation trouble:
> == Unhandled Error ==
> TypeError: undefined is not a constructor (evaluating '''log2(bits)''')
>   file:///.../Client/libs/jsts.js:152
>   file:///.../Client/libs/jsts.js:157
>   file:///.../Client/libs/jsts.js:409
>   file:///.../Client/libs/jsts.js:12

As far as I know Math.log2 is defined only in the ES6 specification. Is this a mistake or am I mistaken?

Thanks.

**Comment by bjornharrtell** [comment]
Agreed seems you are correct. I suppose polyfilling it in https://github.com/bjornharrtell/jsts/blob/master/src/Math.js should help.

**Comment by bjornharrtell** [comment]
Done with https://github.com/bjornharrtell/jsts/commit/002d9c03a68bb96caa666760e830efff2fd270df.
