### ISSUE TITLE
DiscreteHausdorffDistance not exported/used?

### ISSUE THREAD

**Issue by anoff** [bjornharrtell/jsts#343]
I am currently looking for a library to calculate a Hausdorff distance. I saw that you [implemented](https://github.com/bjornharrtell/jsts/blob/master/src/org/locationtech/jts/algorithm/distance/DiscreteHausdorffDistance.js) it but it doesn't seem to be exported in the [algorithm](https://github.com/bjornharrtell/jsts/blob/master/src/org/locationtech/jts/algorithm.js) object that can be accessed after loading the module.

Would you be willing to approve a MR that exposes `jsts.algorithm.DiscreteHausdorffDistance` together with the other methods implemented but not exported to the library interface

```javascript
import * as distance from './algorithm/distance_module'
import * as locate from './algorithm/locate'
import * as match from './algorithm/match'
```

**Comment by bjornharrtell** [comment]
Thanks, seems I forgot to re-export these modules for the ES5 build. Done with https://github.com/bjornharrtell/jsts/commit/52a29edc5182b75f121d4a2f769eca19e44cb345.

**Comment by DataCamper** [comment]
Hey, I'm currently encountering the same issue. Do you already know when you will release this fix?

**Comment by bjornharrtell** [comment]
Not sure when I can get time to do a release, sorry.
