### ISSUE TITLE
Buffer endcap style

### ISSUE THREAD

**Issue by zsoooc** [bjornharrtell/jsts#349]
Hello!

I made buffer zone around linestring with JSTS and OpenLayers 4.
I would like to set flat endcap style like in PostGIS: http://www.postgis.net/docs/ST_Buffer.html
endcap=flat
How to do this with JSTS?

I set` jsts.operation.buffer.BufferParameters.CAP_FLAT`, but the result is different. The two ends of the buffer are not flat. 

Screenshot: https://drive.google.com/file/d/1Brjp9wTpEJB2MR3Vfp-FkYdDXRxmHKBP/view?usp=sharing

**Comment by PeterSteen01** [comment]
using 1.4 it works fine for me!
 /**
     * Buffers a geometry
     * @param geom:Geometry
     * @param radius:double
     * @param precision:int
     * @param endStyle:int (1: rounded by radius, 2: Perpendicular to feature, 3: Square boxes)
     */
   ```
 public createBuffer(geom: Geometry, radius: number, precision?: number, endStyle?: number): Geometry {
        let input = this.readOLgeometry(geom);
        let buffer = input.buffer(radius, precision, endStyle);
        return this.writeOLFeature(buffer);
    }
```
