### ISSUE TITLE
Jsts is undefined

### ISSUE THREAD

**Issue by Alados** [bjornharrtell/jsts#350]
After update to new version (1.6.1) if I try use jsts it is always undefined, but from console it is available.

Import like this: `import * as jsts from 'jsts'`

Angular version 6.0.9

@types/jsts version 0.17.0

**Comment by bjornharrtell** [comment]
Not sure what is causing this. Downgrading to 1.6.0 resolves the issue?

**Comment by Alados** [comment]
Yes, it helped

**Comment by bjornharrtell** [comment]
Hmm so it's the same as discussed in the suggested change at https://github.com/bjornharrtell/jsts/pull/346. Looks like removing it is the right thing to do... but I wonder if "module": "index.js" should be left in `package.json` (it was in 1.6.0) (might be needed for bundlers using individual modules)

**Comment by bjornharrtell** [comment]
I've just made a 1.6.2 release without an empty index.js module. Not sure if it will help or if it will cause other issues and would appreciate any feedback from testing it with webpack and elsewhere.

**Comment by rangaraireddy** [comment]
That worked for me. Thanks!!
