### ISSUE TITLE
Problem / error?

### ISSUE THREAD

**Issue by pecet86** [bjornharrtell/jsts#355]
https://github.com/bjornharrtell/jsts/blob/624a0058963e558c80fbd46a0f9e713c4c4eed84/src/org/locationtech/jts/io/GeoJSONParser.js#L136

Hello
Why does not GeoJson Reader take into account the 3rd variable although it is supported in coordinates?

Is this an error or an idea.
Regards, Paweł

**Comment by bjornharrtell** [comment]
Don't have an answer.
