### ISSUE TITLE
PolygonizeDirectedEdge calls super() without arguments - causes an error

### ISSUE THREAD

**Issue by kordilery** [bjornharrtell/jsts#359]
PolygonizeDirectedEdge extends DirectedEdge. Calling DirectedEdge constructor without arguments causes an error as it requires 4 arguments to be defined (from, to, directionPt, edgeDirection). The solution is to have `super(...arguments);` as a first line in PolygonizeDirectedEdge constructor.
Thank you for fix in advance.

**Comment by bjornharrtell** [comment]
Nice find. Normally these classes is not used externally. What practical issue does this cause? I would like to make a failing test case.

**Comment by kordilery** [comment]
We are using a Polygonizer instance in our tool for cutting polygon by line. The problem occurs when using Polygonizer `add` method as it creates an instance of the PolygonizerDirectedEdge class.
The steps of cutting a polygon are as follows:
1) `getExteriorRing` of the polygon
2) ` union` it with the cutting line 
3) `add` the union to the polygonizer and finally `getPolygons`
