### ISSUE TITLE
extend.js removed during refactor but remains referenced in some files 

### ISSUE THREAD

**Issue by maxmorgan** [bjornharrtell/jsts#362]
As part of the ECMAScript 2015 classes refactor is looks like [extend.js has been removed](
https://github.com/bjornharrtell/jsts/commit/37ca36c80bdfcb30a0499b70bfb779098320675f#diff-45ed5e0f20f4e0ac60d2fe09f79cafa0).

But we still see references to it in [some files](https://github.com/bjornharrtell/jsts/search?q=%22import+extend%22&unscoped_q=%22import+extend%22) that is causing our build to fail.

It's possible that these files are potentially unnecessary or were missed during the refactor. I'll see if I can dive into this further or just convert them, but for now raising this your way.

**Comment by bjornharrtell** [comment]
Thanks for noticing this. These are old files no longer part of upstream, i.e transpiled from an older version using the old transpilation process. They should not be needed and I will remove them.

**Comment by bjornharrtell** [comment]
Done in https://github.com/bjornharrtell/jsts/commit/a7f6fc02f11437e6bb7c37a74a27f6cf9cfb0f70.
