### ISSUE TITLE
VWSimplifer not in `jsts.simplify`

### ISSUE THREAD

**Issue by nickpeihl** [bjornharrtell/jsts#363]
[VWSimplifier](https://github.com/bjornharrtell/jsts/blob/master/src/org/locationtech/jts/simplify/VWSimplifier.js) appears to be a useful module. Is there a reason it isn't exported in [`jsts.simplify`](https://github.com/bjornharrtell/jsts/blob/master/src/org/locationtech/jts/simplify.js)?

**Comment by bjornharrtell** [comment]
No :)

**Comment by bjornharrtell** [comment]
Done with https://github.com/bjornharrtell/jsts/commit/4fb020186d8e83ccc13e9f14fd438a03bef944a7.
