### ISSUE TITLE
ERROR: Uncaught ReferenceError: MapOp is not defined

### ISSUE THREAD

**Issue by presto41** [bjornharrtell/jsts#366]
Hi,

I want to report a bug in the jsts@2.0.2.
I got it when my code was trying to check if a two GeometryCollections had any intersections.

This is the error from browser console:

```
monkey.js:39 Uncaught ReferenceError: MapOp is not defined
    at Nt.H.intersection (monkey.js:39)
    at demo ((index):62)
    at window.onload ((index):129)
```

This bug is from [this place](https://github.com/bjornharrtell/jsts/blob/37ca36c80bdfcb30a0499b70bfb779098320675f/src/org/locationtech/jts/monkey.js#L39).

I saw that MapOp [is not anywhere defined in the repository](https://github.com/bjornharrtell/jsts/search?q=MapOp&unscoped_q=MapOp) so I made a decision about added `function MapOp() {}` into my code [just like you have here](https://github.com/bjornharrtell/jsts/blob/258b53b039134e862ae800b441133d52e3a89404/src/org/locationtech/jts/geom/util/GeometryMapper.js#L35) in jsts@1.6.2.

[Here](https://jsfiddle.net/Lmzx9nr6/25/) is my code to reproduce this bug.
If you want to see if my solution works then you have to uncomment a script statement from HTML file.

**Comment by bjornharrtell** [comment]
Confirmed bug in code transformation.

**Comment by bjornharrtell** [comment]
Hey @presto41, to check for intersections you should use `intersects` not `intersection`. The latter (which has the bug) calculated the actual intersecting part of geometry.

**Comment by presto41** [comment]
@bjornharrtell thanks for reply but I not want to know only if intersection is exists. I want to know if exists and I need too these calculations so I have to use `intersection`

**Comment by bjornharrtell** [comment]
Fixed by https://github.com/bjornharrtell/jsts/commit/eb2c8394bc2594f95dd159f9c5540478d2f0860b and https://github.com/bjornharrtell/jsts/commit/837884d8f7a8ffde02a1d0bc96520e559909c23c.

**Comment by presto41** [comment]
@bjornharrtell Could you tell me when do you plan to public a 2.0.3 version?

**Comment by bjornharrtell** [comment]
Soon.

**Comment by presto41** [comment]
@bjornharrtell "soon" is taking too long, don't you think? The world is still waiting for release jsts to 2.0.3 version :) could you?

**Comment by bjornharrtell** [comment]
Well.. it *is* almost christmas, so I might just be so inclined to do the nice thing... just this once. ;)

**Comment by bjornharrtell** [comment]
https://github.com/bjornharrtell/jsts/releases/tag/2.0.3
