### ISSUE TITLE
Implement PrecisionModel on WKTWriter

### ISSUE THREAD

**Issue by pecet86** [bjornharrtell/jsts#372]
Helo
A have proposition use PrecisionModel to write geometry to WKT

```
coordinate: function coordinate(_coordinate) {
	return this.geometryFactory.precisionModel.makePrecise(_coordinate.x) 
    + ' ' + this.geometryFactory.precisionModel.makePrecise(_coordinate.y);
},
```

https://github.com/bjornharrtell/jsts/blob/7a611831e4d1159faecdf781987a8f7c91c6a33f/src/org/locationtech/jts/io/WKTParser.js#L102

**Comment by bjornharrtell** [comment]
AFAIK this is not upstream behavior and in general I think it make sense to leave it to the consumer to make the geometry adhere to the precision.

**Comment by dr-jts** [comment]
The WKTWriter uses the precision model of the input geometry to determine the number of decimal places to write.  This seems to match what is being proposed.

**Comment by pecet86** [comment]
Yes, it's similar to GeometryPrecisionReducer but there is no reduction limit to the output data, you still have to save it [e.g. to WKT], and before copying.
This limits the number of operations.

The earliest one is used for output data [e.g. QGIS]. It is larger when editing.

The introduction of PrecisionModel usage does not change anything for basic data and makes working with them easier.

You do not need to make a superstructure or a copy of scripts.

**Comment by bjornharrtell** [comment]
Thanks for correcting me, I will make this or a similar change to master when possible.

**Comment by bjornharrtell** [comment]
I hope https://github.com/bjornharrtell/jsts/commit/02556b25a60e7f3c75241556ea32429b5eee5e03 is the correct fix for this.
