### ISSUE TITLE
Treeshaking observations

### ISSUE THREAD

**Issue by rowanwins** [bjornharrtell/jsts#375]
Hey @bjornharrtell 

I was in discussions with @dr-jts via email the other day re some buffer algorithm stuff regarding TurfJS (which I help maintain) and he thought it was worth touching base with you re tree-shaking of JSTS.

So I thought I'd just document a few learnings and thoughts.

To get started I created a really minimal case, you can see [a repo here](https://github.com/rowanwins/jsts-treeshaking-tests). I have jsts downloaded locally and I'm using [`npm link`](https://codurance.com/2016/12/21/how-to-use-npm-link/) so I can test against it easily.

So I thought I'd start with a basic starting point in my `index.js`
````
import WktReader from 'jsts/src/org/locationtech/jts/io/WKTReader'

var reader = new WktReader()
var a = reader.read('POINT (-20 0)')
````
As it stands my tree-shaked output comes out at 174kb (109kb minified)
- If I do a search on the word `class` in the `bundle.js` I get 145 matches, everything from `DimensionalComparator` to `Orientation` etc etc. Basically the `/src/org/locationtech/jts/geom/GeometryFactory.js` pulls in a lot...
- Obviously that's not very good if that's essentially a baseline starting point, any operation such as buffer is going to be additional to that baseline filesize....

I was reading the [thread here](https://groups.google.com/forum/#!topic/jsts-devs/yMidjp1xpDE) about dynamic imports however for building bundles those dynamic imports can be done at compile time of the bundling but not at runtime. For example I could pull out the point classes if I knew the points we're the only geometries people we're going to put in.

So not sure I've got any good suggestions just yet but thought I'd share the initial results...

Cheers

**Comment by bjornharrtell** [comment]
Hi @rowanwins, I'm not surprised by your findings. Essentially the JTS code base has pretty deep and complex dependencies. I've worked around the most problematic one by removing the shortcut methods to most complex operations on the Geometry class, but there are still some pretty deep ones.

Basically, IMHO this can really only be improved by refactoring JTS and some of that work could be impossible without breaking existing public API. I've done part of the work which was needed for the removal of shortcut methods in the transpilation process need this patch https://github.com/locationtech/jts/pull/200 which unfortunately is still open.

There is also an impedance between Java and JavaScript in that Java is a strictly object oriented language making it difficult to decouple code. I'm no Java expert but I think it needs careful use of interfaces, but there is no such thing in JavaScript. In JavaScript you can instead use functional design patterns to decouple code.

**Comment by dr-jts** [comment]
All good points @bjornharrtell .  I haven't had time to look at the refactoring PR, but in general I think it's a good direction to go.  Hopefully my new gig will breathe a bit of life into this.  

In the short term, if Turf only wants (say) buffer, would it be possible to manually remove other methods from Geometry which cause other stuff to be dragged in?  (Although do I remember you saying that you'd tried this and it only reduced lib size by about 50%?)

**Comment by bjornharrtell** [comment]
@dr-jts: With the exception of BoundaryOp, shortcut methods on Geometry to operations *are* removed in JSTS, but then added back in runtime with a monkey patch in the full build to be more compatible with upstream (and making ports of client code easier).
