### ISSUE TITLE
PointLocator class access

### ISSUE THREAD

**Issue by rowanwins** [bjornharrtell/jsts#377]
Hi there,

I've been trying to access the [PointLocator](https://github.com/bjornharrtell/jsts/blob/master/src/org/locationtech/jts/algorithm/PointLocator.js) class to run a point in polygon test.

Using the built version 
````
const jsts = require('jsts')
const PL = new jsts.algorithm.PointLocator()
````
I get `TypeError: jsts.algorithm.PointLocator is not a constructor`

I also had a go at building something based on the ES6 modules
````
import PointLocator from 'jsts/src/org/locationtech/jts/algorithm/PointLocator'

export function jsts (point, poly) {
    const pe = new PointLocator()
    return pe.intersects(point, poly);
}
````
However when I do that I get the wrong result for a simple case...

Am I missing anything obvious?

Thanks,
Rowan

**Comment by bjornharrtell** [comment]
You might be the first user of that class and I have no testcases for it so mabye it does not work. Can you provide more details on the unexpected result, or implement as a failing test case?

**Comment by rowanwins** [comment]
Hi @bjornharrtell 

I was pointed to this method by @dr-jts as the fastest way to do point in polygon checks using JTS. I was wanting to do a rough speed comparison to a new pip algorithm I've [implemented here](https://github.com/rowanwins/point-in-polygon-hao).

I'm using this [input of switzerland](https://gist.github.com/rowanwins/eb80c8bd4cd0e4155bfe31bd0e8e6dea) and my point is 
`{type: 'Point', coordinates: [8, 46.5]}` and it's currently returning as false when I would expect it to return true, however this is using my bundled version of the method that I created using rollup.

Hopefully that helps

**Comment by bjornharrtell** [comment]
It's likely there is nothing wrong with your rollup build. Not sure when I can get time to make a proper reproduction and continue investigating if there is a bug, if you want to assist please translate your case into a proper test case similar to fx. https://github.com/bjornharrtell/jsts/blob/master/test/manual/issues/279.js.

**Comment by dr-jts** [comment]
It's odd if this class isn't working, because it's pretty fundamental to several core JTS operations. E.g. it's used in the DistanceOp [here](https://github.com/bjornharrtell/jsts/blob/master/src/org/locationtech/jts/operation/distance/DistanceOp.js#L69).

@rowanwins Perhaps try using the [`PointLocator.locate`](https://github.com/bjornharrtell/jsts/blob/master/src/org/locationtech/jts/operation/distance/DistanceOp.js#L69) entry point?

**Comment by rowanwins** [comment]
That returns `2` which I gather means `Location.EXTERIOR` which is the opposite to what I'd expect.

**Comment by dr-jts** [comment]
Well that is very strange, since as mentioned I would think that would cause all kinds of other things to break.

**Comment by dr-jts** [comment]
If you want to get closer to the metal, try the [`PointLocation.isInRing`](https://github.com/bjornharrtell/jsts/blob/master/src/org/locationtech/jts/algorithm/PointLocation.js#L45) call.

**Comment by rowanwins** [comment]
I believe the `PointLocation.isInRing` method is working as expected, although I'm not 100% sure given that I'm not super familiar with the JSTS API. 

What I did was 
````
    const poly = reader.read({type: 'Polygon', coordinates: [[[1, 1], [1, 2], [2, 2], [2, 1], [1, 1]]]})
    const point = reader.read({type: 'Point', coordinates: [1.5, 1.5]})
    const pl = new PointLocation()
    const isInside = pl.constructor.isInRing(point, poly._shell);
    expect(isInside).to.be(true)
````

**Comment by dr-jts** [comment]
Well that's good news at least.

@rowanwins for the purposes of your performance testing calling the PIP algorithm that way should give the desired result.

**Comment by bjornharrtell** [comment]
@rowanwins the issue is that you are calling the API with wrong type, you are sending a Point when it expected a Coordinate. Except from API docs:

![Skärmbild från 2019-03-27 11-27-17](https://user-images.githubusercontent.com/141030/55068994-5d6eef80-5083-11e9-9b45-6f75bc6f7c00.png)

**Comment by rowanwins** [comment]
🤦‍♂️ doh 

Although the original issue of ` TypeError: jsts.algorithm.PointLocator is not a constructor` still exists

**Comment by bjornharrtell** [comment]
Right, I'll consider exposing it in the next release.

**Comment by bjornharrtell** [comment]
Done with https://github.com/bjornharrtell/jsts/commit/6d54fec05a2e075ec380880c8ee6f7e237442b25.
