### ISSUE TITLE
jsts object is missing utils package

### ISSUE THREAD

**Issue by oconnelc** [bjornharrtell/jsts#379]
The util package is not included in the jsts object. There are some useful classes, such as the org.locationtech.jts.util.GeometricShapeFactory. I'm not sure if this was done intentionally or just missed. 

For a node project, the workaround is to import the file directly: 
```
import GeomerticShapeFactory from 'jsts/src/org/locationtech/jts/util/'
var factory = new GeomerticShapeFactory ();
```

**Comment by wallw-bits** [comment]
I'll second this, but for `jsts/src/org/locationtech/jts/geom/util/`. I was specifically looking for [LineStringExtracter](https://github.com/bjornharrtell/jsts/blob/master/src/org/locationtech/jts/geom/util/LineStringExtracter.js).
