### ISSUE TITLE
Size is not a function

### ISSUE THREAD

**Issue by tmacintosh** [bjornharrtell/jsts#383]
I am using the jsts 2.0.4 library via the cdn in a asp.net webforms app.

I try to create a Point using the following code:
```
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jsts/2.0.4/jsts.min.js"></script>
<script type="text/javascript">
    var point = new jsts.geom.Point(new jsts.geom.Coordinate(0, 0));
</script>
```

And I keep getting the following error:
```
Uncaught TypeError: t.size is not a function
    at qt.init (Point.js:123)
    at qt.constructor_ (Point.js:140)
    at new qt (Point.js:14)
```

I saw a similar issue where within() needed to be declared upstream, is this a similar issue? Otherwise is there something I'm missing?

**Comment by bjornharrtell** [comment]
You should use https://github.com/bjornharrtell/jsts/blob/efe352bf39deece7ee9cb8b26fc7617ea0ccd160/src/org/locationtech/jts/geom/GeometryFactory.js#L135 to create points.

**Comment by tmacintosh** [comment]
Ok, thank you.
