### ISSUE TITLE
Investigate J2CL for transpilation?

### ISSUE THREAD

**Issue by dr-jts** [bjornharrtell/jsts#387]
Google has released a Java-to_Javascript transpiler called [J2CL](https://github.com/google/j2cl).  Perhaps it's worth a look?

**Comment by bjornharrtell** [comment]
As usual the interop seem complex - https://github.com/google/j2cl/blob/master/docs/jsinterop-by-example.md

**Comment by dr-jts** [comment]
Yeah, I thought that might be the case.  Carry on with your good work then!

**Comment by willcohen** [comment]
As a quick note here -- j2cl has an experimental j2wasm compiler that looks like it might not actually require annotations in the same way as j2cl. I'll see if I can get JTS to build that way, which might just let us call right into a wasm file rather than something fully transpiled to JS.

**Comment by willcohen** [comment]
Update -- getting bazel and all its dependencies to work on my computer has been a blocker for me. As an alternative, I'm now looking into https://github.com/oracle/graal/tree/master/web-image, which may accomplish the task a little more simply.

**Comment by willcohen** [comment]
As a quick update here -- j2wasm isn't baked enough for transpilation to work, there's just too much manual wrapper code that needs to be handwritten.

web-image, though, appears extremely positive. The implementation isn't complete, so much of the annotation that would make it more automated is still somewhat broken, but on the bright side, it fully compiles the JTS into some kind of a WASM file. Once I can get a clean example of creating, processing, and some io of a manipulated geometry, I'll get this posted into an initial repo. It's all still within GraalVM EA builds, so my guess is that the code to build the wasm wrapper will shift a lot in the coming years -- it seems, though, that it should be transparent to the end user, who just get a js wrapper over a wasm build.
