### ISSUE TITLE
jsts error in production mode (optimization)

### ISSUE THREAD

**Issue by vherbst** [bjornharrtell/jsts#389]
I have a strange issue in our angular app, in development mode everything works fine, however in production with optimization set to true we experience following error:
ERROR in ./node_modules/jsts/src/org/locationtech/jts/geom/util/AffineTransformation.js 10:15 Module parse failed: Unexpected token (10:15) You may need an appropriate loader to handle this file type.
Could this be an issue with webpack? Any experiences with certain versions which cause problems?

**Comment by bjornharrtell** [comment]
I have no idea what is causing this and have not seen similar problems.
