### ISSUE TITLE
InteriorPointLine broken when used as ES6 module 

### ISSUE THREAD

**Issue by kluthje** [bjornharrtell/jsts#391]
Hi

I tried to start using the ES6 module way of importing jsts but ran into a problem: If you try to use InteriorPointLine imported as ES6 module from the source files, it is broken because it tries to use .getCentroid() on Geometry object which is not present there in the ES6 module because the monkey patches are not run. See link:

https://github.com/bjornharrtell/jsts/blob/master/src/org/locationtech/jts/algorithm/InteriorPointLine.js#L73

**Comment by bjornharrtell** [comment]
Thanks for reporting.

**Comment by bjornharrtell** [comment]
Fixed by https://github.com/bjornharrtell/jsts/commit/c6a82e0b482342b1c775563e44ef97f934e35877
