### ISSUE TITLE
LineSequencer not available in the minified verstion

### ISSUE THREAD

**Issue by PauloSSAragao** [bjornharrtell/jsts#393]
Helllo Bjorn,
many thanks to provide this jts libray for javascript!!! It is very usefull!!!

currently I am using the minified verstion of jsts:
 <script src="https://unpkg.com/jsts@2.0.6/dist/jsts.min.js"></script>)

I am trying to use the available class jsts.operation.linemerge.LineSequencer, but it is not available, altough I can see in the source code in 2.0.6.

Maybe I am missing something??

Many thanks and kind regards!!!

**Comment by bjornharrtell** [comment]
Not every class is exposed in the minified build. Might consider it for a future release.

**Comment by PauloSSAragao** [comment]
> Not every class is exposed in the minified build. Might consider it for a future release.

Ok, many thanks!!!!

**Comment by bjornharrtell** [comment]
Done in https://github.com/bjornharrtell/jsts/commit/d165c86f0d405d74e4922add1e6f46f6223b4977.

**Comment by PauloSSAragao** [comment]
> Done in [d165c86](https://github.com/bjornharrtell/jsts/commit/d165c86f0d405d74e4922add1e6f46f6223b4977).

Cool, great news, many thanks :-)
