### ISSUE TITLE
How to calculate distance between 2 points?

### ISSUE THREAD

**Issue by jdang67** [bjornharrtell/jsts#394]
Hi, 

I just download jsts library and try to test the distance between 2 points and I'm not sure I'm doing the right way or not. 

``` javascript
  
const input1 =  geomFactory.createPoint(new jsts.geom.Coordinate (32.77240, -96.78402));
const input2 =  geomFactory.createPoint(new jsts.geom.Coordinate (32.78240, -96.75992));
console.log( "test distance:",  new jsts.operation.distance.DistanceOp( input1, input2).distance())

test distance:  0.026092336039540538
````
Since the output is too small,  I used google map to calculate the distance between these 2 points 
and got the straight distance about 1.56mi
![image](https://user-images.githubusercontent.com/8005940/68899012-5837e100-06f6-11ea-8e0d-8d8c1faad1ce.png)

It looks like the way I use the library is wrong. Can anyone who has experience with this library show me the right way to do this?  

thanks,

Jdang

**Comment by bjornharrtell** [comment]
Your units are not meters or miles, they are degrees. Also, this library only works on flat coordinate systems.
