### ISSUE TITLE
intersection is not a function

### ISSUE THREAD

**Issue by alefortvi** [bjornharrtell/jsts#395]
I am migrating from ol3 to ol6 and this code tells me that "intersection is not a function".

import JstOl3Parser from 'jsts/org/locationtech/jts/io/OL3Parser';

`let parser = new JstOl3Parser();`
`parser.inject(LineString, LinearRing, Polygon,  MultiLineString);`

`let geomFinca = parser.read(vm.InternalFinca.feature.getGeometry());`

(geoFinca) is a jsts/geom/Polygon object
... 
`for (const i = poligonos.iterator(); i.hasNext();) {`
      `const polygon = i.next();`
      `const feature = new ol.Feature();`
      `feature.setGeometry(parser.write(polygon));`
      `let geo = parser.read(feature.getGeometry());`
      `const intersection = geomFinca.intersection(geo);`
      `const supIntersection = intersection.getArea();`

...

**Comment by bjornharrtell** [comment]
This is by design. Read https://github.com/bjornharrtell/jsts#caveats.

**Comment by alefortvi** [comment]
Thank you. The final code is

`const intersection = OverlayOp.overlayOp(geomFinca,geo,OverlayOp.INTERSECTION);`

**Comment by bjornharrtell** [comment]
Seems right, but you could have used the shortcut at https://github.com/bjornharrtell/jsts/blob/b544f09052a38e11fce47fd7eeb564f57d747ec1/src/org/locationtech/jts/operation/overlay/OverlayOp.js#L41.

**Comment by alefortvi** [comment]
Ohh I can see.

`const intersection = OverlayOp.intersection(geomFinca,geo);`

Thanks again!
