### ISSUE TITLE
Missing validation in GeoJSONParser.read()

### ISSUE THREAD

**Issue by richard-ling** [bjornharrtell/jsts#398]
It's not clear to me whether JSTS' GeoJSONParser is expected to deal with invalid GeoJSON, or whether I'm supposed to have validated that with some other library (eg. GJV) before using GeoJSONParser.  In any case...

1. parse.Polygon() does not check for an undefined 'coordinates' member.
The following call will cause `TypeError: Cannot read property '0' of undefined`
`new GeoJSONParser().read({ type: 'Polygon' })`

2. parse.Polygon() does not check for an empty 'coordinates' array (ie, no rings are defined).
The following call will cause `TypeError: Cannot read property 'length' of undefined`
`new GeoJSONParser().read({ type: 'Polygon', coordinates: [] })`

This problem seems related to #390.

**Comment by bjornharrtell** [comment]
I don't think it's related to #390 because it's about valid GeoJSON that cannot be parsed.

I don't see anything wrong with the errors thrown for the invalid GeoJSON? If you need to handle it gracefully in a client you should catch and handle the error.
