### ISSUE TITLE
Error when intersect two polygon

### ISSUE THREAD

**Issue by phi-le** [bjornharrtell/jsts#401]
- This is my two polygon before operate intersect polygon:

![beforeclickAND](https://user-images.githubusercontent.com/12743581/78264325-3916e000-752d-11ea-8230-c0deae0e86a0.jpg)

**- And this is result:**
![afterclickAND](https://user-images.githubusercontent.com/12743581/78264413-58ae0880-752d-11ea-9be3-e752ba2a4e43.jpg)

**- I was try on other library:**
 + _SqlServer_:
![And_SqlServer](https://user-images.githubusercontent.com/12743581/78264648-a0cd2b00-752d-11ea-9753-112cd7d2b123.jpg)
 + _Postgis_:
![And_Postgis](https://user-images.githubusercontent.com/12743581/78264694-b04c7400-752d-11ea-9662-904d7cb3f831.jpg)

**Is it a error or property of jsts ?**

**Comment by bjornharrtell** [comment]
Should be similar or same result. Not sure what the cause is.
