### ISSUE TITLE
jsts.io.GeoJSONReader generate a opposite place

### ISSUE THREAD

**Issue by qy177** [bjornharrtell/jsts#406]
I use jsts.io.GeoJSONReader.read method to generate a Geometry.
But found that the place was generated at an opposite place.
Then I read the jsts/io/GeoJSONParser.js
Line 126

        'coordinates': function(array) {
            var coordinates = [];
            for (var i = 0; i < array.length; ++i) {
                var sub = array[i];
                coordinates.push(new jsts.geom.Coordinate(sub[0], sub[1]));
            }
            return coordinates;
        },

due to the GeoJSON's coordinates are opposite to the normal coordinates.
Maybe it should be 
coordinates.push(new jsts.geom.Coordinate(sub[1], sub[0]));

Thank you

**Comment by bjornharrtell** [comment]
Mabye. Mabye not.
