### ISSUE TITLE
'disjoint'  no implementation in 'RelateOp'

### ISSUE THREAD

**Issue by pecet86** [bjornharrtell/jsts#412]
Hello, I caught the lack of implementation of the method in a large number of newer versions of JSTS

Version bug: 1.5.0 - 2.5.0

in version 1.4.0 there is:
`RelateOp.disjoint = function (g1, g2) {
	return !g1.intersects(g2);
};`
in newer versions there is no this entry [(RelateOp.js 2.5.0)](https://github.com/bjornharrtell/jsts/blob/2.5.0/src/org/locationtech/jts/operation/relate/RelateOp.js)

so the entry [(monkey.js)](https://github.com/bjornharrtell/jsts/blob/master/src/org/locationtech/jts/monkey.js):
`Geometry.prototype.disjoint = function(g) {
  return RelateOp.disjoint(this, g)
}`
does not make sense

I even found a security for it in:
[BasicPreparedGeometry.js](https://github.com/bjornharrtell/jsts/blob/master/src/org/locationtech/jts/geom/prep/BasicPreparedGeometry.js)

**Comment by bjornharrtell** [comment]
You are correct, it's a bug and regression.

In the meantime the workaround is to use the inverse of intersects (i.e doing `!RelateOp.intersects(this, g)`) should give the disjoint result.

**Comment by bjornharrtell** [comment]
Fixed in upstream patch https://github.com/bjornharrtell/jts/commit/28f5ed1e016b70a04be00f55c9dfded08dd50641.
