### ISSUE TITLE
Huge buffer in mercator projection 3857

### ISSUE THREAD

**Issue by slavas62** [bjornharrtell/jsts#416]
Hello. I am creating a large buffer for a point with a radius of more than 2000 km in the Mercator projection (3857). In this case, the center of the buffer always coincides with the parent point. This is normal for low latitudes. For mid and high latitudes, distortion should appear in the form of an offset of the center of the buffer in latitude relative to the parent point, but there is no distortion.
Thanks!

**Comment by bjornharrtell** [comment]
I believe you are trying to say you expect results to be calculated using geodetics. JSTS/JTS works in a Cartesian, planar, 2-dimensional space only. See https://locationtech.github.io/jts/jts-faq.html#F1.
