### ISSUE TITLE
Where is method angleBetweenCoords

### ISSUE THREAD

**Issue by themrxcm** [bjornharrtell/jsts#417]
Hi!
Please return method "angleBetweenCoords"! 
[angleBetweenCoords](https://bjornharrtell.github.io/jsts/doc/api/jsts.algorithm.Angle.html)

**Comment by bjornharrtell** [comment]
It's been renamed to "angle", see https://locationtech.github.io/jts/javadoc/org/locationtech/jts/algorithm/Angle.html#angle-org.locationtech.jts.geom.Coordinate-org.locationtech.jts.geom.Coordinate-.

The API docs you refer to are old, obsolete and will be removed with https://github.com/bjornharrtell/jsts/issues/396.

**Comment by themrxcm** [comment]
Thanks!
