### ISSUE TITLE
distance.DistanceOp.nearestPoints throwing error

### ISSUE THREAD

**Issue by JamesLMilner** [bjornharrtell/jsts#423]
Hello! Firstly, thanks for all your hard work. I wanted to raise a issue to say that it appears that `distance.DistanceOp.nearestPoints` doesn't work as expected. When I do something like this:

```typescript
            const jstsLine = reader.read({
                type: 'Feature',
                properties: {},
                geometry: { type: 'LineString', coordinates: [[...someCoordinatesOne], [...someCoordinatesTwo]] }
            });
            const jstsPoint = reader.read({
                type: 'Feature',
                properties: {},
                geometry: { type: 'Point', coordinates: [...someCoordinatesThree] }
            });

 
            const nearestPoint = jsts.operation.distance.DistanceOp.nearestPoints(jstsLine, jstsPoint);
```

Where the GeoJSON line and point are known to be valid - the code will throw `Uncaught TypeError: n.getDimension is not a function`. Any ideas as to what might be going on there? I also tried the `isWithinDistance` on `DistantOp` which also threw an error. Thanks in advance!

**Comment by bjornharrtell** [comment]
Hmm that's wierd. Cannot reproduce with a test case (see https://github.com/bjornharrtell/jsts/commit/d487a6012b29804ac08db14031e30aa1d4e5586c) so not sure what's going on here. Possibly something with the bundling/babelification but I would be surprised. Can you try this with a unminified bundle and provide a full stack trace?

**Comment by bjornharrtell** [comment]
@JamesLMilner I think I see your problem. You are parsing GeoJSON features not geometry so you do not have geometry instances for jstsLine and jstsPoint and internal logic then fails on missing expected member getDimension which exists on geometry instances.

**Comment by JamesLMilner** [comment]
@bjornharrtell yes that turned out to be the issue! All working correctly now - sorry for disturbing.
