### ISSUE TITLE
Buffer with custom JOIN style?

### ISSUE THREAD

**Issue by ablakey** [bjornharrtell/jsts#426]
I am buffering a linestring and I can set the END_CAP but not the JOIN style. I've dug through the docs and code and it looks like it's not exposed anywhere? 

Any ideas on how I might get this, even if it's hacky?

I can get the poly on the left, but what I want is the poly on the right.

![image](https://user-images.githubusercontent.com/9021944/113052918-b5122b00-9175-11eb-9fed-2a5de0f40317.png)

Thank you!

**Comment by noamgat** [comment]
This is also relevant for me.

**Comment by noamgat** [comment]
`import { operation } from 'jsts';

// Like jstsPoly.buffer(distance), but will use straight perpendicular lines rather than curves or diagonals
export const bufferStraight = (jstsPoly, distance) => {
  const bufParams = new operation.buffer.BufferParameters(2,
    operation.buffer.BufferParameters.CAP_FLAT,
    operation.buffer.BufferParameters.JOIN_MITRE,
    10);

  const bufferOp = new operation.buffer.BufferOp(jstsPoly, bufParams);
  const resultPoly = bufferOp.getResultGeometry(distance);
  return resultPoly;
};
`

**Comment by bjornharrtell** [comment]
Can you confirm that gives the desired result @noamgat?

PS. You can import the individual classes instead of using "operation", it will be shorter code and possibly will also bundle into a smaller build.

**Comment by noamgat** [comment]
For us it works. I did not post the original question and don't have the source code that generated the screenshot.

**Comment by bjornharrtell** [comment]
Thanks @noamgat that's good enough for me to close this.

My recommendation is to import individual classes. The "namespaces" modules are really only intended for the single file build.

**Comment by ablakey** [comment]
Thanks for this.  I'm excited to test it out on the above code today once I've had some coffee.

**Comment by ablakey** [comment]
![image](https://user-images.githubusercontent.com/9021944/120324351-8834de00-c2b4-11eb-8645-bfad9cb866f0.png)
Beautiful!

Thank you for this tip. Had no idea I could interact with buffer through `operation.`
