### ISSUE TITLE
Why are the jsts.precision.EnhancedPrecisionOp classes missing in the build?

### ISSUE THREAD

**Issue by iGureEV** [bjornharrtell/jsts#429]
The project build previously included more classes, for example, after version 0.17.0, the classes disappeared:
- jsts.precision.CommonBits
- jsts.precision.CommonBitsOp
- jsts.precision.CommonBitsRemover
- jsts.precision.CommonCoordinateFilter
- jsts.precision.Translater
- jsts.precision.EnhancedPrecisionOp

But there was a previously missing class:
- jsts.precision.GeometryPrecisionReducer

In the project, classes were noticed that were missing in 0.17.0, but also not included in the assembly (their work was not checked):
- jsts.precision.CoordinatePrecisionReducerFilter
- jsts.precision.MinimumClearance
- jsts.precision.PrecisionReducerCoordinateOperation
- jsts.precision.SimpleMinimumClearance

Scripts for missing classes are present in the project, but not included in the build

```
//File: jsts\src\org\locationtech\jts\precision.js

import GeometryPrecisionReducer from './precision/GeometryPrecisionReducer'

export {
  GeometryPrecisionReducer
}
```

although adding them doesn't break anything

```
//File: jsts\src\org\locationtech\jts\precision.js

import CommonBits from './precision/CommonBits'
import CommonBitsOp from './precision/CommonBitsOp'
import CommonBitsRemover from './precision/CommonBitsRemover'
import EnhancedPrecisionOp from './precision/EnhancedPrecisionOp'
import GeometryPrecisionReducer from './precision/GeometryPrecisionReducer'

export {
  CommonBits,
  CommonBitsOp,
  CommonBitsRemover,
  EnhancedPrecisionOp,
  GeometryPrecisionReducer
}
```

Tell me, for what reason these classes are not included in the assembly, because they have not changed in JTS since the manual migration in version 0.17.0?

The dependencies of the listed classes are not far behind JTS. In other words, the assembly with them is quite working.

**Comment by bjornharrtell** [comment]
Three reasons:

1. Originally when making 1.0 (which was a complete remaking of JSTS from the 0.x series) I had to make the bundle entry point manually and decided to only include classes I had experience with and use for
2. Including all/most classes would increase the bundle size (but probably not much so this is very minor)
3. I don't think I've used the single file build in years, instead I use the npm package and when doing that the entry points are irrelevant and you can use any class you need

I have no immediate plans to make any changes so I would suggest to use the method in 3 above.
