### ISSUE TITLE
Direct access to OffsetCurveBuilder via npm?

### ISSUE THREAD

**Issue by noamgat** [bjornharrtell/jsts#432]
Hello,
I would like to use some of the functionality of OffsetCurveBuilder:

https://github.com/bjornharrtell/jsts/blob/master/src/org/locationtech/jts/operation/buffer/OffsetCurveBuilder.js

But it is not present in operation.buffer when I import 

import { geom, operation } from 'jsts';

Is it possible to use this class directly when working with the npm package?

**Comment by bjornharrtell** [comment]
Yes, import `jsts/org/locationtech/jts/operation/buffer/OffsetCurveBuilder`.
