### ISSUE TITLE
WKTParser issues with z coordinates

### ISSUE THREAD

**Issue by johndiiorio** [bjornharrtell/jsts#433]
Hello. I have noticed a couple issues with the jts/io/WKTParser.js pertaining to z coordinates, which results in improperly written WKT.

- The function `encodeLineStringGeometry` drops any `z` coordinates when encoding. I'd imagine that if the `z` coordinate exists (including 0), it should be included.
- The function `encodeGeometryLayout` has a `if (c.z) { dimInfo += Z }` block. This does not execute if `c.z = 0`.

**Comment by bjornharrtell** [comment]
Nice catch. :)

**Comment by bjornharrtell** [comment]
Fixed by https://github.com/bjornharrtell/jsts/commit/af188e2c96b0ad91cf47d78592ab83cf23660e4b and released as 2.6.2.
