### ISSUE TITLE
DelaunayTriangulationBuilder return error

### ISSUE THREAD

**Issue by ericzdj0522** [bjornharrtell/jsts#434]
Hi bjornharrtell,
    I'm trying to use DelaunayTriangulationBuilder in JSTS to generate a Delaunay Triangle from a set of points, I'm refering to this example:[https://github.com/edmarmoretti/i3geo/blob/master/pacotes/jsts/old/examples/triangulation.html], but when I reach line 23, the getTriangle function will report error, which means triangle result won't be returned.
    Also for line 22, if I feed a geometry instead of a set of coordinates, the setSites function also will report error, as i read source code and JTS doc, this function supposed to take either input.
    Do you know if this is a API issue or there is a better way to perform this triangulation process? I've tested whole day, really appreciate your help!

**Comment by bjornharrtell** [comment]
Not sure how I can help. Perhaps this test case can help? https://github.com/bjornharrtell/jsts/blob/master/test/manual/triangulate/DelauneyTriangulationBuilder.js

**Comment by ericzdj0522** [comment]
Thanks a lot Bjornharrtell! I found exactly this example 5 hours ago and it worked! One more question, now it's working with WKT format, does this triangulation function take other format of points input? Like in that old demo, Multipoints from JTS.geom or regular jsts coordinates both not worked well this triangulation function! Thanks again!

**Comment by bjornharrtell** [comment]
DelaunayTriangulationBuilder setSites takes geometry as input not WKT, here:

https://github.com/bjornharrtell/jsts/blob/af188e2c96b0ad91cf47d78592ab83cf23660e4b/test/manual/triangulate/DelauneyTriangulationBuilder.js#L14

The test case uses WKT and a WKTReader to convert that format to geometry. There are several other ways to convert or construct geometry.
