### ISSUE TITLE
Read/parse of valid wkt fail, jsts version > 2.0.4

### ISSUE THREAD

**Issue by bad-ch** [bjornharrtell/jsts#438]
I try to parse/read a valid WKT definition with the current version 2.7.1, in the jsts version <= 2.0.4 that has worked with the following code:

var wktGeometryA = 'POLYGON((1301712.757865992 6026164.346872674,1301669.7465115704 6026170.404811879,1301664.2943687106 6026171.616395722,1301615.83087192 6026176.765641262,1301605.8352784396 6026177.977221535,1301585.5411924808 6026180.40040435,1301582.332685697 6026182.526422543,1301589.7694125674 6026211.563888157,1301616.739922689 6026205.842624029,1301634.4706453828 6026207.233407627,1301673.0791028552 6026204.932816303,1301693.9789898398 6026203.721227319,1301743.9573375955 6026227.648949694,1301752.1362757408 6026214.016353954,1301726.3911354416 6026193.1131246565,1301712.757865992 6026164.346872674))';

var factory = new jsts.geom.GeometryFactory(new jsts.geom.PrecisionModel(jsts.geom.PrecisionModel.maximumPreciseValue));
var reader = new jsts.io.WKTReader(factory);
var featureAGeometry = reader.read(wktGeometryA);

var isValidA = jsts.operation.valid.IsValidOp.isValid(featureAGeometry);

Now I get an error at the last line (because the read operation has not delivered a proper object):

Uncaught TypeError: this.map.set is not a function in the put method.

Any ideas ?

**Comment by bjornharrtell** [comment]
Cannot reproduce in isolated test (commited with https://github.com/bjornharrtell/jsts/commit/cad4e303b193864b47f43e081370c9d11bef9d0f). I'll have to see if I can reproduce with the bundled variant.

**Comment by bjornharrtell** [comment]
I cannot reproduce in browser with bundled jsts either. Which browser(s) have you tried @bad-ch?

**Comment by bad-ch** [comment]
I was trying out several minified versions from here https://cdnjs.com/libraries/jsts/ (> v.2.0.4) and the browser firefox version 90.0.2

**Comment by bad-ch** [comment]
I will give it a try on a chrome browser as well

**Comment by bad-ch** [comment]
I think it's not a problem from your framework. In the HashMap class you are instancing a new Map() object (and you assume that it is a Openlayers Map object). But in our case it's a different class, which has not a set method.
