### ISSUE TITLE
Inflated Polygon does not Match Original Polygon

### ISSUE THREAD

**Issue by bjvesely** [bjornharrtell/jsts#439]
I am seeing a possible issue where the inflated polygon does not match the original polygon as shown in attached image with the red polygon. 
I specify that no special corner should be displayed as shown in the code below.

 var shell = geometryFactory.createPolygon(geoInput);
 //should be no special corners with zero value
 var polygon = shell.buffer(spacing,0)

![Capture](https://user-images.githubusercontent.com/77748095/128238584-e0626ed8-f324-478b-a7de-0a26e9f11524.JPG)

My goal is to get the exact copy of the polygon below in grey/green.   Is this a issue or something that I am doing wrong?

![Capture1](https://user-images.githubusercontent.com/77748095/128239176-1901da4b-cc0a-4937-a76c-fa953868be04.JPG)

Thank you in advance,
B.V.

**Comment by js-virdi** [comment]
can we get the coordinates of the buffer also?

**Comment by bjornharrtell** [comment]
Closing due to lack of info.
