### ISSUE TITLE
2.7.2 regression - Error: export 'io' (imported as 'jsts') was not found in 'jsts' (module has no exports)

### ISSUE THREAD

**Issue by tomgruszowski** [bjornharrtell/jsts#442]
Building on latest Angular (12.x) which uses Webpack 5 under the hood, TypeScript 4.2.4.

JSTS usage is:
import * as jsts from 'jsts';

and then inside a local method:
const reader = new jsts.io.GeoJSONReader();

also using @types/jsts: "^0.17.5" for typings

Should I be using a more specific import scheme?

Will try to provide a more reproducible example if this is not enough detail.

**Comment by tomgruszowski** [comment]
@bjornharrtell was there anything in 2.7.2 that would have caused this? I had a quick scan through changes and noticed that it was mostly updating references to include .js as well build tool updates.

I won't have time to look into this today so sticking to 2.7.1 for now, but please keep this issue open and I'll follow-up with some details, or maybe we'll see someone else with more insight into this problem.

**Comment by bjornharrtell** [comment]
@tomgruszowski I've switched to so called module package (https://github.com/bjornharrtell/jsts/blob/fff51f25065a012180d5ef7e535e525357f8be8d/package.json#L35) and it probably has something to do with that but I don't understand what yet. I have reproduced it in a few dependent projects of mine so I'm just as interested as you to find out and fix this. :)

**Comment by bjornharrtell** [comment]
Hmm I was too quick to conclude I could reproduce.. I actually have it working in a project using webpack 5 but I have a problem with another package of mine (https://github.com/flatgeobuf/flatgeobuf) with something similar but not quite the same.

**Comment by gvdhorst** [comment]
I'm experiencing a very similar issue using ES6 modules on Node.js.
I've noticed /dist/jsts.es6.* is missing, I suspect that's part of what's causing this.

On node.js the following works with 2.7.1:
`import jsts from 'jsts';`
But with 2.7.2 it causes the following error:
**export 'default' (imported as 'jsts') was not found in 'jsts' (module has no exports)**

**Comment by bjornharrtell** [comment]
@gvdhorst the jsts.es6.js single file build should not be relevant it is not referred to from package.json and I have only made it as an internal experiment. But I think the problem is that webpack tries to resolve 'jsts' to what is "main" in package.json (dist/jsts.min.js) and that is not an ES module.

I really don't want jsts to have an entry point at all, so I will see what happens if I publish a package without "main". It should mean you cannot import 'jsts' but that's the intent, the idea is to import individual modules.

**Comment by bjornharrtell** [comment]
Published as 2.7.3.

**Comment by bjornharrtell** [comment]
I've updated the instructions for Node.js use to read:

For Node.js 14+, install using `npm install jsts` after which you can import individual modules with fx. `import GeoJSONReader from 'jsts/org/locationtech/jts/io/GeoJSONReader'`.

This works for me. The old instruction with require('jsts') was very out of date and I do not intend to support it any longer.

**Comment by tomgruszowski** [comment]
@bjornharrtell I agree with yu-tou, and I mean this in as constructive way as possible. There was a similar issue prior to 2.7, a patch version broke things quite significantly for us. This is the only package that I have locked to exact version because I need to always vet the changes. I'd suggest anything that is not a bug fix should be at least a minor version update. Thanks for your hard work on this :)

**Comment by bjornharrtell** [comment]
I did not *intend* to break anything that is why it was patch level. Npm packaging is a mess these days and the transition away from cjs in the node world is a mess. So excuse me for not getting it perfectly right but then again this project is kind of on life support to be honest.

**Comment by tomgruszowski** [comment]
@bjornharrtell  apologies for coming across in a certain way, I never intended to suggest blame, bugs happen, it's life. Mostly that patch versions are often very small changes, like typos and to maybe use minor version instead for anything that's not trivial. Appreciate your work on this project. 

As a side question, since you mentioned life support, is there another project of this type that does what JSTS does?

**Comment by bjornharrtell** [comment]
@tomgruszowski no worries we all have our point of views. 🙂

There is turfjs that tried to provide a more modern/easy API but I don't like it for several reasons and it actually uses a now unnecessary fork of jsts for some operations.
