### ISSUE TITLE
this is my test data,why return false ?

### ISSUE THREAD

**Issue by Cherry-Ran** [bjornharrtell/jsts#446]
here is my test demo ,i can't understand why this result isfalse ? 
         
var reader = new jsts.io.WKTReader()
            var jstsPoly1 = reader.read('POLYGON((106.57322276 29.57264283, 106.57165706 29.56381264, 106.5678092 29.55092201, 106.55788218 29.54906528, 106.55742723 29.55457311, 106.55433217 29.55804952, 106.54840393 29.56658392, 106.54690398 29.56642771, 106.54852212 29.56999239, 106.55107361 29.57285701, 106.56458456 29.5744905, 106.57322276 29.57264283))')
            var jstsPoly2= reader.read('POLYGON((106.57108465 29.56290442, 106.558 29.5637, 106.55790005 29.55760945, 106.56319913 29.55733367, 106.56881362 29.55661661, 106.57108465 29.56290442))')
            console.log('jsts运算结果：',jsts.operation.relate.RelateOp.overlaps(jstsPoly2, jstsPoly1))

**Comment by Cherry-Ran** [comment]
![5C685BCE-7DBF-4138-A564-7078553FB41D](https://user-images.githubusercontent.com/32769218/140450768-350c2fbc-e2bd-4c2d-a6be-a62fa9cc23e9.png)


the red is jstsPoly1  and yello is jstsPoly2 ,the two are in an intersecting relationship

**Comment by bjornharrtell** [comment]
Please research the definition of overlaps in context of SFS and DE-9IM (https://en.wikipedia.org/wiki/DE-9IM).

**Comment by Cherry-Ran** [comment]
> Please research the definition of overlaps in context of SFS and DE-9IM (https://en.wikipedia.org/wiki/DE-9IM).

hello sir，this is my first use this JS tool,what shuold i do?What function should I use，please tell me

**Comment by gevrum** [comment]
Please check out the examples: https://bjornharrtell.github.io/jsts/
