### ISSUE TITLE
Will the GeometryFixer be ported from the JTS library?

### ISSUE THREAD

**Issue by gevrum** [bjornharrtell/jsts#448]
Hello.  
In the spring of this year, a tool for correcting topology errors finally appeared in JTS - a group of classes ending with GeometryFixer (see [article](http://lin-ear-th-inking.blogspot.com/2021/05/fixing-invalid-geometry-with-jts.html)).  
Will JSTS be updated to support these classes?

**Comment by bjornharrtell** [comment]
See https://github.com/bjornharrtell/jsts/issues/422. (used in GeometryFixer)

**Comment by dr-jts** [comment]
You could just use the current `union` operation. `GeometryFixer` should work fine with that for most cases.

**Comment by gevrum** [comment]
It doesn't always work. Using `buffer(0)` also does not save.
Ok, I'll do the translation of the code from JTS...

**Comment by gevrum** [comment]
The absence of such a type as `IllegalStateException` in JS does not cause an error?
It seems to me that a description of this type of exception is required...
