### ISSUE TITLE
Imports broken since v2.7.2

### ISSUE THREAD

**Issue by ludvigeriksson** [bjornharrtell/jsts#451]
I'm importing the io module like this: `const { io } = require("jsts");`. This worked until v2.7.2., now I get `Error: Cannot find module 'jsts'`.

**Comment by bjornharrtell** [comment]
I never intended to support importing in that way, the jsts module was intended only for single file builds. See https://github.com/bjornharrtell/jsts#browser-or-nodejs-use.

**Comment by ludvigeriksson** [comment]
The import syntax is only valid in ES modules (you get `SyntaxError: Cannot use import statement outside a module`). How do I import it in a Node (CommonJS) project?

**Comment by bjornharrtell** [comment]
As of version 14 node supports ES modules.

**Comment by ludvigeriksson** [comment]
I am using Node v16 when I'm getting that error. However, I think I would have to declare my entire project as an ES module (`"type": "module"` in my package.json) which would mean my other require imports would break? Or am I missing something?

**Comment by bjornharrtell** [comment]
Yes, either declare your project as a module project or use mjs extension to treat an individual source file as a module. AFAIK node had to do it this way because there was no reasonable way to support both cjs and es modules without a clean break.

In retrospect I should have bumped major version of jsts to indicate this as a breaking change, but at the time it was not obvious to me that it would affect usage in this way and in either case it's too late now.

**Comment by ludvigeriksson** [comment]
I did some research and it seems the only way to import an ES6 module into CommonJS is by using a [dynamic import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#dynamic_imports) ([node docs](https://nodejs.org/docs/latest-v16.x/api/esm.html#interoperability-with-commonjs)), which is asynchronous (e.g. `const GeoJSONReader = (await import("jsts/org/locationtech/jts/io/GeoJSONReader.js")).default`). It might be worth adding this as an example to the readme or somewhere in the docs?

**Comment by bjornharrtell** [comment]
That could possibly be added as a note in https://github.com/bjornharrtell/jsts#browser-or-nodejs-use or a bullet in https://github.com/bjornharrtell/jsts#caveats.

**Comment by bjornharrtell** [comment]
It's all well explained at https://nodejs.org/api/esm.html so I've settled with refencing that page in the node js section of the readme.
