### ISSUE TITLE
Advice on keeping track of polygons by ID?

### ISSUE THREAD

**Issue by ablakey** [bjornharrtell/jsts#455]
Is there a JSTS/JTS API for bringing non-spatial attributes along for the ride when I convert GeoJSON into JSTS polygons?

- Make an R-tree of 10,000 polygons (originally 10,000 GeoJSON features, with properties and IDs)
- Search the R-tree
- Perform an `intersects` test on search results
- Get a collection of polygons that intersect the input polygon.
- Know, by ID, which polygons were returned so that I can perform more attribute analysis on their non-JSTS GeoJSON-like Features.

Once I feed my GeoJSON into JSTS, I lose their IDs and cannot get them back.

I've searched the docs and online for ideas for doing this. I've done some silly stuff like keeping ordered lists of both. But it breaks when I try to do bulk collection operations or filter operations that mucks with the ordering.

Thank you!

**Comment by dr-jts** [comment]
In JTS you can use `Geometry.setUserData(Object)` to add attributes to `Geometry` objects.  Not sure if this has been ported to JSTS.

Or, in Java you can use a side `HashMap` to associate data with `Geoemetry` objects.

**Comment by ablakey** [comment]
Thanks for that lead! I'll see if `setUserData` is available in JSTS.

Yeah I did a but of clever stuff with JS `Map` but the ergonomics for some data pipelines is pretty bad.

**Comment by ablakey** [comment]
Yup, `setUserData` and `getUserData` seem to be implemented in JSTS and solve my problems.  The JTS Java Docs are quite... busy and I surely was just looking for the wrong terms like `attributes` and `properties`. 

Thanks again for helping me with this.
