### ISSUE TITLE
Incorrect buffer around polyline

### ISSUE THREAD

**Issue by Ritzi1708** [bjornharrtell/jsts#456]
I am trying to create a buffered polygon around polyline using below code snippet:

***************************************************
const distance = 1.609 / 111.12; // distance of 1 meter in degree
const geometryFactory = new jsts.geom.GeometryFactory();
const geoInput = overviewPath.map((x: any) => new jsts.geom.Coordinate(x.lat(), x.lng()));

const shell = geometryFactory.createLineString(geoInput);
const polygon = shell.buffer(distance, 1000, 1);
const oCoordinates = polygon.getCoordinates();
const fencePoints: any[] = [];
const oCoordinates = polygon.getCoordinates();
for (const oItem of oCoordinates) {
	fencePoints.push(new google.maps.LatLng(oItem.x, oItem.y));
}
 const poly = new google.maps.Polygon({
    paths: fencePoints,
    strokeColor: "#FF0000",
    strokeOpacity: 0.8,
    strokeWeight: 2,
    fillColor: "#FF0000",
    fillOpacity: 0.35,
  });

  poly.setMap(map);

***************************************************************************
Mostly it gets plotted correctly but sometimes (like for below dataset) it is not buffering the whole polyline(image attached).

Point A - 3 Whitehall, London SW1A 2DD, UK
to Point B - Carr. Madrid, 12, 28703 San Sebastián de los Reyes, Madrid, Spain

[{"lat":51.507220000000004,"lng":-0.12759},{"lat":51.525980000000004,"lng":0.07532000000000001},{"lat":51.52449000000001,"lng":0.15049},{"lat":51.49400000000001,"lng":0.24124},{"lat":51.497640000000004,"lng":0.27038},{"lat":51.47296000000001,"lng":0.26545},{"lat":51.4412,"lng":0.23875000000000002},{"lat":51.4042,"lng":0.21011000000000002},{"lat":51.38434,"lng":0.21461000000000002},{"lat":51.359550000000006,"lng":0.26943},{"lat":51.32081,"lng":0.28022},{"lat":51.311440000000005,"lng":0.41402000000000005},{"lat":51.29674000000001,"lng":0.49698000000000003},{"lat":51.27599000000001,"lng":0.59374},{"lat":51.22429,"lng":0.7018000000000001},{"lat":51.18319,"lng":0.8364},{"lat":51.12769,"lng":0.9305700000000001},{"lat":51.092020000000005,"lng":1.0871300000000002},{"lat":51.09910000000001,"lng":1.1745100000000002},{"lat":51.11348,"lng":1.2501600000000002},{"lat":51.092310000000005,"lng":1.34037},{"lat":50.9172,"lng":1.8076900000000002},{"lat":50.94267000000001,"lng":1.8179},{"lat":50.91010000000001,"lng":1.78289},{"lat":50.84774,"lng":1.71984},{"lat":50.74437,"lng":1.62809},{"lat":50.723220000000005,"lng":1.64823},{"lat":50.70013,"lng":1.63369},{"lat":50.67714,"lng":1.6627800000000001},{"lat":50.65542000000001,"lng":1.6581000000000001},{"lat":50.59348000000001,"lng":1.6438800000000002},{"lat":50.552020000000006,"lng":1.67189},{"lat":50.48884,"lng":1.68344},{"lat":50.460770000000004,"lng":1.7014500000000001},{"lat":50.427110000000006,"lng":1.69398},{"lat":50.3412,"lng":1.69466},{"lat":50.27913,"lng":1.73347},{"lat":50.21388,"lng":1.7537200000000002},{"lat":50.16485,"lng":1.7635500000000002},{"lat":50.1358,"lng":1.8101200000000002},{"lat":50.104290000000006,"lng":1.7848700000000002},{"lat":50.06593,"lng":1.7899600000000002},{"lat":49.986110000000004,"lng":1.68476},{"lat":49.844750000000005,"lng":1.5488000000000002},{"lat":49.784290000000006,"lng":1.4832200000000002},{"lat":49.754430000000006,"lng":1.48415},{"lat":49.722120000000004,"lng":1.4420400000000002},{"lat":49.66138,"lng":1.30299},{"lat":49.63904,"lng":1.2681200000000001},{"lat":49.59756,"lng":1.27411},{"lat":49.553200000000004,"lng":1.2546400000000002},{"lat":49.524660000000004,"lng":1.2005100000000002},{"lat":49.4894,"lng":1.14381},{"lat":49.44395,"lng":1.13625},{"lat":49.42503000000001,"lng":1.05373},{"lat":49.400400000000005,"lng":1.03214},{"lat":49.384370000000004,"lng":1.04811},{"lat":49.339110000000005,"lng":0.9884900000000001},{"lat":49.361580000000004,"lng":0.83172},{"lat":49.32873000000001,"lng":0.82803},{"lat":49.29833000000001,"lng":0.79276},{"lat":49.24830000000001,"lng":0.7738900000000001},{"lat":49.19559,"lng":0.77031},{"lat":49.165620000000004,"lng":0.7287600000000001},{"lat":49.163610000000006,"lng":0.6556200000000001},{"lat":49.13993000000001,"lng":0.5529400000000001},{"lat":49.074490000000004,"lng":0.47377},{"lat":48.923660000000005,"lng":0.40677},{"lat":48.812780000000004,"lng":0.34748},{"lat":48.73626,"lng":0.26335000000000003},{"lat":48.64170000000001,"lng":0.21066000000000001},{"lat":48.567190000000004,"lng":0.17495000000000002},{"lat":48.50292,"lng":0.12836},{"lat":48.424020000000006,"lng":0.1373},{"lat":48.39025,"lng":0.10718000000000001},{"lat":48.33214,"lng":0.10954000000000001},{"lat":48.29016000000001,"lng":0.15444000000000002},{"lat":48.23333,"lng":0.17007000000000003},{"lat":48.188550000000006,"lng":0.17052},{"lat":48.13299000000001,"lng":0.14374},{"lat":48.088170000000005,"lng":0.17651000000000003},{"lat":48.054410000000004,"lng":0.18435},{"lat":48.050070000000005,"lng":0.28944000000000003},{"lat":48.00432000000001,"lng":0.30870000000000003},{"lat":47.97191,"lng":0.32979},{"lat":47.91552,"lng":0.29985},{"lat":47.82184,"lng":0.30689000000000005},{"lat":47.773410000000005,"lng":0.31343000000000004},{"lat":47.72272,"lng":0.34166},{"lat":47.68433,"lng":0.36771000000000004},{"lat":47.661120000000004,"lng":0.41423000000000004},{"lat":47.61919,"lng":0.51871},{"lat":47.527100000000004,"lng":0.6220800000000001},{"lat":47.48572,"lng":0.6757500000000001},{"lat":47.48337,"lng":0.73867},{"lat":47.47263,"lng":0.7582500000000001},{"lat":47.450050000000005,"lng":0.7450500000000001},{"lat":47.39549,"lng":0.70672},{"lat":47.28302,"lng":0.6809000000000001},{"lat":47.122870000000006,"lng":0.6055},{"lat":47.044560000000004,"lng":0.58348},{"lat":46.97661,"lng":0.54651},{"lat":46.88376,"lng":0.51768},{"lat":46.78703,"lng":0.5059400000000001},{"lat":46.72419000000001,"lng":0.38906},{"lat":46.633630000000004,"lng":0.35216000000000003},{"lat":46.563010000000006,"lng":0.28674000000000005},{"lat":46.507450000000006,"lng":0.20629000000000003},{"lat":46.49983,"lng":0.09487000000000001},{"lat":46.464220000000005,"lng":0.016880000000000003},{"lat":46.394510000000004,"lng":-0.18018},{"lat":46.333090000000006,"lng":-0.325},{"lat":46.265950000000004,"lng":-0.41241000000000005},{"lat":46.159740000000006,"lng":-0.51539},{"lat":45.94623000000001,"lng":-0.5571},{"lat":45.88523000000001,"lng":-0.6166100000000001},{"lat":45.81917000000001,"lng":-0.6492100000000001},{"lat":45.73481,"lng":-0.6647500000000001},{"lat":45.62521,"lng":-0.6107400000000001},{"lat":45.57725000000001,"lng":-0.59965},{"lat":45.52356,"lng":-0.6104900000000001},{"lat":45.42528,"lng":-0.60492},{"lat":45.32728,"lng":-0.5657300000000001},{"lat":45.2252,"lng":-0.51543},{"lat":45.168530000000004,"lng":-0.48194000000000004},{"lat":45.08357,"lng":-0.46963000000000005},{"lat":45.025200000000005,"lng":-0.43667000000000006},{"lat":44.97238,"lng":-0.4349},{"lat":44.886300000000006,"lng":-0.5072800000000001},{"lat":44.839180000000006,"lng":-0.50151},{"lat":44.807300000000005,"lng":-0.5280900000000001},{"lat":44.78094,"lng":-0.5795300000000001},{"lat":44.783710000000006,"lng":-0.63139},{"lat":44.731230000000004,"lng":-0.7249300000000001},{"lat":44.64715,"lng":-0.83786},{"lat":44.56958,"lng":-0.8334400000000001},{"lat":44.5133,"lng":-0.8415300000000001},{"lat":44.464980000000004,"lng":-0.8179200000000001},{"lat":44.405860000000004,"lng":-0.8184300000000001},{"lat":44.300760000000004,"lng":-0.8853500000000001},{"lat":44.163340000000005,"lng":-0.9537300000000001},{"lat":44.02908,"lng":-1.01642},{"lat":43.90287,"lng":-1.12832},{"lat":43.85835,"lng":-1.1648},{"lat":43.772290000000005,"lng":-1.2177},{"lat":43.71611,"lng":-1.2279300000000002},{"lat":43.68536,"lng":-1.2592400000000001},{"lat":43.64417,"lng":-1.37325},{"lat":43.584860000000006,"lng":-1.4206100000000002},{"lat":43.54359,"lng":-1.43157},{"lat":43.49893,"lng":-1.4426700000000001},{"lat":43.467020000000005,"lng":-1.48046},{"lat":43.42969,"lng":-1.5860200000000002},{"lat":43.37375,"lng":-1.6586400000000001},{"lat":43.30637,"lng":-1.8888500000000001},{"lat":43.289030000000004,"lng":-1.9363500000000002},{"lat":43.27655,"lng":-1.9982300000000002},{"lat":43.293260000000004,"lng":-2.0439700000000003},{"lat":43.281470000000006,"lng":-2.1159700000000004},{"lat":43.285120000000006,"lng":-2.22881},{"lat":43.270300000000006,"lng":-2.2675300000000003},{"lat":43.27544,"lng":-2.30992},{"lat":43.27279,"lng":-2.36795},{"lat":43.235110000000006,"lng":-2.40384},{"lat":43.17859000000001,"lng":-2.42614},{"lat":43.11639,"lng":-2.42855},{"lat":43.074540000000006,"lng":-2.46124},{"lat":43.02009,"lng":-2.528},{"lat":42.92365,"lng":-2.65465},{"lat":42.91465,"lng":-2.6984800000000004},{"lat":42.89717,"lng":-2.7049100000000004},{"lat":42.880570000000006,"lng":-2.70461},{"lat":42.86084,"lng":-2.7400800000000003},{"lat":42.80828,"lng":-2.8012400000000004},{"lat":42.745960000000004,"lng":-2.8530300000000004},{"lat":42.706810000000004,"lng":-2.88118},{"lat":42.690580000000004,"lng":-2.9910200000000002},{"lat":42.63306,"lng":-3.1089},{"lat":42.620490000000004,"lng":-3.18244},{"lat":42.57016,"lng":-3.2616300000000003},{"lat":42.480140000000006,"lng":-3.4237400000000004},{"lat":42.414970000000004,"lng":-3.5264300000000004},{"lat":42.33138,"lng":-3.63343},{"lat":42.315250000000006,"lng":-3.70265},{"lat":42.24091000000001,"lng":-3.70671},{"lat":42.153710000000004,"lng":-3.7014700000000005},{"lat":42.084500000000006,"lng":-3.7300700000000004},{"lat":42.034200000000006,"lng":-3.7639500000000004},{"lat":42.00439,"lng":-3.7566900000000003},{"lat":41.970870000000005,"lng":-3.7783},{"lat":41.888490000000004,"lng":-3.73944},{"lat":41.838190000000004,"lng":-3.7101200000000003},{"lat":41.713260000000005,"lng":-3.68868},{"lat":41.68318,"lng":-3.72324},{"lat":41.65213000000001,"lng":-3.7228200000000005},{"lat":41.62997,"lng":-3.6958200000000003},{"lat":41.590900000000005,"lng":-3.6981800000000002},{"lat":41.51503,"lng":-3.71708},{"lat":41.459920000000004,"lng":-3.67654},{"lat":41.360200000000006,"lng":-3.6391100000000005},{"lat":41.31909,"lng":-3.62882},{"lat":41.294250000000005,"lng":-3.6043100000000003},{"lat":41.236760000000004,"lng":-3.5891400000000004},{"lat":41.14444,"lng":-3.5826400000000005},{"lat":41.054,"lng":-3.6145300000000002},{"lat":40.976150000000004,"lng":-3.6391000000000004},{"lat":40.920410000000004,"lng":-3.6122500000000004},{"lat":40.869580000000006,"lng":-3.6052800000000005},{"lat":40.80713,"lng":-3.6200300000000003},{"lat":40.745070000000005,"lng":-3.5717900000000005},{"lat":40.699070000000006,"lng":-3.5868400000000005},{"lat":40.67709000000001,"lng":-3.6112900000000003},{"lat":40.62346,"lng":-3.58598},{"lat":40.58062,"lng":-3.5856800000000004},{"lat":40.565810000000006,"lng":-3.6064100000000003},{"lat":40.56517,"lng":-3.6031600000000004}]

See Image:
![route2](https://user-images.githubusercontent.com/15275094/152746102-cc5a987c-7604-4d72-9d9c-d44f7a7a61f3.png)

**Comment by bjornharrtell** [comment]
Seems strange and I have no explanation. Haven't encountered something similar. Can you provide the data converted to GeoJSON? It would increase chances of me diving further into this.

**Comment by Ritzi1708** [comment]
I got this reason for above. So I am using Google maps DirectionsService and it returns as its response an - result.routes[0].overview_path. But this was not the actual path but sort of median.
I am looping through the response's each leg and step to get the actual path. But now it is 67k+ coordinates and buffering the created lineString doesn't return any value(takes forever as it is huge).
