### ISSUE TITLE
overlaps is not a function

### ISSUE THREAD

**Issue by infacto** [bjornharrtell/jsts#457]
Since version 2.x there is no method "overlaps" anymore. For example:

```ts
import * as geom from 'jsts/org/locationtech/jts/geom';

const geometryFactory = new geom.GeometryFactory();
const shell = geometryFactory.createLinearRing(coordinates); // geom.Coordinate(lat,lng)[]
const myPolygon: geom.Polygon geometryFactory.createPolygon(shell, []);

const overlaps = myPolygon.overlaps(anotherPolygon); // <-- overlaps is not a function
```

http://locationtech.github.io/jts/javadoc/
"jsts": "^2.7.1", (now 2.8.1)

It works some versions before. With `import * as jsts from 'jsts'; jsts.geom` This import way is no option anymore (Cannot find module 'jsts').

I can't find any changelog or docs. How do I check two polygons for overlap in the latest version.

Update: Also `getCentroid` is not a function.

**Comment by bjornharrtell** [comment]
See https://github.com/bjornharrtell/jsts#caveats

**Comment by bjornharrtell** [comment]
Does this help?

https://github.com/bjornharrtell/jsts/blob/ffe1e20319e71342ec1ca059fb6da63cd3d1e930/src/org/locationtech/jts/operation/relate/RelateOp.js#L77

**Comment by infacto** [comment]
Yes, it helps. Thanks. Now I know the way to replace it. Currently discover the [monkey.js](https://github.com/bjornharrtell/jsts/blob/2.8.1/src/org/locationtech/jts/monkey.js) to find out the original classes. For example:

https://github.com/bjornharrtell/jsts/blob/82fb99b9a89d4f5bdbb2eedaa692b8d597e67faa/src/org/locationtech/jts/monkey.js#L99

https://github.com/bjornharrtell/jsts/blob/82fb99b9a89d4f5bdbb2eedaa692b8d597e67faa/src/org/locationtech/jts/monkey.js#L65

https://github.com/bjornharrtell/jsts/blob/82fb99b9a89d4f5bdbb2eedaa692b8d597e67faa/src/org/locationtech/jts/monkey.js#L71

etc. I would recommend to add this information to the caveats section of [readme.md](https://github.com/bjornharrtell/jsts#caveats). Just the info where the prototypes come from. The monkey.js.

**Comment by bjornharrtell** [comment]
Good idea and done :)
