### ISSUE TITLE
Does JSTS (JTS) work in a CRS or Cartesian Space?

### ISSUE THREAD

**Issue by ablakey** [bjornharrtell/jsts#458]
Does JSTS/JTS work in a CRS space in degrees, accounting for curvature and such? Or is it all Cartesian math with linear distances in metres or whatnot?  

I've been working with `io.GeoJSONReader` as my data is in GeoJSON Format (but we pretend it's x,y in metres, not lat,lng).

I'm having a problem with `intersects` returning different responses depending on where along a polygon's edge the other polygon touches it.  Got me wondering if coordinate systems are a concern.

**Comment by bjornharrtell** [comment]
It's cartesian only.
