### ISSUE TITLE
404 links

### ISSUE THREAD

**Issue by gregsadetsky** [bjornharrtell/jsts#460]
Hi,

Two small 404 link errors:
- On https://github.com/bjornharrtell/jsts/blob/master/README.md?plain=1#L15 , the link to the JTS Validation Suite is incorrect and should be http://bjornharrtell.github.io/jsts/1.6.1/validationsuite/index.html
- On http://bjornharrtell.github.io/jsts/ , the "this page" link is incorrect and should be https://openlayers.org/en/latest/examples/jsts.html

Cheers!

**Comment by bjornharrtell** [comment]
Thanks for noticing, fixed now.
