### ISSUE TITLE
es6 package missing monkey.js

### ISSUE THREAD

**Issue by deyihu** [bjornharrtell/jsts#463]
https://github.com/bjornharrtell/jsts/blob/92731446a83f44f38cebb021b2e08226a5460f84/src/jsts.js#L16

If users import ES6 packages, some functions will be lost

such as Geometry.buffer

**Comment by bjornharrtell** [comment]
This is intentional and I do not recommend using those methods. See Caveats section.

**Comment by bjornharrtell** [comment]
Oh I see you mean the es6 bundle. That was an experiment and I will remove it.
