### ISSUE TITLE
More complete documentation about partial import

### ISSUE THREAD

**Issue by deyihu** [bjornharrtell/jsts#464]
such as

```js
import { GeoJSONReader, GeoJSONWriter } from 'jsts/org/locationtech/jts/io';

```

If the user does not import monkey JS, leading to incomplete functions
You need to prompt the user to import monkey js

such as 

```js
import { GeoJSONReader, GeoJSONWriter } from 'jsts/org/locationtech/jts/io';
import 'jsts/org/locationtech/jts/monkey';

```

**Comment by bjornharrtell** [comment]
This is intentional and I do not recommend using those methods. See Caveats section.
