### ISSUE TITLE
Polygon object doesn't have a union method

### ISSUE THREAD

**Issue by Zemledelec** [bjornharrtell/jsts#474]
Hi!
I try to make a cascade union with the code:
```
        let arr = new ArrayList();
        arr.addAll(polys);
        let jstsArea = CascadedPolygonUnion.union(arr);
```
where the polys are an array of Polygon instances.
But my polys do not have a union method.

What do I do wrong?

P.S.
I use `UnionOp.union` instead, and it works for me, but `CascadedPolygonUnion` is much more efficient as far as I heard.

**Comment by bjornharrtell** [comment]
Shortcut union method doesn't exist in modern usage of jsts as per https://github.com/bjornharrtell/jsts#caveats. But I don't see how that is relevant here. The example code looks ok, can you provide details about how it fails?

**Comment by Zemledelec** [comment]
Thanks! Here it is:
Jsts Polygon factory:

```
function createPolygonFromLonLatArray(geometryFactory, lonLatArr) {
        let jstsCoords = myLonLatToJstsArray(lonLatArr);
        let shell = geometryFactory.createLinearRing(jstsCoords);
        return geometryFactory.createPolygon(shell);
}
```
ERROR:
OverlapUnion.js?6d2a:130 Uncaught TypeError: geom0.union is not a function
![image](https://user-images.githubusercontent.com/5452251/186141666-fc044cf8-4661-4a49-90d8-f91b38f82017.png)

**Comment by bjornharrtell** [comment]
Ah! That is a bug, unfortunately.

**Comment by Zemledelec** [comment]
It works! Thanks, @bjornharrtell! 

P.S.
Can't promise the tests now. But in my work, I swear the result is the same if I use `UnionOp.union`:)

![image](https://user-images.githubusercontent.com/5452251/186348136-b3cc9802-0964-4b1d-ba23-f139d7e70c18.png)

**Comment by bjornharrtell** [comment]
@Zemledelec thanks :) I'll cut a release shortly.
