### ISSUE TITLE
Cubic Bezier support

### ISSUE THREAD

**Issue by MingyaoLiu** [bjornharrtell/jsts#475]
Hi,
I just want to ask about cubic bezier curve support, I saw in JTS they added CubicBezierClass in Jan this year, file is here: https://github.com/locationtech/jts/blob/master/modules/core/src/main/java/org/locationtech/jts/shape/CubicBezierCurve.java

Is there anyway to officially support this? Or does it require a big upgrade to the base JTS the JSTS depends on, and it won't be very easily done?

Need some advice.
Thanks.

**Comment by bjornharrtell** [comment]
Hi @MingyaoLiu, unfortunately it requires substantial work to upgrade so i'm sorry to say it doesn't look to be happening anytime soon unless someone steps up in a significant way.

**Comment by bjornharrtell** [comment]
Hi @MingyaoLiu, unfortunately it requires substantial work to upgrade so i'm sorry to say it doesn't look to be happening anytime soon unless someone steps up in a significant way.

**Comment by MingyaoLiu** [comment]
Hi @bjornharrtell , thanks for the reply, I have spent some time today translating the java code to js, and also adding type definitions for it. If it runs fine, I will create a pull request.

**Comment by bjornharrtell** [comment]
@MingyaoLiu ok but be aware that the the translation of the jts source is not manual and I'm not keen on accepting PR's with manually translated source. JSTS is transpiled from a patched JTS 1.17 using https://github.com/bjornharrtell/java2estree. Transpiling a later version will require the substantial work... manually translated code can perhaps work but is a nightmare to maintain and trace possible errors for.

**Comment by MingyaoLiu** [comment]
Gotcha, no problem.

**Comment by MingyaoLiu** [comment]
I have added Cubic Bezier to my jsts fork: https://github.com/VolteraInc/jsts

**Comment by bjornharrtell** [comment]
ref https://github.com/bjornharrtell/jsts/issues/488
