### ISSUE TITLE
ConcaveHullOfPolygons

### ISSUE THREAD

**Issue by Processfive** [bjornharrtell/jsts#477]
Hi,

Does jsts contain ConcaveHullOfPolygons? I can't seem to find it.

https://locationtech.github.io/jts/javadoc/org/locationtech/jts/algorithm/hull/ConcaveHullOfPolygons.html

Best regards,

Jeroen.

**Comment by bjornharrtell** [comment]
See https://github.com/bjornharrtell/jsts/issues/425.
