### ISSUE TITLE
Difference and intersection imports

### ISSUE THREAD

**Issue by neocarto** [bjornharrtell/jsts#480]
Make it possible to import intersection and difference operations like this: 
```import IntersectionOp from "jsts/org/locationtech/jts/operation/intersection/IntersectionOp.js";```
```import DifferenceOp from "jsts/org/locationtech/jts/operation/difference/DifferenceOp.js";```
(need for [geotoolbox](https://github.com/neocarto/geotoolbox))

**Comment by bjornharrtell** [comment]
That does not mirror currently transpiled JTS API and AFAIK not the current version JTS API either. So I'm inclined to say no.
