### ISSUE TITLE
missing return in Geometry.toString method

### ISSUE THREAD

**Issue by stringertheory** [bjornharrtell/jsts#483]
https://github.com/bjornharrtell/jsts/blob/f109ab7e8cec4faf1a25f7ba1ca2f00f66620df9/src/org/locationtech/jts/monkey.js#L126-L128

Added it in PR #482.

**Comment by bjornharrtell** [comment]
Thanks, trivial fix so I added it with https://github.com/bjornharrtell/jsts/commit/a7189152429f85040ff216e906b0cb3944cfaf5d.
