### ISSUE TITLE
Observable require jsts > 2.7.0

### ISSUE THREAD

**Issue by neocarto** [bjornharrtell/jsts#486]
jsts = require("jsts@2.7.0") works with Observablehq
jsts = require("jsts@2.9.2") doesn't work

**Comment by neocarto** [comment]
Not sure. I think the pb is this commit. https://github.com/bjornharrtell/jsts/commit/b522f1031631cd6f98aac28cb6b140a46b02d3b3

**Comment by neocarto** [comment]
I confirm that the problem does not come from Observable side.

**Comment by bjornharrtell** [comment]
I would like to have more substantial information to go on. I don't know how to reproduce the problem at all.

**Comment by neocarto** [comment]
What I can say is that it doesn't work anymore from this comit. https://github.com/bjornharrtell/jsts/commit/b522f1031631cd6f98aac28cb6b140a46b02d3b3

**Comment by bjornharrtell** [comment]
What exactly does not work?
