### ISSUE TITLE
Intersection with lines?

### ISSUE THREAD

**Issue by abenrob** [bjornharrtell/jsts#489]
I'm trying to do an intersection between lines and a polygon. It doesn't seem to work - am I doing something wrong, or are lines not supported in this operation?

https://observablehq.com/d/c0d6fd2f4d0174e0

**Comment by bjornharrtell** [comment]
Sorry but this is not a free support forum.

**Comment by abenrob** [comment]
I'm happy to contribute. A simple yes/no would suffice to let me know if I should continue troubleshooting, or consider a feature add.

**Comment by bjornharrtell** [comment]
Yes it is supported. It looks like you are making wrong assumptions on how the API works, i.e you cannot pass on objects of "features" to intersection, it expects a single geometry (which could be a geometrycollection). You also seem to be using a very old version (1.1.1 is from 2016).
