### ISSUE TITLE
LinearRing isRing() function not working

### ISSUE THREAD

**Issue by lfromeroa** [bjornharrtell/jsts#492]
Hello, 

There is a way to validate that a LinearRing is correctly constructed??? I'm trying to use isRing() function from LinearRing class but i get the following error: 

TypeError: this.isSimple is not a function

The idea is to check if the LinearRing is not self intersected.

Thank you.

**Comment by bjornharrtell** [comment]
I think that is a bug. But I'm not sure it would give you the answer you want even if it worked. Instead you could use the IsValidOp operation (https://github.com/bjornharrtell/jsts/blob/master/src/org/locationtech/jts/operation/valid/IsValidOp.js#L100).

**Comment by bjornharrtell** [comment]
Fix in upstream patch https://github.com/bjornharrtell/jts/commit/864dd8527ed4a9eca93d80e8f1da0ce4a4f405ee.
