### ISSUE TITLE
Build the lastest source code in ES5

### ISSUE THREAD

**Issue by Leon-Carto** [bjornharrtell/jsts#493]
Hello, I need to build the source code in ES5 for embedding into my project. I find the rollup.config attaching the babel, and build bundle successfully, but when I run build with my project it failed. Need help to solve the issue. Thanks

```
babel({
      exclude: 'node_modules/**',
      presets: [['@babel/env', {
        targets: {
          browsers: ['>2%', 'not dead']
        }
      }]],
      babelrc: false,
      babelHelpers: 'bundled'
    }),
```
<img width="583" alt="Screen Shot 2023-03-17 at 01 33 32" src="https://user-images.githubusercontent.com/74805596/225719831-d8551b61-20d7-45c4-bca1-49e08db5d4f5.png">

**Comment by bjornharrtell** [comment]
Sorry I think your problem is out of scope of this project.
