### ISSUE TITLE
Problem with ES5 not support LIneMerge

### ISSUE THREAD

**Issue by smartlabDEV** [bjornharrtell/jsts#494]
i try https://unpkg.com/jsts@1.6.1/dist/jsts.min.js but not support LineMerge how an i get this function for ES5? work fine with ES6 but my JS framework i'm using doesn't support ES6.

can a version be made that supports this with ES5?

**Comment by bjornharrtell** [comment]
This project do not have bandwidth to support ES5 builds. Perhaps it is possible to make such a build yourself, or you should upgrade your framework.
