### ISSUE TITLE
RelateOp.contains   fails

### ISSUE THREAD

**Issue by sunishkumar** [bjornharrtell/jsts#497]
lateOp.js:86 Uncaught TypeError: g2.getDimension is not a function
    at RelateOp.contains (RelateOp.js:86:12)

**Comment by bjornharrtell** [comment]
@sunishkumar this does not seem like a general bug, can you provide a test case reproduction?

**Comment by sunishkumar** [comment]
It was my mistake. One of the arguments I was giving Coordinate instead of Point .
