### ISSUE TITLE
import Densifier

### ISSUE THREAD

**Issue by neocarto** [bjornharrtell/jsts#498]
When I import Densifier like this 
```
import Densifier from "jsts/org/locationtech/jts/densify/Densifier"; 
```
It seems that buffer is not imported, even though it is used

**Comment by bjornharrtell** [comment]
Yes seems to be a missing part here, likely caused by missing test coverage and usage/interest of this particular function.

**Comment by neocarto** [comment]
Do you plan to fix this?

**Comment by bjornharrtell** [comment]
Not at this time, but perhaps I will find some time to look into it at some point.

**Comment by bjornharrtell** [comment]
Upstream patch fix by https://github.com/bjornharrtell/jts/commit/c64bf0666fa0996fbb6f8d4113954a09a782631d.

**Comment by neocarto** [comment]
Thank you
