### ISSUE TITLE
GeometryMapper class missing flatMap function.

### ISSUE THREAD

**Issue by Angusross111** [bjornharrtell/jsts#501]
In the latest release `OffsetCurve` and `CubicBezierCurve` both call a function `flatMap` on the class `GeometryMapper` [here](https://github.com/search?q=repo%3Abjornharrtell%2Fjsts%20GeometryMapper.flatMap&type=code), but that function does not exist in the [GeometryMapper class](https://github.com/bjornharrtell/jsts/blob/master/src/org/locationtech/jts/geom/util/GeometryMapper.js#L5).

**Comment by bjornharrtell** [comment]
Hmm these have been included by mistake and are part of newer JTS that I'm currently not able to transpile properly. See https://github.com/bjornharrtell/jsts/issues/488.

Probably they have been introduced by some attempt to transpile newer code that I reverted. I will have to revisit and clean it up.

I'm curious how you found these extra non working parts @Angusross111? Actively looking for them to be properly ported?

**Comment by Angusross111** [comment]
Ok that makes sense. It was by chance, I have been migrating some code from python that used shapely to JavaScript, and had a function using offset curve, so I had a quick search through the source code after seeing the latest update and found the code. 
I though it was a bit strange that you hadn’t closed issue 488.

**Comment by bjornharrtell** [comment]
I definitely accidentally left some test transpilation in there. Removed with https://github.com/bjornharrtell/jsts/commit/0ae8b18d05d84e6b0221ce160a5252898d64ca9e.

Sorry for misleading you into thinking it was available.
