### ISSUE TITLE
TypeError: Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by adrianmfi** [bjornharrtell/jsts#502]
Hi, thanks for the awesome work porting jts.

I've just attempted updating from `jsts@2.9.3` to `jsts@2.10.0` using npm, and get the following error when loading the module.

```
TypeError: Class extends value undefined is not a constructor or null
at LinearRing.js:6:41
```

The import of `LineString` has become `undefined`:
![image](https://github.com/bjornharrtell/jsts/assets/12783483/f7ba5564-34a0-4757-82ad-b3a872a653d4)

Other imports in the same file is defined:
![image](https://github.com/bjornharrtell/jsts/assets/12783483/ed2feef8-826c-4cee-ba4d-403fa6a7fe3f)

When using jsts 2.9.3, `LineString` is defined:

![image](https://github.com/bjornharrtell/jsts/assets/12783483/798ff991-bb13-4193-9350-d2c9b6cc0010)

Any idea what might be the cause?

**Comment by bjornharrtell** [comment]
Thanks for reporting. Not sure why this is happening and certainly not sure why it's not found by test cases or somewhere else (yet). The only thing that comes to mind that could cause undefined import is in some cases of circular dependency but I'm not sure what would introduce that in 2.10.0. If you can provide a full reproduction in a public git repo that could help get to the bottom of this.

**Comment by bjornharrtell** [comment]
I've tried to make a reproduction at https://github.com/bjornharrtell/jsts-issue-502 but it works as expected no import issues and runs fine outputting the expected `LINESTRING (1 1, 2 2)`, so I really need your help with a reproduction.

**Comment by adrianmfi** [comment]
I spent some some time trying to reproduce minimally, and it turns out that it was my fault, my apologies.

The cause was, as you suggested, a circular import issue, which I inadvertently introduced as part of upgrading.
I think the reason why I did not observe the error on v2.9.3 is that I'm using [Vite with dependency pre-bundling](https://vitejs.dev/guide/dep-pre-bundling.html), where the cached version of jsts@2.9.3 did not have the circular import, or something along those lines.
When disabling browser cache, and thus forcing the browser to fetch the newest bundle, I observe the error on v 2.9.3 as well.

Removing the circular import and I no longer get the error.

Thanks for pointing me in the direction of circular imports and once again sorry for the inconvenience!

**Comment by adrianmfi** [comment]
A quick follow up, this seems to have been caused because I was using
`import { GeometryFactory } from 'jsts/org/locationtech/jts/geom';`
style imports, but only for dependencies optimized by `vite`. 
Changing to 
`import GeometryFactory from 'jsts/org/locationtech/jts/geom/GeometryFactory';`
and the issue was resolved.
