### ISSUE TITLE
Difference is not working with complex GeoJSON Polygons

### ISSUE THREAD

**Issue by Stophface** [bjornharrtell/jsts#504]
I think jsts is failing with the difference function on complex GeoJSONs.
I have these two GeoJSON

**worldCover**

    const a = {"type":"Feature","properties":{},"geometry":{"type":"Polygon","coordinates":[[[-180,-90],[180,-90],[180,90],[-180,90],[-180,-90]]]}}

**complexGeojson**

    const b = {"type":"Feature","geometry":{"type":"MultiPolygon","coordinates":[[[[102,2],[103,2],[103,3],[102,3],[102,2]]],[[[100,0],[101,0],[101,1],[100,1],[100,0]],[[100.2,0.2],[100.2,0.8],[100.8,0.8],[100.8,0.2],[100.2,0.2]]],[[[100.3,0.3],[100.7,0.3],[100.7,0.7],[100.3,0.7],[100.3,0.3]],[[100.4305160192801,0.67817296142852],[100.42176614977494,0.6777431305923907],[100.41310055071305,0.6764577778174132],[100.40460268077847,0.6743292824257617],[100.39635438296318,0.6713781440787653],[100.38843509621175,0.667632785305691],[100.3809210902431,0.6631292777150927],[100.37388473092459,0.6579109945286342],[100.36739378327755,0.6520281927874465],[100.36151075883018,0.6455375292587178],[100.35629231360264,0.6385015147088778],[100.35178870252209,0.6309879118031904],[100.34804329551801,0.6230690824341718],[100.34509215995416,0.6148212907677792],[100.34296371341229,0.6063239687221135],[100.34167845016515,0.5976589509544159],[100.34124874396572,0.5889096867249723],[100.34167872904445,0.5801604362283926],[100.34296426045371,0.5714954591315431],[100.34509295413531,0.56299820313176],[100.34804430631903,0.5547505003481902],[100.35178989109856,0.5468317792832317],[100.35629363427834,0.5393182999407915],[100.36151216085236,0.5322824194649319],[100.3673952127673,0.5257918953685367],[100.37388613294743,0.5199092330597317],[100.38092241092006,0.5146910839473947],[100.38843628478985,0.5101876999202546],[100.39635539376593,0.5064424494514895],[100.40460347496123,0.503491399987565],[100.41310109775573,0.5013629706420072],[100.42176642865488,0.5000776585380188],[100.4305160192801,0.49964784143480295],[100.43926560990533,0.5000776585380188],[100.4479309408045,0.5013629706420072],[100.45642856359898,0.503491399987565],[100.46467664479428,0.5064424494514895],[100.47259575377038,0.5101876999202546],[100.48010962764015,0.5146910839473947],[100.48714590561279,0.5199092330597317],[100.4936368257929,0.5257918953685365],[100.49951987770788,0.5322824194649319],[100.50473840428187,0.5393182999407914],[100.50924214746165,0.5468317792832317],[100.51298773224117,0.5547505003481902],[100.51593908442491,0.56299820313176],[100.51806777810651,0.5714954591315431],[100.51935330951578,0.5801604362283926],[100.51978329459449,0.5889096867249723],[100.51935358839506,0.5976589509544159],[100.51806832514795,0.6063239687221135],[100.51593987860606,0.6148212907677792],[100.5129887430422,0.6230690824341719],[100.50924333603814,0.6309879118031904],[100.50473972495757,0.6385015147088778],[100.49952127973005,0.6455375292587178],[100.49363825528266,0.6520281927874464],[100.48714730763562,0.6579109945286341],[100.48011094831709,0.6631292777150927],[100.47259694234847,0.667632785305691],[100.46467765559704,0.6713781440787653],[100.45642935778174,0.6743292824257617],[100.44793148784716,0.6764577778174132],[100.43926588878527,0.6777431305923907],[100.4305160192801,0.67817296142852]]],[[[101.2,0.2],[101.8,0.2],[101.8,0.8],[101.2,0.8],[101.2,0.2]],[[101.3,0.3],[101.3,0.7],[101.7,0.7],[101.7,0.3],[101.3,0.3]]]]},"properties":{"name":"Dinagat Islands"}}

I am using [this version of jsts](https://unpkg.com/jsts@1.6.1/dist/jsts.min.js) and I am trying to use the `difference()` method. 
I want to go from this

<img width="645" alt="Screenshot 2023-08-27 at 12 09 43" src="https://github.com/bjornharrtell/jsts/assets/8275981/6a75dfbe-2168-48b7-abca-1dbdac15065a">

to this

<img width="653" alt="Screenshot 2023-08-27 at 12 10 11" src="https://github.com/bjornharrtell/jsts/assets/8275981/eaf6edc9-f3c1-453d-a7df-c200ebff12ad">

According to the docs, this should work like this

```
const reader = new jsts.io.GeoJSONReader();
const worldCover = reader.read(JSON.parse(a))
const complexGeojson = reader.read(JSON.parse(b))
const difference = jsts.operation.overlay.OverlayOp.difference(complexGeojson, worldCover)
```

But, this gives me 

> t.isEmpty is not a function

**Comment by bjornharrtell** [comment]
1.6.1 is a five year old version. Feel free to request this to be reopened if you reproduce with a recent version.

**Comment by Stophface** [comment]
This is also happening with [this version ](https://unpkg.com/jsts@2.10.1/dist/jsts.min.js)
I created a [fiddle](https://jsfiddle.net/Jodelkraeh/tha5g17r/36/)

**Comment by bjornharrtell** [comment]
@Stophface the problem is that GeoJSONReader isn't able to parse features. Documentation says it should be able and mabye it's become broken at some point.. however, since JTS/JSTS is about geometries not features it not a use case I feel is very important. As far as I can tell it works fine if you modify the GeoJSON to be geometry fragments instead.

**Comment by Stophface** [comment]
@bjornharrtell Thanks for your response. Could you elaborate what you mean by: "As far as I can tell it works fine if you modify the GeoJSON to be geometry fragments instead."?

**Comment by bjornharrtell** [comment]
a geojson feature:

```json
{
  "type": "Feature",
  "geometry": {
    "type": "Point",
    "coordinates": [125.6, 10.1]
  },
  "properties": {
    "name": "Dinagat Islands"
  }
}
```

a geojson geometry:
```json
{
  "type": "Point",
  "coordinates": [125.6, 10.1]
}
```

**Comment by Stophface** [comment]
@bjornharrtell Thanks for sticking with me. So its basically just, whats available through the geometry key. I'll check that out and let you know!

**Comment by Stophface** [comment]
@bjornharrtell Still no luck. There are my *geometries* now

```
const complexGeometry = JSON.parse('{"type":"MultiPolygon","coordinates":[[[[102,2],[103,2],[103,3],[102,3],[102,2]]],[[[100,0],[101,0],[101,1],[100,1],[100,0]],[[100.2,0.2],[100.2,0.8],[100.8,0.8],[100.8,0.2],[100.2,0.2]]],[[[100.3,0.3],[100.7,0.3],[100.7,0.7],[100.3,0.7],[100.3,0.3]],[[100.4305160192801,0.67817296142852],[100.42176614977494,0.6777431305923907],[100.41310055071305,0.6764577778174132],[100.40460268077847,0.6743292824257617],[100.39635438296318,0.6713781440787653],[100.38843509621175,0.667632785305691],[100.3809210902431,0.6631292777150927],[100.37388473092459,0.6579109945286342],[100.36739378327755,0.6520281927874465],[100.36151075883018,0.6455375292587178],[100.35629231360264,0.6385015147088778],[100.35178870252209,0.6309879118031904],[100.34804329551801,0.6230690824341718],[100.34509215995416,0.6148212907677792],[100.34296371341229,0.6063239687221135],[100.34167845016515,0.5976589509544159],[100.34124874396572,0.5889096867249723],[100.34167872904445,0.5801604362283926],[100.34296426045371,0.5714954591315431],[100.34509295413531,0.56299820313176],[100.34804430631903,0.5547505003481902],[100.35178989109856,0.5468317792832317],[100.35629363427834,0.5393182999407915],[100.36151216085236,0.5322824194649319],[100.3673952127673,0.5257918953685367],[100.37388613294743,0.5199092330597317],[100.38092241092006,0.5146910839473947],[100.38843628478985,0.5101876999202546],[100.39635539376593,0.5064424494514895],[100.40460347496123,0.503491399987565],[100.41310109775573,0.5013629706420072],[100.42176642865488,0.5000776585380188],[100.4305160192801,0.49964784143480295],[100.43926560990533,0.5000776585380188],[100.4479309408045,0.5013629706420072],[100.45642856359898,0.503491399987565],[100.46467664479428,0.5064424494514895],[100.47259575377038,0.5101876999202546],[100.48010962764015,0.5146910839473947],[100.48714590561279,0.5199092330597317],[100.4936368257929,0.5257918953685365],[100.49951987770788,0.5322824194649319],[100.50473840428187,0.5393182999407914],[100.50924214746165,0.5468317792832317],[100.51298773224117,0.5547505003481902],[100.51593908442491,0.56299820313176],[100.51806777810651,0.5714954591315431],[100.51935330951578,0.5801604362283926],[100.51978329459449,0.5889096867249723],[100.51935358839506,0.5976589509544159],[100.51806832514795,0.6063239687221135],[100.51593987860606,0.6148212907677792],[100.5129887430422,0.6230690824341719],[100.50924333603814,0.6309879118031904],[100.50473972495757,0.6385015147088778],[100.49952127973005,0.6455375292587178],[100.49363825528266,0.6520281927874464],[100.48714730763562,0.6579109945286341],[100.48011094831709,0.6631292777150927],[100.47259694234847,0.667632785305691],[100.46467765559704,0.6713781440787653],[100.45642935778174,0.6743292824257617],[100.44793148784716,0.6764577778174132],[100.43926588878527,0.6777431305923907],[100.4305160192801,0.67817296142852]]],[[[101.2,0.2],[101.8,0.2],[101.8,0.8],[101.2,0.8],[101.2,0.2]],[[101.3,0.3],[101.3,0.7],[101.7,0.7],[101.7,0.3],[101.3,0.3]]]]}')

const coverGeometry = JSON.parse('{"coordinates":[[[-180,-90],[180,-90],[180,90],[-180,90],[-180,-90]]],"type":"Polygon"}')

const difference = jsts.operation.overlay.OverlayOp.difference(complexGeometry, coverGeometry)

```

Here is an updated [fiddle](https://jsfiddle.net/Jodelkraeh/tha5g17r/47/)

I wonder if this is because there are holes in my polygons, which again have holes, or better: islands in islands, which the algorithm cannot process?

**Comment by bjornharrtell** [comment]
No the problem is now that you for some reason removed the GeoJSONReader...

**Comment by Stophface** [comment]
@bjornharrtell Ah, sorry. I thought now that it is not a GeoJSON anymore, I do not need the reader...

I added

```
const reader = new jsts.io.GeoJSONReader();
const writer = new jsts.io.GeoJSONWriter();
const coverJsts = reader.read(coverGeometry)
const complexGeometryJsts = reader.read(complexGeometry)
const difference = jsts.operation.overlay.OverlayOp.difference(coverJsts, complexGeometryJsts)
const result = writer.write(difference)
```

and it seems to work :) I was banging my head against writing an algorithm myself that mask/clip (here: difference) very complex geomtries! This library is a lifesaver! <3
