### ISSUE TITLE
Package does not work on AWS lambda

### ISSUE THREAD

**Issue by karimfayed** [bjornharrtell/jsts#509]
I have all my dependencies uploaded to a Lamda layer, but when it came to JSTS Iambda is always unable to find the module while the rest of my dependencies work fine.

Here is the error that keeps on popping:

`"errorType": "Runtime.ImportModuleError", "errorMessage": "Error: Cannot find module 'jsts'\nRequire stack:\n- /var/task/validators.js\n- /var/task/utils.js\n- /var/task/getFeature.js\n- /var/task/index.js\n- /var/runtime/index.mjs", "stack": [ "Runtime.ImportModuleError: Error: Cannot find module 'jsts'", "Require stack:", "- /var/task/validators.js", "- /var/task/utils.js", "- /var/task/getFeature.js", "- /var/task/index.js", "- /var/runtime/index.mjs", " at _loadUserApp (file:///var/runtime/index.mjs:1061:17)", " at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1093:21)", " at async start (file:///var/runtime/index.mjs:1256:23)", " at async file:///var/runtime/index.mjs:1262:1" ] }`

Is there a reason behind this?

**Comment by bjornharrtell** [comment]
No.
