### ISSUE TITLE
Package problem with AWS lambda

### ISSUE THREAD

**Issue by monasser112** [bjornharrtell/jsts#510]
I am facing a problem with using this package in AWS lambda layer.
I have exactly the same problem found [in this issue](https://github.com/bjornharrtell/jsts/issues/509)
My current OS is windows 11.

I think this needs to be investigated as it seems that this recurring problem. 

Waiting for your feedback. Thanks for your time.

**Comment by bjornharrtell** [comment]
You are welcome to investigate. As this seems to be an issue with AWS lamda I will close until proven otherwise.
