### ISSUE TITLE
Invalid number of points in LinearRing

### ISSUE THREAD

**Issue by Ryszard-Trojnacki** [bjornharrtell/jsts#511]
I'm trying to create `LinearRing` (`Polygon`) from array of `CoordinatesXY` but I get exception:
`IllegalArgumentException: Invalid number of points in LinearRing (found 3 - must be 0 or >= 4)`

Why there is a minimum of 4 points? Isn't triangle a valid `LinearRing`?

Another thing - Java implementation (JTS) requires only 3 points.

[JavaScript constant definition](https://github.com/bjornharrtell/jsts/blob/e18f6e86c4ba9f7cda3cbce39b0e590625982c43/src/org/locationtech/jts/geom/LinearRing.js#L48C1-L48C34) and validate method:
```javascript
LinearRing.MINIMUM_VALID_SIZE = 4

validateConstruction() {
    if (!this.isEmpty() && !super.isClosed.call(this)) 
      throw new IllegalArgumentException('Points of LinearRing do not form a closed linestring')
    
    if (this.getCoordinateSequence().size() >= 1 && this.getCoordinateSequence().size() < LinearRing.MINIMUM_VALID_SIZE) 
      throw new IllegalArgumentException('Invalid number of points in LinearRing (found ' + this.getCoordinateSequence().size() + ' - must be 0 or >= 4)')
    
  }
```

[Java constant definition](https://github.com/locationtech/jts/blob/52e19880a045c90991f17b2cc655abd94117622b/modules/core/src/main/java/org/locationtech/jts/geom/LinearRing.java#L38) and validate method:
```java
public class LinearRing extends LineString {
  public static final int MINIMUM_VALID_SIZE = 3;

  private void validateConstruction() {
    if (!isEmpty() && ! super.isClosed()) {
      throw new IllegalArgumentException("Points of LinearRing do not form a closed linestring");
    }
    if (getCoordinateSequence().size() >= 1 && getCoordinateSequence().size() < MINIMUM_VALID_SIZE) {
      throw new IllegalArgumentException("Invalid number of points in LinearRing (found "
      		+ getCoordinateSequence().size() + " - must be 0 or >= " + MINIMUM_VALID_SIZE + ")");
    }
  }
}
```
Shouldn't this be changed to `3` like in Java code?

**Comment by Ryszard-Trojnacki** [comment]
I see that in Java this code was [changed](https://github.com/locationtech/jts/pull/682) from 4 to 3.

**Comment by bjornharrtell** [comment]
@Ryszard-Trojnacki I guess the definition is that it needs to be a closed ring in which case a triangle would be defined by 4 points. As seen in the pull request in JTS it was lowered with the intent to be able to create *invalid* rings.
