### ISSUE TITLE
How to access the contains method of the JSTS Geometry class

### ISSUE THREAD

**Issue by vaishnavravi33** [bjornharrtell/jsts#512]
Previously it was working. After migration from angular v9 to angular v13.

I am stuck with JSTS import in angular v13.  I was getting the error "Error: Module not found: Error: Can't resolve 'jsts'". To resolve this issue I imported the JSTS as below -

```
import * as io from 'jsts/org/locationtech/jts/io';
const parser = new io.OL3Parser();
```

So, now the above code is working but facing the issue with "contains method of the JSTS Geometry class". While accessing the contains on geometry class it is giving the error "ERROR TypeError: GeomA.contains is not a function".

```
import * as io from 'jsts/org/locationtech/jts/io';

const parser = new io.OL3Parser();

parser.inject(
  Point,
  LineString,
  LinearRing,
  Polygon,
  MultiPoint,
  MultiLineString,
  MultiPolygon,
  GeometryCollection
);

let GeomA = parser.read(featureA.getGeometry());
let GeomB = parser.read(featureB.getGeometry());
let isGeomAContainsGeomB = GeomA.contains(GeomB); <--- **Error**
```

**My Environment -**
Angular: 13.4.0
Angular CLI: 13.3.11
typescript: 4.6.4
Node: 19.4.0 (Unsupported)
Package Manager: npm 9.2.0
OS: win32 x64

Need help in this matter please.

**Comment by bjornharrtell** [comment]
Read the https://github.com/bjornharrtell/jsts?tab=readme-ov-file#caveats (last bullet point).

**Comment by bjornharrtell** [comment]
More specific hint is this:

https://github.com/bjornharrtell/jsts/blob/master/src/org/locationtech/jts/operation/relate/RelateOp.js#L88

**Comment by vaishnavravi33** [comment]
> More specific hint is this:
> 
> https://github.com/bjornharrtell/jsts/blob/master/src/org/locationtech/jts/operation/relate/RelateOp.js#L88

Thank you for the quick response. It works now.
