### ISSUE TITLE
Wrong types in index.d.ts

### ISSUE THREAD

**Issue by doskabouter** [bjornharrtell/jsts#514]
Not sure if that is supposed to be fixed in this repo, but there are a couple of issues with the index.d.ts that is installed from npm.
- CoordinateSequence is just a struct, shouldn't that be an array of Coordinate?
- the overloads (f.e. the bufferOp,bufferOp2,bufferOp3) could be changed into one method with union-types for the parameters
- The OverlayOp.intersection(Geometry,Geometry) is missing
- The Quadtree is missing

**Comment by bjornharrtell** [comment]
I have no knowledge of those types and they are not coming from this project. I would suggest not using them.
