### ISSUE TITLE
Error using MaximumInscribedCircle 

### ISSUE THREAD

**Issue by doskabouter** [bjornharrtell/jsts#516]
It seems to pull in the PriorityQueue, but that references ArrayList as ../../../../java/util/ArrayList.js which can;t be found (https://github.com/bjornharrtell/jsts/blob/9131e8308206b8a024564b7482a6f248aa344160/src/java/util/PriorityQueue.js#L1)
shouldn't that be just ./ArrayList.js?

And if its not too much trouble can you release this fix on npm too?

**Comment by bjornharrtell** [comment]
Indeed it should be just `/ArrayList.js`. Not sure how that slipped through... and why it's not a cause of other issues.

Unfortunately it doesn't make MaximumInscribedCircle work. Seems MaximumInscribedCircle has never been tested and will require more work.

**Comment by bjornharrtell** [comment]
Looks like I found out how to fix it. I'll try to get a release to npm in a near future.

**Comment by bjornharrtell** [comment]
Published as 2.11.2

**Comment by doskabouter** [comment]
Thank you very much!
