### ISSUE TITLE
TS7016: Could not find a declaration file for module

### ISSUE THREAD

**Issue by YuriiDmytryshyn** [bjornharrtell/jsts#523]
Angular 16
node v20.9.0
npm 10.1.0
jsts 2.11.3
<img width="951" alt="Screenshot 2024-07-30 at 17 04 26" src="https://github.com/user-attachments/assets/d507354a-ef42-4947-b86c-6e46a8280f2f">

import OL3Parser from 'jsts/org/locationtech/jts/io/OL3Parser';
export class **** {
  const parserFromOL3 = new OL3Parser();
}

**Comment by bjornharrtell** [comment]
JSTS do not supply type definitions, see https://github.com/bjornharrtell/jsts/issues/285.
