### ISSUE TITLE
Fix geometries in order to make them valid

### ISSUE THREAD

**Issue by fjacupar** [bjornharrtell/jsts#526]
Hello @bjornharrtell,

I am currently using the library to do some topology validation of features/geometries coming from geojson. There are some of them that are not valid for the library because they have holes inside or the geometry crosses itself. Is there any possibility to fix or make these geometries valid with library JSTS? I know JTS has a class GeometryFixer to make invalid geometries valid.

Thanks in advance

**Comment by bjornharrtell** [comment]
It's not available because newer versions of JTS hasn't been ported at this time, see https://github.com/bjornharrtell/jsts/issues/488.
