### ISSUE TITLE
JSTS within Angular

### ISSUE THREAD

**Issue by bad-ch** [bjornharrtell/jsts#528]
Technical stack;
- Angular 17
- Typescript 5.4.5
- JSTS version 2.12.1 (npm install jsts)
- @types/jsts version 0.17.24 () (npm install @types/jsts)

Source code:
[jsts.js.txt](https://github.com/user-attachments/files/18021668/jsts.js.txt)

In VsCode I get no errors, but during build the following ones (**I list only some examples get's lots more**):

Error: node_modules/jsts/types/org/locationtech/jts/geom/MultiPolygon.d.ts:3:9 - error TS2416: Property 'interfaces_' in type 'MultiPolygon' is not assignable to the same property in base type 'GeometryCollection'.
  Type '(typeof Polygonal)[]' is not assignable to type '(() => void)[]'.

3     get interfaces_(): (typeof Polygonal)[];

Error: node_modules/jsts/types/org/locationtech/jts/geom/MultiPolygon.d.ts:2:5 - error TS2416: Property 'copyInternal' in type 'MultiPolygon' is not assignable to the same property in base type 'GeometryCollection'.
  Type '() => MultiPolygon' is not assignable to type '() => GeometryCollection'.
    Call signature return types 'MultiPolygon' and 'GeometryCollection' are incompatible.
      The types of 'interfaces_' are incompatible between these types.
        Type '(typeof Polygonal)[]' is not assignable to type '(() => void)[]'.
          Type 'typeof Polygonal' is not assignable to type '() => void'.
            Type 'typeof Polygonal' provides no match for the signature '(): void'.

2     copyInternal(): MultiPolygon;
      ~~~~~~~~~~~~

Any idreas ?

**Comment by bjornharrtell** [comment]
Hmm looks like TypeScript issues, that is likely related to the generated types introduced in the latest version. Since they are directly from the TypeScript compiler I would assume they would "just work".

I no Angular knowledge or wish to have but if this is a real issue it should be reproducable without Angular. I will try to find time to look into it, but efforts to provide a good isolated reproduction would be helpful.

**Comment by bad-ch** [comment]
Only for your information with version 2.11.3 everything works properly

**Comment by bjornharrtell** [comment]
That's not unexpected because that version did not have any types.

**Comment by bad-ch** [comment]
As soon as I update to Angular 18/19 the jsts version 2.12.1 works again (typescript version is 5.6.2) => perhaps a comment in the release notes ? In my opinion the issue is solved. Investigation make no sense. But Thx for your feedback.

**Comment by bjornharrtell** [comment]
That's good to know, so it's a TypeScript version compatibility issue.
