### ISSUE TITLE
ExtractLineByLocation is missing in linearref (not exported)

### ISSUE THREAD

**Issue by bad-ch** [bjornharrtell/jsts#529]
ExtractLineByLocation is not exported in the script linearref.js, the class ExtractLineByLocation is availeable in the folder struture. Is it possible to fix that on the version 2.11.3 as well ?

**Comment by bjornharrtell** [comment]
Nah, the rexporting stuff was made for the single file build and might be removed in the future. Just import the module directly.

**Comment by bad-ch** [comment]
That I have already done, but Thx
